// Edition-isolated Fighter rules used by generation, validation, references, and class sheets.
const P2014=Object.freeze({
1:{actionSurge:0,indomitable:0,attacks:1,features:["Fighting Style","Second Wind"]},2:{actionSurge:1,indomitable:0,attacks:1,features:["Action Surge"]},3:{actionSurge:1,indomitable:0,attacks:1,features:["Martial Archetype"]},4:{actionSurge:1,indomitable:0,attacks:1,features:["Ability Score Improvement"]},5:{actionSurge:1,indomitable:0,attacks:2,features:["Extra Attack"]},6:{actionSurge:1,indomitable:0,attacks:2,features:["Ability Score Improvement"]},7:{actionSurge:1,indomitable:0,attacks:2,features:["Martial Archetype Feature"]},8:{actionSurge:1,indomitable:0,attacks:2,features:["Ability Score Improvement"]},9:{actionSurge:1,indomitable:1,attacks:2,features:["Indomitable"]},10:{actionSurge:1,indomitable:1,attacks:2,features:["Martial Archetype Feature"]},11:{actionSurge:1,indomitable:1,attacks:3,features:["Extra Attack (2)"]},12:{actionSurge:1,indomitable:1,attacks:3,features:["Ability Score Improvement"]},13:{actionSurge:1,indomitable:2,attacks:3,features:["Indomitable"]},14:{actionSurge:1,indomitable:2,attacks:3,features:["Ability Score Improvement"]},15:{actionSurge:1,indomitable:2,attacks:3,features:["Martial Archetype Feature"]},16:{actionSurge:1,indomitable:2,attacks:3,features:["Ability Score Improvement"]},17:{actionSurge:2,indomitable:3,attacks:3,features:["Action Surge","Indomitable"]},18:{actionSurge:2,indomitable:3,attacks:3,features:["Martial Archetype Feature"]},19:{actionSurge:2,indomitable:3,attacks:3,features:["Ability Score Improvement"]},20:{actionSurge:2,indomitable:3,attacks:4,features:["Extra Attack (3)"]}
});
const SECOND_WIND=[2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4],MASTERY=[3,3,3,4,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6];
const P2024=Object.freeze(Object.fromEntries(Array.from({length:20},(_,i)=>{const level=i+1,features=level===1?["Fighting Style","Second Wind","Weapon Mastery"]:[];if(level===2)features.push("Action Surge","Tactical Mind");if(level===3)features.push("Fighter Subclass");if([4,6,8,12,14,16].includes(level))features.push("Ability Score Improvement");if(level===5)features.push("Extra Attack","Tactical Shift");if(level===9)features.push("Indomitable","Tactical Master");if(level===11)features.push("Two Extra Attacks");if(level===13)features.push("Indomitable","Studied Attacks");if(level===17)features.push("Action Surge","Indomitable");if(level===19)features.push("Epic Boon");if(level===20)features.push("Three Extra Attacks");return[level,{secondWind:SECOND_WIND[i],masteries:MASTERY[i],actionSurge:level>=17?2:level>=2?1:0,indomitable:level>=17?3:level>=13?2:level>=9?1:0,attacks:level>=20?4:level>=11?3:level>=5?2:1,features}];})));
const CHAMPION_2014=Object.freeze([{level:3,name:"Improved Critical"},{level:7,name:"Remarkable Athlete"},{level:10,name:"Additional Fighting Style"},{level:15,name:"Superior Critical"},{level:18,name:"Survivor"}]);
const CHAMPION_2024=Object.freeze([{level:3,name:"Improved Critical"},{level:3,name:"Remarkable Athlete"},{level:7,name:"Additional Fighting Style"},{level:10,name:"Heroic Warrior"},{level:15,name:"Superior Critical"},{level:18,name:"Survivor"}]);
function tableFor(ruleset){if(ruleset==="2014")return P2014;if(ruleset==="2024")return P2024;throw new Error(`Unsupported Fighter ruleset: ${ruleset}`);}
export function fighterProgression(ruleset,level){try{const numeric=Number(level);if(!Number.isInteger(numeric)||numeric<1||numeric>20)throw new Error(`Fighter level must be an integer from 1 to 20: ${level}`);return structuredClone(tableFor(ruleset)[numeric]);}catch(error){console.error("[fighter] progression lookup failed",error);throw error;}}
export function fighterFeatures(ruleset,level,subclassId){try{const numeric=Number(level),features=[];for(let current=1;current<=numeric;current++)features.push(...tableFor(ruleset)[current].features);if(subclassId&&subclassId!=="champion")throw new Error(`Unsupported Fighter subclass for ${ruleset}: ${subclassId}`);const subclass=ruleset==="2014"?CHAMPION_2014:CHAMPION_2024;if(subclassId)for(const feature of subclass)if(numeric>=feature.level)features.push(feature.name);return[...new Set(features)].filter(name=>!["Martial Archetype Feature"].includes(name));}catch(error){console.error("[fighter] feature resolution failed",error);throw error;}}
export function fighterResources(ruleset,level){try{const row=fighterProgression(ruleset,level),resources=[];if(ruleset==="2024")resources.push({id:"second-wind",name:"Second Wind",value:String(row.secondWind),detail:"Regain one expended use on a Short Rest; all on a Long Rest."});else resources.push({id:"second-wind",name:"Second Wind",value:"1",detail:"Regain after a Short or Long Rest."});if(row.actionSurge)resources.push({id:"action-surge",name:"Action Surge",value:String(row.actionSurge),detail:"Uses before a Short or Long Rest; from level 17, no more than once per turn."});if(row.indomitable)resources.push({id:"indomitable",name:"Indomitable",value:String(row.indomitable),detail:ruleset==="2024"?"Uses per Long Rest; reroll a failed save with a bonus equal to Fighter level.":"Uses per Long Rest; reroll a failed saving throw and use the new roll."});if(ruleset==="2024")resources.push({id:"weapon-masteries",name:"Weapon Masteries",value:String(row.masteries),detail:"Chosen proficient weapons whose mastery properties you can use."});resources.push({id:"attacks-per-action",name:"Attacks / Attack Action",value:String(row.attacks),detail:"Current Fighter Extra Attack progression."});return resources;}catch(error){console.error("[fighter] resource build failed",error);throw error;}}
export const FIGHTER_TABLES=Object.freeze({"2014":P2014,"2024":P2024});
