import { RANDOM, SOURCE, ABILITIES, SKILLS } from "../schema.js";
import { FORGE_2014, FORGE_2024 } from "../data/forge-data.js";
import { LANGUAGES_2014 } from "../data/species-2014.js";
import { pick, sample } from "./random.js";
import { generateBaseAbilities, apply2014Species, apply2024Background } from "./abilities.js";
import { abilityMod, proficiencyBonus } from "./math.js";
import { fighterFeatures, wizardFeatures, clericFeatures, rogueFeatures, applyEpicBoonAbility } from "./features.js";
import { resolveClassAdvancements } from "./advancement-feats.js";
import { barbarianFeatures } from "./barbarian-features.js";
import { barbarianProgressionFor, applyPrimalChampion } from "./barbarian.js";
import { validateBarbarianCharacter } from "./barbarian-validation.js";
import { bardFeatures } from "./bard-features.js";
import { bardProgressionFor } from "./bard.js";
import { resolveBardExpertise, resolveBardInstruments, resolveLoreBonusSkills } from "./bard-selections.js";
import { validateBardCharacter } from "./bard-validation.js";
import { buildBardSpellcasting } from "./bard-spellcasting.js";
import { monkFeatures } from "./monk-features.js";
import { applyBodyAndMind, monkProgressionFor } from "./monk.js";
import { resolveMonkEquipment, resolveMonkTool } from "./monk-selections.js";
import { sorcererFeatures } from "./sorcerer-features.js";
import { sorcererProgressionFor } from "./sorcerer.js";
import { resolveSorcererSelections } from "./sorcerer-selections.js";
import { buildSorcererSpellcasting } from "./sorcerer-spellcasting.js";
import { validateSorcererCharacter } from "./sorcerer-validation.js";
import { warlockFeatures } from "./warlock-features.js";
import { warlockProgressionFor } from "./warlock.js";
import { resolveWarlockSelections } from "./warlock-selections.js";
import { buildWarlockSpellcasting } from "./warlock-spellcasting.js";
import { validateWarlockCharacter } from "./warlock-validation.js";
import { druidFeatures } from "./druid-features.js";
import { druidProgressionFor, resolveDruidSelections } from "./druid.js";
import { validateDruidCharacter } from "./druid-validation.js";
import { buildDruidSpellcasting } from "./druid-spellcasting.js";
import { paladinFeatures } from "./paladin-features.js";
import { paladinProgressionFor } from "./paladin.js";
import { validatePaladinCharacter } from "./paladin-validation.js";
import { buildPaladinSpellcasting } from "./paladin-spellcasting.js";
import { rangerFeatures } from "./ranger-features.js";
import { rangerProgressionFor, resolveRangerClassSelections } from "./ranger.js";
import { validateRangerCharacter } from "./ranger-validation.js";
import { buildRangerSpellcasting } from "./ranger-spellcasting.js";
import { fighterProgressionFor } from "./fighter.js";
import { rogueProgressionFor, rogueSaveProficiencies } from "./rogue.js";
import { resolve2024Species } from "./species.js";
import { resolve2014Species } from "./species-2014.js";
import { resolveBackgroundDetails } from "./background.js";
import { applyHomebrew } from "./homebrew.js";
import { buildWizardSpellcasting } from "./wizard.js";
import { buildClericSpellcasting, resolveDivineOrder, resolveBlessedStrikes, clericProgressionFor, validateClericClassSelections } from "./cleric.js";
import { validateCharacter } from "./validation.js";
import { uniqueStrings, uniqueBy } from "./duplicates.js";
import { buildRulesAudit } from "./audit-router.js";
import { deriveCharacter } from "./derive.js";

const NAMES=["Aric Vale","Mira Stone","Tavian Reed","Selene Hart","Bren Ashford","Kael Rowan"],ALL_SKILLS=Object.keys(SKILLS);
const LANGUAGES_2024=["Common Sign Language","Draconic","Dwarvish","Elvish","Giant","Gnomish","Goblin","Halfling","Orc"],SCHOLAR_SKILLS=["arcana","history","investigation","medicine","nature","religion"];
const dataFor=ruleset=>ruleset==="2014"?FORGE_2014:FORGE_2024,resolve=(value,items)=>value&&value!==RANDOM?items.find(i=>i.id===value):pick(items);

export function generateCharacter(state){
  try{
    const data=dataFor(state.ruleset),species=resolve(state.constraints.species,data.species),cls=resolve(state.constraints.class,data.classes);if(!species||!cls)throw new Error("A selected character option is unavailable for this ruleset.");
    const level=resolveLevel(state.constraints.level,state.constraints.subclass,cls),subclasses=data.subclasses.filter(item=>item.classId===cls.id),subclass=level>=cls.subclassLevel&&subclasses.length?resolve(state.constraints.subclass,subclasses):null;if(state.constraints.subclass!==RANDOM&&!subclass)throw new Error(`${cls.name} subclass choice is not legal at level ${level}.`);
    const background=resolveBackgroundForCharacter(state.constraints.background,data.backgrounds,cls,state.classSelections||{});if(!background)throw new Error("A selected character option is unavailable for this ruleset.");
    if(cls.id==="cleric")validateClericClassSelections({ruleset:state.ruleset,level,selections:state.classSelections||{},spellSelections:state.spellSelections||{}});
    const skills=resolveInitialSkills(cls,background,state.classSelections||{}),speciesResolution=state.ruleset==="2014"?resolve2014Species(species,{level,skills,selections:state.speciesSelections||{}}):resolve2024Species(species,{level,skills,selections:state.speciesSelections||{}}),backgroundDetails=resolveBackgroundDetails(state.ruleset,background,state.backgroundSelections||{});
    skills.push(...speciesResolution.addedSkills);if(state.ruleset==="2024"&&cls.id==="barbarian"&&level>=3)skills.push(...sample(cls.skillChoices,1,skills));
    let abilities=generateBaseAbilities("standard",cls.abilityPriority);abilities=state.ruleset==="2014"?apply2014Species(abilities,speciesResolution):apply2024Background(abilities,background,cls.primary);const advancementBaseAbilities={...abilities},advancement=resolveClassAdvancements({ruleset:state.ruleset,level,cls,abilities,selections:state.classSelections||{},skills:[...skills,...(state.classSelections?.loreBonusSkills||[])]});abilities={...advancement.scores};skills.push(...advancement.addedSkills);
    let abilityMaximums=Object.fromEntries(ABILITIES.map(a=>[a,20])),epicBoonFeat=null,epicBoonAbility=null;
    if(state.ruleset==="2024"&&cls.epicBoon&&level>=cls.epicBoon.level){epicBoonFeat=data.feats.find(feat=>feat.id===cls.epicBoon.feat);if(!epicBoonFeat)throw new Error(`${cls.name} Epic Boon feat is unavailable.`);const boon=applyEpicBoonAbility(abilities,abilityMaximums,cls.abilityPriority,epicBoonFeat);abilities=boon.scores;abilityMaximums=boon.maximums;epicBoonAbility=boon.ability;}
    if(cls.id==="barbarian"){const capstone=applyPrimalChampion(abilities,abilityMaximums,state.ruleset,level);abilities=capstone.scores;abilityMaximums=capstone.maximums;}if(cls.id==="monk"){const capstone=applyBodyAndMind(abilities,abilityMaximums,state.ruleset,level);abilities=capstone.scores;abilityMaximums=capstone.maximums;}
    const bard=cls.id==="bard"?bardProgressionFor(state.ruleset,level,subclass?.id):null,monk=cls.id==="monk"?monkProgressionFor(state.ruleset,level,subclass?.id):null,sorcerer=cls.id==="sorcerer"?sorcererProgressionFor(state.ruleset,level,subclass?.id):null,warlock=cls.id==="warlock"?warlockProgressionFor(state.ruleset,level,subclass?.id):null;
    const preLoreSkills=uniqueStrings(skills),bardLoreSkills=cls.id==="bard"?resolveLoreBonusSkills(cls,preLoreSkills,bard.loreBonusSkills,state.classSelections||{}):[],bardInstruments=cls.id==="bard"?resolveBardInstruments(cls,state.classSelections||{}):[];if(bardLoreSkills.length)skills.push(...bardLoreSkills);
    const bardSelections=cls.id==="bard"?{instruments:[...bardInstruments],loreBonusSkills:[...bardLoreSkills],expertise:[]}:null,druidSelections=cls.id==="druid"?resolveDruidSelections(state.ruleset,level,subclass?.id,state.classSelections||{}):null,rangerSelections=cls.id==="ranger"?resolveRangerClassSelections(state.ruleset,level,subclass?.id,state.classSelections||{}):null,monkTool=cls.id==="monk"?resolveMonkTool(cls,state.classSelections||{}):null,monkSelections=cls.id==="monk"?{tool:monkTool}:null,sorcererSelections=cls.id==="sorcerer"?resolveSorcererSelections({ruleset:state.ruleset,level,subclassId:subclass?.id,selections:state.classSelections||{}}):null,warlockSelections=cls.id==="warlock"?resolveWarlockSelections({ruleset:state.ruleset,level,subclassId:subclass?.id,selections:state.classSelections||{}}):null;
    const pb=proficiencyBonus(level),baseEquipment=pick(cls.equipmentPackages),equipment=cls.id==="monk"?resolveMonkEquipment(cls,baseEquipment,monkTool):baseEquipment,barbarian=cls.id==="barbarian"?barbarianProgressionFor(state.ruleset,level,subclass?.id):null,druid=cls.id==="druid"?druidProgressionFor(state.ruleset,level,subclass?.id):null,paladin=cls.id==="paladin"?paladinProgressionFor(state.ruleset,level,subclass?.id,abilityMod(abilities.cha)):null,ranger=cls.id==="ranger"?rangerProgressionFor(state.ruleset,level,subclass?.id,abilityMod(abilities.wis)):null,fighter=cls.id==="fighter"?fighterProgressionFor(state.ruleset,level,subclass?.id):null,rogue=cls.id==="rogue"?rogueProgressionFor(level,subclass?.id,state.ruleset):null,fightingStyles=cls.id==="fighter"?resolveFightingStyles(equipment,data,fighter,cls):cls.id==="paladin"?resolveSingleClassFightingStyle("Paladin",equipment,data,paladin,state.classSelections||{},cls):cls.id==="ranger"?resolveSingleClassFightingStyle("Ranger",equipment,data,ranger,state.classSelections||{},cls):[],fightingStyle=fightingStyles[0]||null,divineOrder=cls.id==="cleric"?resolveDivineOrder(state.ruleset,state.classSelections||{},state.spellSelections||{},level):null,blessedStrikes=cls.id==="cleric"?resolveBlessedStrikes(state.ruleset,level,state.classSelections||{}):null,cleric=cls.id==="cleric"?clericProgressionFor(state.ruleset,level):null;
    const classTools=uniqueStrings([...(cls.tools||[]),...(cls.id==="rogue"?["Thieves' Tools"]:[]),...bardInstruments,...(monkTool?[monkTool]:[]),...advancement.addedTools]),saveProficiencies=cls.id==="rogue"?rogueSaveProficiencies(level,state.ruleset):cls.saves;
    let character={id:crypto.randomUUID(),sourceMode:state.sourceMode,ruleset:state.ruleset,level,name:state.constraints.name.trim()||pick(NAMES),species,size:speciesResolution.size,speciesChoices:speciesResolution.choices,speciesTraits:speciesResolution.activeTraits,speciesAbilityAdds:speciesResolution.abilityAdds||species.abilityAdds||{},class:cls,subclass,background,backgroundChoices:backgroundDetails.choices,backgroundEquipment:backgroundDetails.equipment,toolProficiencies:[...backgroundDetails.toolProficiencies,...(speciesResolution.toolProficiencies||[]),...classTools],magicInitiate:backgroundDetails.magicInitiate,abilities,abilityMaximums,advancementBaseAbilities,classAdvancements:[...advancement.records],advancementSpeedBonus:advancement.speedBonus,skills,expertise:[],saves:saveProficiencies,proficiency:pb,equipment,fightingStyle,fightingStyles,barbarian,bard,bardSelections,monk,monkSelections,sorcerer,sorcererSelections,warlock,warlockSelections,druid,druidSelections,paladin,ranger,rangerSelections,fighter,rogue,cleric,epicBoonAbility,divineOrder,blessedStrikes,languages:resolveLanguages(state.ruleset,background,cls,speciesResolution),feats:advancement.feats.map(feat=>({...feat,advancementFeat:true})),homebrew:[],homebrewAcBonus:0,features:resolveFeatures(state.ruleset,cls.id,level,subclass?.id,divineOrder,rangerSelections,druidSelections,warlockSelections),spells:null,speciesMagic:null};
    if(state.ruleset==="2014"&&cls.id==="sorcerer"&&subclass?.id==="draconic-bloodline")character.languages=uniqueStrings([...character.languages,"Draconic"]);for(const style of fightingStyles)character.features.push(`Fighting Style: ${style.name}`);if(state.ruleset==="2024")character=apply2024Feats(character,data,background,species);if(epicBoonFeat)character.feats.push(epicBoonFeat);if(state.ruleset==="2024"&&cls.id==="warlock"&&warlockSelections.invocations.all.includes("lessons-of-the-first-ones"))character=applyWarlockInvocationFeat(character,data);character.feats=uniqueBy(character.feats,feat=>feat.id);
    if(state.ruleset==="2024"&&cls.id==="wizard"&&level>=2)character.expertise=[pick(character.skills.filter(skill=>SCHOLAR_SKILLS.includes(skill)))];if(cls.id==="rogue"){const expertisePool=state.ruleset==="2014"?uniqueStrings([...character.skills,"Thieves' Tools"]):uniqueStrings(character.skills);character.expertise=sample(expertisePool,rogue.expertiseCount);}if(cls.id==="bard"){const allBardSkills=uniqueStrings(character.skills),earlyPool=state.ruleset==="2024"?allBardSkills.filter(skill=>!bardLoreSkills.includes(skill)):allBardSkills;character.expertise=resolveBardExpertise({ruleset:state.ruleset,level,preLoreSkills:earlyPool,allSkills:allBardSkills,count:bard.expertiseCount,selections:state.classSelections||{}});character.bardSelections.expertise=[...character.expertise];}
    if(state.ruleset==="2014"&&cls.id==="ranger")character.languages=uniqueStrings([...character.languages,...(rangerSelections.favoredEnemyLanguages||[]).filter(Boolean)]);if(state.ruleset==="2024"&&cls.id==="ranger"){character.expertise=sample(uniqueStrings(character.skills),ranger.expertiseCount);if(ranger.extraLanguages)character.languages=uniqueStrings([...character.languages,...sample(LANGUAGES_2024,ranger.extraLanguages,character.languages)]);}if(state.sourceMode===SOURCE.HOMEBREW)character=applyHomebrew(character,state.homebrew);
    if(cls.spellcasting==="wizard")character.spells=buildWizardSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="cleric")character.spells=buildClericSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="bard")character.spells=buildBardSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="sorcerer")character.spells=buildSorcererSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="warlock")character.spells=buildWarlockSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="druid")character.spells=buildDruidSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="paladin"&&(state.ruleset==="2024"||level>=2))character.spells=buildPaladinSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="ranger"&&(state.ruleset==="2024"||level>=2))character.spells=buildRangerSpellcasting(character,state.spellSelections||{});
    character=deriveCharacter(character,data);const baseValidation=validateCharacter(character,state.sourceMode),extraErrors=cls.id==="barbarian"?validateBarbarianCharacter(character):cls.id==="bard"?validateBardCharacter(character):cls.id==="sorcerer"?validateSorcererCharacter(character):cls.id==="warlock"?validateWarlockCharacter(character):cls.id==="druid"?validateDruidCharacter(character):cls.id==="paladin"?validatePaladinCharacter(character):cls.id==="ranger"?validateRangerCharacter(character):[],validation={valid:baseValidation.errors.length+extraErrors.length===0,errors:[...baseValidation.errors,...extraErrors]};if(!validation.valid)throw new Error(validation.errors.join(" "));const audit=buildRulesAudit(character,validation);return{...character,validation,audit};
  }catch(error){console.error("[generator] Character generation blocked",error);throw error;}
}
function resolveLevel(value,subclassValue,cls){try{const maxLevel=cls.maxLevel||5,minimum=subclassValue&&subclassValue!==RANDOM?cls.subclassLevel:1;if(value!==RANDOM){const level=Number(value);if(!Number.isInteger(level)||level<minimum||level>maxLevel)throw new Error(`${cls.name} currently supports levels ${minimum}-${maxLevel} for this selection.`);return level;}if(minimum>maxLevel)throw new Error(`${cls.name} has no legal Random level for this selection.`);return minimum+Math.floor(Math.random()*(maxLevel-minimum+1));}catch(error){console.error("[generator] level resolution failed",error);throw error;}}
function resolveBackgroundForCharacter(value,backgrounds,cls,selections){try{const fixedLore=cls.id==="bard"?new Set(selections.loreBonusSkills||[]):new Set(),legal=background=>!(background?.skills||[]).some(skill=>fixedLore.has(skill));if(value&&value!==RANDOM){const background=backgrounds.find(item=>item.id===value);if(!background)return null;if(!legal(background))throw new Error("A fixed College of Lore bonus skill is already granted by the selected background.");return background;}const pool=backgrounds.filter(legal);if(!pool.length)throw new Error("No verified background can preserve the fixed College of Lore skill choices.");return pick(pool);}catch(error){console.error("[generator] background resolution failed",error);throw error;}}
function resolveInitialSkills(cls,background,selections){try{const backgroundSkills=[...(background.skills||[])];if(cls.id!=="bard")return uniqueStrings([...backgroundSkills,...sample(cls.skillChoices,cls.skillCount,backgroundSkills)]);const lore=new Set(selections.loreBonusSkills||[]),expertise=selections.expertise||[],illegalLore=[...lore].filter(skill=>backgroundSkills.includes(skill)||!cls.skillChoices.includes(skill));if(illegalLore.length)throw new Error(`Illegal College of Lore bonus skill reservation: ${illegalLore.join(", ")}.`);const reserved=uniqueStrings(expertise.filter(skill=>!backgroundSkills.includes(skill)&&!lore.has(skill)));const illegalExpertise=reserved.filter(skill=>!cls.skillChoices.includes(skill));if(illegalExpertise.length)throw new Error(`Illegal Bard Expertise skill reservation: ${illegalExpertise.join(", ")}.`);if(reserved.length>cls.skillCount)throw new Error("Fixed Bard Expertise requires more base class skill proficiencies than Bard can choose.");const randomPool=cls.skillChoices.filter(skill=>!lore.has(skill)),random=sample(randomPool,cls.skillCount-reserved.length,[...backgroundSkills,...reserved]);return uniqueStrings([...backgroundSkills,...reserved,...random]);}catch(error){console.error("[generator] initial skill resolution failed",error);throw error;}}
function resolveFightingStyles(equipment,data,fighter,cls){try{const classPool=cls.styleChoices||[],packagePool=(equipment.styles||[]).filter(id=>classPool.includes(id));if(!classPool.length||!packagePool.length)throw new Error(`${cls.name} verified Fighting Style pool is unavailable.`);const firstId=pick(packagePool),ids=[firstId];if(fighter?.additionalFightingStyle){const choices=classPool.filter(id=>!ids.includes(id));if(!choices.length)throw new Error(`${cls.name} has no legal additional Fighting Style choice.`);ids.push(pick(choices));}return ids.map(id=>{const style=data.fightingStyles[id];if(!style)throw new Error(`Missing ${cls.name} Fighting Style data for ${id}.`);return{id,...style};});}catch(error){console.error("[generator] fighting style resolution failed",error);throw error;}}
function resolveSingleClassFightingStyle(className,equipment,data,progression,selections,cls){try{if(!progression?.fightingStyle)return[];const classPool=cls.styleChoices||[],available=(equipment.styles||[]).filter(id=>classPool.includes(id)),requested=selections.fightingStyle;if(!classPool.length||!available.length)throw new Error(`${className} verified Fighting Style pool is unavailable.`);if(requested&&!available.includes(requested))throw new Error(`${className} Fighting Style "${requested}" is unavailable.`);const id=requested||pick(available),style=data.fightingStyles[id];if(!style)throw new Error(`Missing ${className} Fighting Style data for ${id}.`);return[{id,...style}];}catch(error){console.error(`[generator] ${className} fighting style resolution failed`,error);throw error;}}
function resolveFeatures(ruleset,classId,level,subclassId,divineOrder,rangerSelections,druidSelections,warlockSelections){try{if(classId==="barbarian")return barbarianFeatures(ruleset,level,subclassId);if(classId==="bard")return bardFeatures(ruleset,level,subclassId);if(classId==="monk")return monkFeatures(ruleset,level,subclassId);if(classId==="sorcerer")return sorcererFeatures(ruleset,level,subclassId);if(classId==="warlock")return warlockFeatures(ruleset,level,subclassId,warlockSelections||{});if(classId==="druid")return druidFeatures(ruleset,level,subclassId,druidSelections||{});if(classId==="paladin")return paladinFeatures(ruleset,level,subclassId);if(classId==="ranger")return rangerFeatures(ruleset,level,subclassId,rangerSelections||{});if(classId==="wizard")return wizardFeatures(ruleset,level,subclassId);if(classId==="cleric")return clericFeatures(ruleset,level,subclassId,divineOrder);if(classId==="rogue")return rogueFeatures(ruleset,level,subclassId);if(classId==="fighter")return fighterFeatures(ruleset,level,subclassId);throw new Error(`Unsupported class feature resolver: ${classId}.`);}catch(error){console.error("[generator] feature resolution failed",error);throw error;}}
function resolveLanguages(ruleset,background,cls,speciesResolution){try{if(ruleset==="2014"){const base=[...(speciesResolution.languages||[])],backgroundLanguages=sample(LANGUAGES_2014,background.languages||0,base),languages=uniqueStrings([...base,...backgroundLanguages]);if(cls.id==="rogue")languages.push("Thieves’ Cant");if(cls.id==="druid")languages.push("Druidic");return uniqueStrings(languages);}const base=["Common",...sample(LANGUAGES_2024,2)];if(cls.id==="rogue")return uniqueStrings([...base,"Thieves’ Cant",...sample(LANGUAGES_2024,cls.extraLanguages||1,base)]);if(cls.id==="druid")return uniqueStrings([...base,"Druidic"]);return base;}catch(error){console.error("[generator] language resolution failed",error);throw error;}}
function apply2024Feats(character,data,background,species){try{const next=structuredClone(character),feats=[...(next.feats||[]),data.feats.find(f=>f.id===background.feat)];if(species.originFeat)feats.push(pick(data.feats.filter(f=>f.category==="Origin"&&!f.backgroundOnly&&!feats.some(x=>x?.id===f.id))));next.feats=uniqueBy(feats.filter(Boolean),feat=>feat.id);for(const feat of next.feats)if(feat.extraSkills)next.skills.push(...sample(ALL_SKILLS,feat.extraSkills,next.skills));return next;}catch(error){console.error("[generator] feat resolution failed",error);throw error;}}
function applyWarlockInvocationFeat(character,data){try{const next=structuredClone(character),eligible=data.feats.filter(feat=>feat.category==="Origin"&&!feat.backgroundOnly&&!next.feats.some(current=>current.id===feat.id));if(!eligible.length)throw new Error("Lessons of the First Ones has no verified eligible Origin feat remaining.");const feat=pick(eligible);next.feats.push(feat);if(feat.extraSkills)next.skills.push(...sample(ALL_SKILLS,feat.extraSkills,next.skills));return next;}catch(error){console.error("[generator] Warlock invocation feat resolution failed",error);throw error;}}
