import { RANDOM, SOURCE, ABILITIES, SKILLS } from "../schema.js";
import { RAW_2014 } from "../data/raw-2014.js";
import { RAW_2024 } from "../data/raw-2024.js";
import { LANGUAGES_2014 } from "../data/species-2014.js";
import { pick, sample } from "./random.js";
import { generateBaseAbilities, apply2014Species, apply2024Background } from "./abilities.js";
import { abilityMod, proficiencyBonus, calculateAc, averageHp } from "./math.js";
import { fighterFeatures, wizardFeatures, clericFeatures, rogueFeatures, applyClassAsi, applyEpicBoonAbility } from "./features.js";
import { barbarianFeatures } from "./barbarian-features.js";
import { barbarianProgressionFor, applyPrimalChampion } from "./barbarian.js";
import { validateBarbarianCharacter } from "./barbarian-validation.js";
import { fighterProgressionFor } from "./fighter.js";
import { rogueProgressionFor, rogueSaveProficiencies } from "./rogue.js";
import { resolve2024Species, speciesHpBonus, speciesSpeed, speciesMagic } from "./species.js";
import { resolve2014Species } from "./species-2014.js";
import { resolveBackgroundDetails } from "./background.js";
import { applyHomebrew } from "./homebrew.js";
import { buildWizardSpellcasting } from "./wizard.js";
import { buildClericSpellcasting, resolveDivineOrder, resolveBlessedStrikes, clericProgressionFor, validateClericClassSelections } from "./cleric.js";
import { validateCharacter } from "./validation.js";
import { uniqueStrings, uniqueBy, consolidateInventory } from "./duplicates.js";
import { buildRulesAudit } from "./audit-router.js";

const NAMES=["Aric Vale","Mira Stone","Tavian Reed","Selene Hart","Bren Ashford","Kael Rowan"],ALL_SKILLS=Object.keys(SKILLS);
const LANGUAGES_2024=["Common Sign Language","Draconic","Dwarvish","Elvish","Giant","Gnomish","Goblin","Halfling","Orc"],SCHOLAR_SKILLS=["arcana","history","investigation","medicine","nature","religion"];
const dataFor=ruleset=>ruleset==="2014"?RAW_2014:RAW_2024,resolve=(value,items)=>value&&value!==RANDOM?items.find(i=>i.id===value):pick(items);

export function generateCharacter(state){
  try{
    const data=dataFor(state.ruleset),species=resolve(state.constraints.species,data.species),cls=resolve(state.constraints.class,data.classes),background=resolve(state.constraints.background,data.backgrounds);if(!species||!cls||!background)throw new Error("A selected character option is unavailable for this ruleset.");
    const level=resolveLevel(state.constraints.level,state.constraints.subclass,cls),subclasses=data.subclasses.filter(item=>item.classId===cls.id),subclass=level>=cls.subclassLevel&&subclasses.length?resolve(state.constraints.subclass,subclasses):null;if(state.constraints.subclass!==RANDOM&&!subclass)throw new Error(`${cls.name} subclass choice is not legal at level ${level}.`);
    if(cls.id==="cleric")validateClericClassSelections({ruleset:state.ruleset,level,selections:state.classSelections||{},spellSelections:state.spellSelections||{}});
    const skills=uniqueStrings([...(background.skills||[]),...sample(cls.skillChoices,cls.skillCount,background.skills||[])]),speciesResolution=state.ruleset==="2014"?resolve2014Species(species,{level,skills,selections:state.speciesSelections||{}}):resolve2024Species(species,{level,skills,selections:state.speciesSelections||{}}),backgroundDetails=resolveBackgroundDetails(state.ruleset,background,state.backgroundSelections||{});
    let abilities=generateBaseAbilities("standard",cls.abilityPriority);abilities=state.ruleset==="2014"?apply2014Species(abilities,speciesResolution):apply2024Background(abilities,background,cls.primary);abilities=applyClassAsi(abilities,level,cls.abilityPriority,cls.asiLevels||[4]);
    let abilityMaximums=Object.fromEntries(ABILITIES.map(a=>[a,20])),epicBoonFeat=null,epicBoonAbility=null;
    if(state.ruleset==="2024"&&cls.epicBoon&&level>=cls.epicBoon.level){epicBoonFeat=data.feats.find(feat=>feat.id===cls.epicBoon.feat);if(!epicBoonFeat)throw new Error(`${cls.name} Epic Boon feat is unavailable.`);const boon=applyEpicBoonAbility(abilities,abilityMaximums,cls.abilityPriority,epicBoonFeat);abilities=boon.scores;abilityMaximums=boon.maximums;epicBoonAbility=boon.ability;}
    if(cls.id==="barbarian"){const capstone=applyPrimalChampion(abilities,abilityMaximums,state.ruleset,level);abilities=capstone.scores;abilityMaximums=capstone.maximums;}
    skills.push(...speciesResolution.addedSkills);if(state.ruleset==="2024"&&cls.id==="barbarian"&&level>=3)skills.push(...sample(cls.skillChoices,1,skills));
    const pb=proficiencyBonus(level),equipment=pick(cls.equipmentPackages),barbarian=cls.id==="barbarian"?barbarianProgressionFor(state.ruleset,level,subclass?.id):null,fighter=cls.id==="fighter"?fighterProgressionFor(state.ruleset,level,subclass?.id):null,rogue=cls.id==="rogue"?rogueProgressionFor(level,subclass?.id,state.ruleset):null,fightingStyles=cls.id==="fighter"?resolveFightingStyles(equipment,data,fighter):[],fightingStyle=fightingStyles[0]||null,divineOrder=cls.id==="cleric"?resolveDivineOrder(state.ruleset,state.classSelections||{},state.spellSelections||{},level):null,blessedStrikes=cls.id==="cleric"?resolveBlessedStrikes(state.ruleset,level,state.classSelections||{}):null,cleric=cls.id==="cleric"?clericProgressionFor(state.ruleset,level):null;
    const classTools=cls.id==="rogue"?["Thieves' Tools"]:[],saveProficiencies=cls.id==="rogue"?rogueSaveProficiencies(level,state.ruleset):cls.saves;
    let character={id:crypto.randomUUID(),sourceMode:state.sourceMode,ruleset:state.ruleset,level,name:state.constraints.name.trim()||pick(NAMES),species,size:speciesResolution.size,speciesChoices:speciesResolution.choices,speciesTraits:speciesResolution.activeTraits,speciesAbilityAdds:speciesResolution.abilityAdds||species.abilityAdds||{},class:cls,subclass,background,backgroundChoices:backgroundDetails.choices,backgroundEquipment:backgroundDetails.equipment,toolProficiencies:[...backgroundDetails.toolProficiencies,...(speciesResolution.toolProficiencies||[]),...classTools],magicInitiate:backgroundDetails.magicInitiate,abilities,abilityMaximums,skills,expertise:[],saves:saveProficiencies,proficiency:pb,equipment,fightingStyle,fightingStyles,barbarian,fighter,rogue,cleric,epicBoonAbility,divineOrder,blessedStrikes,languages:resolveLanguages(state.ruleset,background,cls,speciesResolution),feats:[],homebrew:[],homebrewAcBonus:0,features:resolveFeatures(state.ruleset,cls.id,level,subclass?.id,divineOrder),spells:null,speciesMagic:null};
    for(const style of fightingStyles)character.features.push(`Fighting Style: ${style.name}`);
    if(state.ruleset==="2024")character=apply2024Feats(character,data,background,species);
    if(epicBoonFeat)character.feats.push(epicBoonFeat);
    character.feats=uniqueBy(character.feats,feat=>feat.id);
    if(state.ruleset==="2024"&&cls.id==="wizard"&&level>=2)character.expertise=[pick(character.skills.filter(skill=>SCHOLAR_SKILLS.includes(skill)))];
    if(cls.id==="rogue"){
      const expertisePool=state.ruleset==="2014"?uniqueStrings([...character.skills,"Thieves' Tools"]):uniqueStrings(character.skills);
      character.expertise=sample(expertisePool,rogue.expertiseCount);
    }
    if(state.sourceMode===SOURCE.HOMEBREW)character=applyHomebrew(character,state.homebrew);if(cls.spellcasting==="wizard")character.spells=buildWizardSpellcasting(character,state.spellSelections||{});if(cls.spellcasting==="cleric")character.spells=buildClericSpellcasting(character,state.spellSelections||{});
    character=derive(character,data);const baseValidation=validateCharacter(character,state.sourceMode),extraErrors=cls.id==="barbarian"?validateBarbarianCharacter(character):[],validation={valid:baseValidation.errors.length+extraErrors.length===0,errors:[...baseValidation.errors,...extraErrors]};if(!validation.valid)throw new Error(validation.errors.join(" "));const audit=buildRulesAudit(character,validation);return{...character,validation,audit};
  }catch(error){console.error("[generator] Character generation blocked",error);throw error;}
}
function resolveLevel(value,subclassValue,cls){try{const maxLevel=cls.maxLevel||5,minimum=subclassValue&&subclassValue!==RANDOM?cls.subclassLevel:1;if(value!==RANDOM){const level=Number(value);if(!Number.isInteger(level)||level<minimum||level>maxLevel)throw new Error(`${cls.name} currently supports levels ${minimum}-${maxLevel} for this selection.`);return level;}if(minimum>maxLevel)throw new Error(`${cls.name} has no legal Random level for this selection.`);return minimum+Math.floor(Math.random()*(maxLevel-minimum+1));}catch(error){console.error("[generator] level resolution failed",error);throw error;}}
function resolveFightingStyles(equipment,data,fighter){try{const firstId=pick(equipment.styles),ids=[firstId];if(fighter?.additionalFightingStyle){const choices=Object.keys(data.fightingStyles).filter(id=>!ids.includes(id));ids.push(pick(choices));}return ids.map(id=>({id,...data.fightingStyles[id]}));}catch(error){console.error("[generator] fighting style resolution failed",error);throw error;}}
function resolveFeatures(ruleset,classId,level,subclassId,divineOrder){try{if(classId==="barbarian")return barbarianFeatures(ruleset,level,subclassId);if(classId==="wizard")return wizardFeatures(ruleset,level,subclassId);if(classId==="cleric")return clericFeatures(ruleset,level,subclassId,divineOrder);if(classId==="rogue")return rogueFeatures(ruleset,level,subclassId);if(classId==="fighter")return fighterFeatures(ruleset,level,subclassId);throw new Error(`Unsupported class feature resolver: ${classId}.`);}catch(error){console.error("[generator] feature resolution failed",error);throw error;}}
function resolveLanguages(ruleset,background,cls,speciesResolution){try{if(ruleset==="2014"){const base=[...(speciesResolution.languages||[])],backgroundLanguages=sample(LANGUAGES_2014,background.languages||0,base),languages=uniqueStrings([...base,...backgroundLanguages]);return cls.id==="rogue"?uniqueStrings([...languages,"Thieves’ Cant"]):languages;}const base=["Common",...sample(LANGUAGES_2024,2)];if(cls.id!=="rogue")return base;return uniqueStrings([...base,"Thieves’ Cant",...sample(LANGUAGES_2024,cls.extraLanguages||1,base)]);}catch(error){console.error("[generator] language resolution failed",error);throw error;}}
function apply2024Feats(character,data,background,species){try{const next=structuredClone(character),feats=[data.feats.find(f=>f.id===background.feat)];if(species.originFeat)feats.push(pick(data.feats.filter(f=>f.category==="Origin"&&!f.backgroundOnly&&!feats.some(x=>x.id===f.id))));next.feats=uniqueBy(feats.filter(Boolean),feat=>feat.id);for(const feat of next.feats)if(feat.extraSkills)next.skills.push(...sample(ALL_SKILLS,feat.extraSkills,next.skills));return next;}catch(error){console.error("[generator] feat resolution failed",error);throw error;}}
function derive(character,data){
  try{
    const dex=abilityMod(character.abilities.dex),con=abilityMod(character.abilities.con),pb=character.proficiency,styles=character.fightingStyles?.length?character.fightingStyles:(character.fightingStyle?[character.fightingStyle]:[]),acBonus=character.homebrewAcBonus+styles.reduce((sum,style)=>sum+(style.acBonus||0),0),armor=character.equipment.armor?data.armor[character.equipment.armor]:null,ac=character.class.id==="barbarian"&&!armor?10+dex+con+(character.equipment.shield?2:0)+acBonus:calculateAc(armor,dex,character.equipment.shield,acBonus),speciesBonusHp=speciesHpBonus(character),hp=averageHp(character.class.hitDie,character.level,con)+speciesBonusHp,alert=character.feats.some(f=>f.id==="alert")?pb:0;
    const saveBonuses=Object.fromEntries(ABILITIES.map(a=>[a,abilityMod(character.abilities[a])+(character.saves.includes(a)?pb:0)])),thaumaturge=character.ruleset==="2024"&&character.class.id==="cleric"&&character.divineOrder==="thaumaturge"?Math.max(1,abilityMod(character.abilities.wis)):0;
    const skillBonuses=Object.fromEntries(Object.entries(SKILLS).map(([s,a])=>[s,abilityMod(character.abilities[a])+(character.skills.includes(s)?pb:0)+(character.expertise.includes(s)?pb:0)+(["arcana","religion"].includes(s)?thaumaturge:0)]));
    const attacks=character.equipment.weapons.map(id=>{const weapon=data.weapons[id];if(!weapon)throw new Error(`Unknown equipped weapon: ${id}.`);const mod=abilityMod(character.abilities[weapon.ability]),styleBonus=["longbow","light-crossbow"].includes(id)?styles.reduce((sum,style)=>sum+(style.rangedAttackBonus||0),0):0;return{...weapon,id,attackBonus:mod+pb+styleBonus,damageBonus:mod};}),masteryCount=character.barbarian?.masteryCount||character.fighter?.masteryCount||character.rogue?.masteryCount||0,equippedMasteries=[...new Set(character.equipment.weapons)],extraMasteries=masteryCount?sample(Object.keys(data.weapons),Math.max(0,masteryCount-equippedMasteries.length),equippedMasteries):[],masteryIds=masteryCount?[...equippedMasteries,...extraMasteries].slice(0,masteryCount):[];
    const attackInventory=attacks.map(attack=>character.equipment.focus===attack.id?`Arcane Focus (${attack.name})`:attack.name),inventory=consolidateInventory([...attackInventory,...character.equipment.gear,...(character.backgroundEquipment||character.background.equipment||[])]);
    const next={...character,skills:uniqueStrings(character.skills),expertise:uniqueStrings(character.expertise),languages:uniqueStrings(character.languages),toolProficiencies:uniqueStrings(character.toolProficiencies||[]),feats:uniqueBy(character.feats,feat=>feat.id),homebrew:uniqueBy(character.homebrew,item=>item.id),features:uniqueStrings(character.features),ac,hp,speciesHpBonus:speciesBonusHp,initiative:dex+alert,initiativeAdvantage:Boolean(character.barbarian?.initiativeAdvantage||character.fighter?.initiativeAdvantage),speed:speciesSpeed(character)+(character.barbarian?.speedBonus||0),attacks:uniqueBy(attacks,attack=>attack.name),saveBonuses,skillBonuses,passivePerception:10+skillBonuses.perception,masteryIds:uniqueStrings(masteryIds),inventory};
    return{...next,speciesMagic:speciesMagic(next)};
  }catch(error){console.error("[generator] derivation failed",error);throw error;}
}
