import { REFERENCE_2014, REFERENCE_2024, MASTERY_REFERENCE } from "../data/quick-reference.js";
import { RAW_2014 } from "../data/raw-2014.js";
import { RAW_2024 } from "../data/raw-2024.js";
import { GNOME_LINEAGES, GOLIATH_ANCESTRIES, TIEFLING_LEGACIES } from "../data/species-2024.js";
import { wizardSpellsFor } from "../data/wizard-spells.js";
import { referenceProvenance } from "../data/rule-provenance.js";
import { dragonbornBreath, speciesDarkvision, speciesMagic } from "./species.js";
import { abilityMod } from "./math.js";

const dataFor=ruleset=>ruleset==="2014"?RAW_2014:RAW_2024,refsFor=ruleset=>ruleset==="2014"?REFERENCE_2014:REFERENCE_2024;
export function buildQuickReference(character){
  try{
    const rules=refsFor(character.ruleset),items=[];
    for(const trait of character.speciesTraits||character.species.traits||[])push(character,items,`species:${trait}`,trait,dynamicSpeciesTrait(character,trait)||required(rules.species?.[trait],trait));
    if(character.background.feature)push(character,items,`background:${character.background.feature}`,character.background.feature,required(rules.background?.[character.background.feature],character.background.feature));
    for(const feat of character.feats||[])push(character,items,`feat:${feat.id}`,feat.name,dynamicFeat(character,feat)||required(rules.feat?.[feat.name],feat.name));
    const styles=character.fightingStyles?.length?character.fightingStyles:(character.fightingStyle?[character.fightingStyle]:[]);
    for(const style of styles)push(character,items,`style:${style.name}`,style.name,required(rules.style?.[style.name],style.name));
    for(const name of character.features||[]){if(name==="Fighting Style"||name.startsWith("Fighting Style:"))continue;push(character,items,`feature:${name}`,name,dynamicFeature(character,name)||required(rules.feature?.[name],name));}
    for(const mastery of masteryEntries(character))push(character,items,`mastery:${mastery.weaponId}`,`${mastery.weaponName} — ${mastery.property}`,required(MASTERY_REFERENCE[mastery.property],mastery.property));
    const ids=items.map(item=>item.id);if(new Set(ids).size!==ids.length)throw new Error("Duplicate quick-reference entries detected.");return items;
  }catch(error){console.error("[reference] build failed",error);throw error;}
}
export function masteryEntries(character){
  try{if(character.ruleset!=="2024"||!character.masteryIds?.length)return[];const data=dataFor(character.ruleset);return character.masteryIds.map(weaponId=>{const weapon=data.weapons[weaponId];if(!weapon)throw new Error(`Unknown mastery weapon ${weaponId}.`);if(!weapon.mastery)throw new Error(`${weapon.name} is missing its Weapon Mastery property.`);if(!MASTERY_REFERENCE[weapon.mastery])throw new Error(`Missing quick reference for ${weapon.mastery}.`);return{weaponId,weaponName:weapon.name,property:weapon.mastery};});}catch(error){console.error("[reference] mastery lookup failed",error);throw error;}
}
function dynamicSpeciesTrait(character,name){
  try{
    if(character.ruleset!=="2024")return null;const species=character.species.id,choices=character.speciesChoices||{},category=character.species.name,pb=character.proficiency;
    if(name==="Darkvision"){const range=speciesDarkvision(character);if(!range)throw new Error(`${category} Darkvision range is unavailable.`);return rr(category,"Passive",`You have Darkvision out to ${range} ft.`);}
    if(species==="dragonborn"){
      if(name==="Draconic Ancestry")return rr(category,"Chosen at creation",`${choices.ancestryName} ancestry determines your ${choices.damageType} Breath Weapon and Damage Resistance.`);
      if(name==="Breath Weapon"){const breath=dragonbornBreath(character);return rr(category,"Replace one Attack",`When you take the Attack action, replace one attack with a 15-ft Cone or 30-ft-by-5-ft Line. Dexterity save DC ${breath.dc}; failure takes ${breath.dice} ${breath.damageType}, success half. ${breath.uses} uses; regain all after a Long Rest.`);}
      if(name==="Damage Resistance")return rr(category,"Passive",`You have Resistance to ${choices.damageType} damage from your ${choices.ancestryName} ancestry.`);
      if(name==="Draconic Flight")return rr(category,"Bonus Action",`Sprout spectral wings for 10 minutes, gaining a Fly Speed equal to your ${character.speed}-ft Speed. The wings end if retracted or you become Incapacitated. One use; regain it after a Long Rest.`);
    }
    if(species==="dwarf"){
      if(name==="Dwarven Toughness")return rr(category,"Applied",`Your Hit Point maximum is increased by ${character.speciesHpBonus} from Dwarven Toughness at level ${character.level}; this bonus is already included in Hit Points.`);
      if(name==="Stonecunning")return rr(category,"Bonus Action",`While on or touching stone, gain Tremorsense 60 ft for 10 minutes. ${pb} uses; regain all after a Long Rest.`);
    }
    if(species==="elf"){
      if(name==="Elven Lineage"){const magic=speciesMagic(character),parts=[...magic.cantrips,...magic.spells];return rr(category,"Lineage magic",`${choices.lineageName}; ${abilityName(magic.ability)} is your lineage spellcasting ability. Current lineage magic: ${parts.join(", ")||"none"}.${choices.lineage==="high"?" Your current High Elf Wizard cantrip can be replaced with another Wizard cantrip after a Long Rest.":""} Level 3+ and 5+ lineage spells are always prepared and each can be cast once without a slot per Long Rest, or with appropriate spell slots.`);}
      if(name==="Keen Senses")return rr(category,"Applied",`Keen Senses grants proficiency in ${pretty(choices.keenSense)}; it is already included in Skills.`);
    }
    if(species==="gnome"&&name==="Gnomish Lineage"){
      const lineage=GNOME_LINEAGES[choices.lineage],magic=speciesMagic(character);if(!lineage)throw new Error("Gnome lineage data is unavailable.");
      if(choices.lineage==="forest")return rr(category,"Lineage magic",`${lineage.name}; ${abilityName(magic.ability)} is your lineage spellcasting ability. You know ${magic.cantrips.join(", ")} and always have ${magic.spells.join(", ")} prepared. Cast Speak with Animals without a slot ${pb} times per Long Rest, or with spell slots.`);
      return rr(category,"Lineage magic / 10 minutes",`${lineage.name}; ${abilityName(magic.ability)} is your lineage spellcasting ability. You know ${magic.cantrips.join(" and ")}. By spending 10 minutes casting Prestidigitation, create a Tiny AC 5, 1 HP clockwork device based on one of that spell's effects; up to three devices can exist, each lasting 8 hours.`);
    }
    if(species==="goliath"){
      if(name==="Giant Ancestry"){const ancestry=GOLIATH_ANCESTRIES[choices.giantAncestry];if(!ancestry)throw new Error("Goliath ancestry data is unavailable.");return rr(category,"Ancestry benefit",`${ancestry.name} (${ancestry.giant}). ${goliathBenefit(choices.giantAncestry,character)} ${pb} uses; regain all after a Long Rest.`);}
      if(name==="Large Form")return rr(category,"Bonus Action",`Become Large for 10 minutes if space allows. During the form, gain Advantage on Strength checks and your Speed increases from ${character.speed} ft to ${character.speed+10} ft. One use; regain it after a Long Rest.`);
    }
    if(species==="human"){
      if(name==="Skillful")return rr(category,"Applied",`Skillful grants proficiency in ${pretty(choices.skill)}; it is already included in Skills.`);
      if(name==="Versatile"){const feat=character.feats.find(item=>item.category==="Origin"&&item.id!==character.background.feat);return rr(category,"Applied",`Versatile grants an Origin feat. This character selected ${feat?.name||"a legal Origin feat"}, shown in the feat references.`);}
    }
    if(species==="orc"&&name==="Adrenaline Rush")return rr(category,"Bonus Action",`Take the Dash action as a Bonus Action and gain ${pb} Temporary Hit Points. ${pb} uses; regain all after a Short or Long Rest.`);
    if(species==="tiefling"){
      const legacy=TIEFLING_LEGACIES[choices.legacy],magic=speciesMagic(character);if(!legacy||!magic)throw new Error("Tiefling legacy data is unavailable.");
      if(name==="Fiendish Legacy")return rr(category,"Legacy magic",`${legacy.name} legacy grants Resistance to ${legacy.resistance} damage. ${abilityName(magic.ability)} is your legacy spellcasting ability. Current legacy magic: ${magic.cantrips.filter(spell=>spell!=="Thaumaturgy").join(", ")}${magic.spells.length?`, ${magic.spells.join(", ")}`:""}. Level 3+ and 5+ legacy spells are always prepared and each can be cast once without a slot per Long Rest, or with appropriate spell slots.`);
      if(name==="Otherworldly Presence")return rr(category,"Cantrip",`You know Thaumaturgy, using ${abilityName(magic.ability)} as its spellcasting ability.`);
    }
    return null;
  }catch(error){console.error(`[reference] dynamic species trait ${name} failed`,error);throw error;}
}
function dynamicFeat(character,feat){
  try{
    if(character.ruleset==="2024"&&feat.id==="boon-spell-recall")return rr("Epic Boon","Casting level 1–4 spell",`The +1 ${pretty(character.epicBoonAbility)} increase and maximum of 30 are already applied. When you cast a spell using a level 1–4 spell slot, roll 1d4; if the roll equals the slot's level, the slot isn't expended.`);
    if(character.ruleset==="2024"&&feat.id==="boon-fate")return rr("Epic Boon","After a D20 Test",`The +1 ${pretty(character.epicBoonAbility)} increase and maximum of 30 are already applied. When you or a creature within 60 ft succeeds or fails a D20 Test, roll 2d4 and add or subtract the total from the roll. Improve Fate refreshes after you roll Initiative or finish a Short or Long Rest.`);
    return null;
  }catch(error){console.error(`[reference] dynamic feat ${feat?.name} failed`,error);throw error;}
}
function dynamicFeature(character,name){
  try{
    if(name==="Spellcasting")return spellcasting(character);
    if(name==="Second Wind")return secondWind(character);
    if(name==="Action Surge")return actionSurge(character);
    if(name==="Ability Score Improvement")return abilityScoreImprovement(character);
    if(["Extra Attack","Two Extra Attacks","Three Extra Attacks"].includes(name))return extraAttack(character);
    if(name==="Indomitable")return indomitable(character);
    if(name==="Remarkable Athlete")return remarkableAthlete(character);
    if(name==="Additional Fighting Style")return additionalFightingStyle(character);
    if(name==="Superior Critical")return superiorCritical(character);
    if(name==="Weapon Mastery")return{category:"Fighter",timing:"Passive",text:`Use the mastery properties for ${character.masteryIds.length} chosen weapons listed below. After a Long Rest, you can change one chosen weapon.`};
    if(name==="Tactical Shift")return{category:"Fighter",timing:"With Second Wind",text:`After using Second Wind as a Bonus Action, move up to ${Math.floor(character.speed/2)} ft without provoking Opportunity Attacks.`};
    if(name==="Arcane Recovery")return arcaneRecovery(character);
    if(name==="Scholar")return{category:"Wizard",timing:"Passive",text:`Expertise is already applied to ${pretty(character.expertise[0])}.`};
    if(name==="Sculpt Spells"&&character.ruleset==="2024")return rr("Evoker","Evocation spell",`When an Evocation spell affects creatures you can see, protect up to 1 + the spell's level of them. They automatically succeed on their saves against the spell and take no damage if a successful save would normally deal half.`);
    if(name==="Potent Cantrip"&&character.ruleset==="2014")return rr("School of Evocation","Damaging cantrip save",`When a creature succeeds on a saving throw against one of your damaging cantrips, it takes half the cantrip's damage, if any, but suffers no additional effect.`);
    if(name==="Empowered Evocation")return rr(character.ruleset==="2014"?"School of Evocation":"Evoker","Evocation damage",`Add your Intelligence modifier (${signed(abilityMod(character.abilities.int))}) to one damage roll of each Wizard Evocation spell you cast.`);
    if(name==="Overchannel")return rr(character.ruleset==="2014"?"School of Evocation":"Evoker","Wizard spell · level 1–5",`When a damaging Wizard spell is cast at level 1–5, you can maximize its damage on the turn you cast it. First use per Long Rest is safe; the second deals 2d12 Necrotic damage per spell level to you, ignoring Resistance and Immunity, and each further use increases that damage by 1d12 per spell level.`);
    if(name==="Spell Mastery")return spellMastery(character);
    if(name==="Epic Boon")return rr(character.class.name,"Applied",`Your level-19 Epic Boon is ${character.feats.find(feat=>feat.category==="Epic Boon")?.name||"listed separately"}; its legal ability increase is already included.`);
    if(name==="Signature Spells")return signatureSpells(character);
    if(name==="Channel Divinity"||/^Channel Divinity \(\d+\/rest\)$/.test(name))return channelDivinity(character);
    if(name==="Divine Spark")return divineSpark(character);
    if(name==="Channel Divinity: Preserve Life"||name==="Preserve Life")return preserveLife(character);
    if(name.startsWith("Destroy Undead (CR "))return destroyUndead(character);
    if(name==="Sear Undead")return searUndead(character);
    if(name==="Blessed Healer")return blessedHealer(character);
    if(name==="Divine Strike")return divineStrike(character);
    if(name==="Blessed Strikes")return blessedStrikes(character,false);
    if(name==="Divine Intervention")return divineIntervention(character);
    if(name==="Improved Blessed Strikes")return blessedStrikes(character,true);
    if(name==="Supreme Healing")return supremeHealing(character);
    if(name==="Greater Divine Intervention")return greaterDivineIntervention(character);
    if(name==="Survivor")return survivor(character);
    return null;
  }catch(error){console.error(`[reference] dynamic ${name} failed`,error);throw error;}
}
function spellcasting(character){
  try{const base="Use the spell section above for save DC, attack bonus, slots, and prepared spells. Expended spell slots return after a Long Rest.";if(character.ruleset==="2014"&&character.class.id==="wizard")return{category:"Wizard",timing:"Magic / Ritual",text:`${base} A Ritual-tag spell in your spellbook can be cast as a Ritual without being prepared.`};if(character.ruleset==="2014"&&character.class.id==="cleric")return{category:"Cleric",timing:"Magic / Ritual",text:`${base} A prepared Cleric spell with the Ritual tag can be cast as a Ritual.`};if(character.ruleset==="2024"&&character.class.id==="wizard")return{category:"Wizard",timing:"Magic",text:`${base} After a Long Rest, you can replace prepared level 1+ spells with legal spells from your spellbook; Wizard features that are always prepared do not consume this prepared-spell count.`};return{category:"Cleric",timing:"Magic",text:`${base} After a Long Rest, you can replace prepared level 1+ spells with other Cleric spells for which you have slots. Life Domain spells are always prepared and do not consume the normal prepared count.`};}catch(error){console.error("[reference] spellcasting failed",error);throw error;}
}
function spellMastery(character){try{const mastery=character.spells?.spellMastery;if(!mastery)throw new Error("Spell Mastery state is missing.");const first=wizardSpellName(character,mastery.level1),second=wizardSpellName(character,mastery.level2);if(character.ruleset==="2014")return rr("Wizard","At will while prepared / 8 hours study",`${first} (level 1) and ${second} (level 2) are this character's mastered spells. This Forge loadout has both prepared, and they count against the normal prepared-spell total. While prepared, each can be cast at its lowest level without a spell slot; higher-level casts use slots. After 8 hours of study, either or both can be exchanged for same-level Wizard spells in the spellbook.`);return rr("Wizard","At will / after Long Rest",`${first} (level 1) and ${second} (level 2) are always prepared and can be cast at their lowest level without a spell slot. Higher-level casts use slots. After a Long Rest, one mastered spell can be replaced by an eligible same-level spell in the spellbook.`);}catch(error){console.error("[reference] Spell Mastery failed",error);throw error;}}
function signatureSpells(character){try{const ids=character.spells?.signatureSpells||[];if(ids.length!==2)throw new Error("Signature Spell state requires two spells.");return rr("Wizard","Free cast / Short or Long Rest",`${ids.map(id=>wizardSpellName(character,id)).join(" and ")} are always prepared. Each can be cast once at level 3 without a spell slot; each free cast refreshes after a Short or Long Rest. Higher-level casts use slots.`);}catch(error){console.error("[reference] Signature Spells failed",error);throw error;}}
function wizardSpellName(character,id){try{return wizardSpellsFor(character.ruleset).find(spell=>spell.id===id)?.name||id;}catch(error){console.error("[reference] Wizard spell name failed",error);throw error;}}
function secondWind(character){try{const healing=`1d10 + ${character.level} HP`;if(character.ruleset==="2014")return{category:"Fighter",timing:"Bonus Action",text:`Regain ${healing}. One use; regain it after a Short or Long Rest.`};const uses=character.fighter?.secondWindUses;if(!Number.isInteger(uses))throw new Error("2024 Second Wind reference requires Fighter progression data.");return{category:"Fighter",timing:"Bonus Action",text:`Regain ${healing}. ${uses} uses; regain one expended use after a Short Rest and all expended uses after a Long Rest.`};}catch(error){console.error("[reference] Second Wind failed",error);throw error;}}
function actionSurge(character){try{const uses=character.fighter?.actionSurgeUses;if(!Number.isInteger(uses))throw new Error("Action Surge reference requires Fighter progression data.");const restriction=character.ruleset==="2024"?" The additional action cannot be the Magic action.":"";return{category:"Fighter",timing:"On your turn",text:`Take one additional action.${restriction} ${uses} use${uses===1?"":"s"} between rests; regain all uses after a Short or Long Rest${uses>1?", and use it no more than once on the same turn":""}.`};}catch(error){console.error("[reference] Action Surge failed",error);throw error;}}
function abilityScoreImprovement(character){try{const levels=character.class.asiLevels||[4],count=levels.filter(level=>character.level>=level).length;if(count<1)throw new Error("ASI reference requires at least one earned ASI level.");return{category:"Class",timing:"Applied",text:`${count} Ability Score Improvement opportunit${count===1?"y has":"ies have"} been earned at this level and the generated legal increases are already included in the ability scores above.`};}catch(error){console.error("[reference] Ability Score Improvement failed",error);throw error;}}
function extraAttack(character){try{const attacks=character.fighter?.attacksPerAction;if(!Number.isInteger(attacks))throw new Error("Extra Attack reference requires Fighter progression data.");return{category:"Fighter",timing:"Attack action",text:`Attack ${numberWord(attacks)} times instead of once whenever you take the Attack action on your turn.`};}catch(error){console.error("[reference] Extra Attack failed",error);throw error;}}
function indomitable(character){try{const uses=character.fighter?.indomitableUses;if(!Number.isInteger(uses)||uses<1)throw new Error("Indomitable reference requires active Fighter progression data.");const bonus=character.ruleset==="2024"?` with a +${character.level} bonus`:"";return{category:"Fighter",timing:"Failed saving throw",text:`Reroll a failed saving throw${bonus} and use the new roll. ${uses} use${uses===1?"":"s"}; regain all uses after a Long Rest.`};}catch(error){console.error("[reference] Indomitable failed",error);throw error;}}
function remarkableAthlete(character){try{if(character.ruleset==="2014"){const bonus=Math.ceil(character.proficiency/2),jump=abilityMod(character.abilities.str);return{category:"Champion",timing:"Ability checks / running jump",text:`Add +${bonus} to Strength, Dexterity, or Constitution checks that do not already use your Proficiency Bonus. Your running long-jump distance also changes by ${jump} ft from this feature.`};}return{category:"Champion",timing:"Passive / after crit",text:`You have Advantage on Initiative rolls and Strength (Athletics) checks. Immediately after a Critical Hit, move up to ${Math.floor(character.speed/2)} ft without provoking Opportunity Attacks.`};}catch(error){console.error("[reference] Remarkable Athlete failed",error);throw error;}}
function additionalFightingStyle(character){try{const styles=(character.fightingStyles||[]).map(style=>style.name).join(" + ");return{category:"Champion",timing:"Passive",text:`You have a second Fighting Style. Active styles: ${styles}. Each style is listed separately with its own mechanics and source citation.`};}catch(error){console.error("[reference] Additional Fighting Style failed",error);throw error;}}
function superiorCritical(character){try{return character.ruleset==="2014"?{category:"Champion",timing:"Passive",text:"Your weapon attacks score a Critical Hit on a d20 roll of 18–20."}:{category:"Champion",timing:"Passive",text:"Weapon and Unarmed Strike attack rolls score a Critical Hit on a d20 roll of 18–20."};}catch(error){console.error("[reference] Superior Critical failed",error);throw error;}}
function survivor(character){try{const healing=5+abilityMod(character.abilities.con);if(character.ruleset==="2014")return{category:"Champion",timing:"Start of turn",text:`If you have at least 1 HP and no more than half your maximum HP, regain ${healing} HP at the start of each of your turns.`};return{category:"Champion",timing:"Passive / start of turn",text:`You have Advantage on Death Saving Throws, and a death save roll of 18–20 gains the benefit of a 20. While Bloodied with at least 1 HP, regain ${healing} HP at the start of each turn.`};}catch(error){console.error("[reference] Survivor failed",error);throw error;}}
function arcaneRecovery(character){try{const levels=Math.ceil(character.level/2),limit=`up to ${levels} total spell-slot level${levels===1?"":"s"}`;return character.ruleset==="2014"?{category:"Wizard",timing:"After Short Rest",text:`Once per day, recover expended slots totaling ${limit}; none can be level 6+.`}:{category:"Wizard",timing:"After Short Rest",text:`Recover expended slots totaling ${limit}; none can be level 6+. Once used, it returns after a Long Rest.`};}catch(error){console.error("[reference] Arcane Recovery failed",error);throw error;}}
function channelDivinity(character){try{const uses=character.cleric?.channelDivinityUses;if(!Number.isInteger(uses)||uses<1)throw new Error("Channel Divinity reference requires active Cleric progression data.");if(character.ruleset==="2014")return rr("Cleric","Resource",`${uses} use${uses===1?"":"s"} fuel Turn Undead or Preserve Life. Regain all expended uses after a Short or Long Rest.`);return rr("Cleric","Resource",`${uses} uses fuel Divine Spark, Turn Undead, or a subclass Channel Divinity option. Regain one expended use after a Short Rest and all expended uses after a Long Rest.`);}catch(error){console.error("[reference] Channel Divinity failed",error);throw error;}}
function divineSpark(character){try{const dice=character.cleric?.divineSparkDice,wis=abilityMod(character.abilities.wis);if(!Number.isInteger(dice)||dice<1)throw new Error("Divine Spark reference requires active Cleric progression data.");return rr("Cleric","Magic action · Channel Divinity",`Choose another creature you can see within 30 ft. Roll ${dice}d8 ${signed(wis)}: restore that many Hit Points, or force a Constitution save against DC ${character.spells.saveDc} for that much Radiant or Necrotic damage; a successful save takes half.`);}catch(error){console.error("[reference] Divine Spark failed",error);throw error;}}
function preserveLife(character){try{const pool=5*character.level;if(character.ruleset==="2014")return{category:"Life Domain",timing:"Action · Channel Divinity",text:`Distribute up to ${pool} HP among creatures within 30 ft, but no creature can be healed above half its maximum. It has no effect on Undead or Constructs.`};return{category:"Life Domain",timing:"Magic action · Channel Divinity",text:`Distribute up to ${pool} HP among Bloodied creatures within 30 ft, including yourself, but no creature can be healed above half its maximum.`};}catch(error){console.error("[reference] Preserve Life failed",error);throw error;}}
function destroyUndead(character){try{const cr=character.cleric?.destroyUndeadCr;if(!cr)throw new Error("Destroy Undead reference requires an active CR threshold.");return rr("Cleric","With Turn Undead",`When an Undead of CR ${cr} or lower fails its saving throw against Turn Undead, it is instantly destroyed instead of being turned.`);}catch(error){console.error("[reference] Destroy Undead failed",error);throw error;}}
function searUndead(character){try{const dice=Math.max(1,abilityMod(character.abilities.wis));return{category:"Cleric",timing:"With Turn Undead",text:`Roll ${dice}d8. Each Undead that fails its Turn Undead save takes that much Radiant damage; this damage does not end the turning effect.`};}catch(error){console.error("[reference] Sear Undead failed",error);throw error;}}
function blessedHealer(character){try{if(character.ruleset==="2014")return rr("Life Domain","Level 1+ healing spell",`When a spell of level 1 or higher that you cast restores Hit Points to a creature other than you, you regain Hit Points equal to 2 + the spell's level.`);return rr("Life Domain","Healing spell with slot",`When a spell you cast with a spell slot restores Hit Points to a creature other than you, you also regain Hit Points equal to 2 + the slot's level.`);}catch(error){console.error("[reference] Blessed Healer failed",error);throw error;}}
function divineStrike(character){try{if(character.ruleset!=="2014")throw new Error("Legacy Divine Strike reference is only valid for 2014 Cleric.");const dice=character.level>=14?"2d8":"1d8";return rr("Life Domain","Once per turn · weapon hit",`When you hit a creature with a weapon attack, deal an extra ${dice} Radiant damage. This benefit applies once on each of your turns.`);}catch(error){console.error("[reference] Divine Strike failed",error);throw error;}}
function blessedStrikes(character,improved){try{const wis=abilityMod(character.abilities.wis);if(character.blessedStrikes==="divine-strike")return rr("Cleric",improved?"Once per turn · weapon hit":"Once per turn · weapon hit",`Divine Strike adds ${improved?"2d8":"1d8"} Radiant or Necrotic damage to one weapon hit on your turn.`);if(character.blessedStrikes==="potent-spellcasting"){const extra=improved?` When a Cleric cantrip deals damage, you can also give yourself or one creature within 60 ft ${Math.max(0,2*wis)} Temporary Hit Points.`:"";return rr("Cleric","Cleric cantrip damage",`Potent Spellcasting adds your Wisdom modifier (${signed(wis)}) to the damage of Cleric cantrips.${extra}`);}throw new Error("Blessed Strikes reference requires a legal choice.");}catch(error){console.error("[reference] Blessed Strikes failed",error);throw error;}}
function divineIntervention(character){try{if(character.ruleset==="2014"){const threshold=character.cleric?.divineInterventionThreshold;if(!threshold)throw new Error("2014 Divine Intervention progression is missing.");if(threshold==="automatic")return rr("Cleric","Action · automatic at level 20",`Describe the assistance you seek from your deity. Divine Intervention succeeds automatically at Cleric level 20. The GM chooses the nature of the intervention; a Cleric or domain spell effect is appropriate. After a successful intervention, you cannot use this feature again for 7 days.`);return rr("Cleric","Action · percentile roll",`Describe the assistance you seek from your deity, then roll percentile dice. If the result is ${threshold} or lower, your deity intervenes. The GM chooses the nature of the intervention; a Cleric or domain spell effect is appropriate. After success, this feature cannot be used again for 7 days; after failure, it returns after a Long Rest.`);}return rr("Cleric","Magic action · Long Rest",`Choose a Cleric spell of level 5 or lower that does not require a Reaction to cast. As this Magic action, cast it without expending a spell slot or providing Material components. After using Divine Intervention, you cannot use it again until you finish a Long Rest.`);}catch(error){console.error("[reference] Divine Intervention failed",error);throw error;}}
function supremeHealing(character){try{if(character.ruleset==="2014")return rr("Life Domain","Healing spell",`When you would normally roll one or more dice to restore Hit Points with a spell, use the highest number possible for each die instead.`);return rr("Life Domain","Healing roll",`Whenever you would roll one or more dice to restore Hit Points with a spell or Channel Divinity, use the highest possible result on each healing die instead.`);}catch(error){console.error("[reference] Supreme Healing failed",error);throw error;}}
function greaterDivineIntervention(character){try{return rr("Cleric","Divine Intervention",`Divine Intervention can now choose Wish. If you use it to cast Wish, you cannot use Divine Intervention again until you finish 2d4 Long Rests.`);}catch(error){console.error("[reference] Greater Divine Intervention failed",error);throw error;}}
function goliathBenefit(id,character){try{const con=abilityMod(character.abilities.con);return({cloud:"As a Bonus Action, teleport up to 30 ft to an unoccupied space you can see.",fire:"When an attack roll hits and deals damage, deal an extra 1d10 Fire damage.",frost:"When an attack roll hits and deals damage, deal an extra 1d6 Cold damage and reduce the target's Speed by 10 ft until the start of your next turn.",hill:"When an attack roll hits a Large or smaller creature and deals damage, give it the Prone condition.",stone:`As a Reaction when you take damage, reduce that damage by 1d12 ${con>=0?"+":"−"} ${Math.abs(con)} (your Constitution modifier).`,storm:"As a Reaction when a creature within 60 ft damages you, deal 1d8 Thunder damage to it."})[id]||"Unknown Giant Ancestry benefit.";}catch(error){console.error("[reference] Goliath benefit failed",error);throw error;}}
function abilityName(id){try{return({int:"Intelligence",wis:"Wisdom",cha:"Charisma"})[id]||String(id);}catch(error){console.error("[reference] ability name failed",error);throw error;}}
function rr(category,timing,text){return{category,timing,text};}
function numberWord(value){try{return({1:"once",2:"twice",3:"three",4:"four"})[value]||String(value);}catch(error){console.error("[reference] number word failed",error);throw error;}}
function push(character,items,id,name,entry){try{const kind=id.split(":",1)[0],source=referenceProvenance(character,kind,name);items.push({id,name,...entry,source});}catch(error){console.error(`[reference] provenance attach failed for ${name}`,error);throw error;}}
function required(entry,name){try{if(!entry)throw new Error(`Missing quick reference for ${name}.`);return entry;}catch(error){console.error(`[reference] required entry failed for ${name}`,error);throw error;}}
function pretty(value){try{return String(value||"the chosen skill").replace(/([A-Z])/g," $1").replace(/^./,char=>char.toUpperCase());}catch(error){console.error("[reference] pretty label failed",error);throw error;}}
function signed(value){return value>=0?`+ ${value}`:`− ${Math.abs(value)}`;}
