import { ABILITIES, SOURCE } from "../schema.js";
import { abilityMod } from "./math.js";
import { lifeDomainAlwaysPrepared } from "./cleric.js";
import { barbarianProgression, barbarianUnarmoredAc, barbarianSpeed } from "./barbarian.js";
import { BARBARIAN_ADVANCEMENT } from "./barbarian-advancement.js";
import { rogueExpertiseCount, rogueExtraSaveProficiencies, rogueProgression } from "./rogue.js";
import { ROGUE_ADVANCEMENT } from "./rogue-advancement.js";
import { fighterProgression } from "./fighter.js";
import { FIGHTER_ADVANCEMENT } from "./fighter-advancement.js";
import { monkExtraSaveProficiencies, monkFlurryStrikes, monkProgression, monkSpeed, monkUnarmoredAc } from "./monk.js";
import { MONK_ADVANCEMENT } from "./monk-advancement.js";
import { duplicateValues } from "./duplicates.js";

const CLERIC_CANTRIPS={1:3,2:3,3:3,4:4,5:4},CLERIC_PREPARED_2024={1:4,2:5,3:6,4:7,5:9};
export function validateCharacter(character,mode){
  try{
    const errors=[];
    if(mode!==SOURCE.RAW)errors.push("Production Character Forge accepts RAW characters only.");if(character.sourceMode!==SOURCE.RAW)errors.push("Generated character source must be RAW.");if(character.homebrew.length)errors.push("RAW characters cannot contain Homebrew content.");
    const maxLevel=character.class.maxLevel||5;if(character.level<1||character.level>maxLevel)errors.push(`${character.class.name} is validated through level ${maxLevel}.`);
    for(const ability of ABILITIES){const max=character.abilityMaximums[ability]??20;if(character.abilities[ability]>max)errors.push(`${ability.toUpperCase()} exceeds its maximum.`);if(character.abilities[ability]<1)errors.push(`${ability.toUpperCase()} is below 1.`);}
    checkDuplicates(errors,"skill proficiencies",character.skills);checkDuplicates(errors,"expertise entries",character.expertise);checkDuplicates(errors,"saving throw proficiencies",character.saves);checkDuplicates(errors,"languages",character.languages);checkDuplicates(errors,"feats",character.feats,item=>item.id);checkDuplicates(errors,"feat names",character.feats,item=>item.name);checkDuplicates(errors,"Homebrew entries",character.homebrew,item=>item.id);checkDuplicates(errors,"Homebrew names",character.homebrew,item=>item.name);checkDuplicates(errors,"weapon masteries",character.masteryIds);checkDuplicates(errors,"attack entries",character.attacks,item=>item.name);checkDuplicates(errors,"features",character.features);checkDuplicates(errors,"Fighting Styles",character.fightingStyles||[],item=>item.id);
    if(character.skills.length<character.class.skillCount)errors.push(`${character.class.name} is missing skill proficiencies.`);if(character.subclass&&character.level<character.class.subclassLevel)errors.push(`${character.class.name} subclass cannot be active before level ${character.class.subclassLevel}.`);if(character.expertise.some(skill=>!character.skills.includes(skill)))errors.push("Expertise requires an existing skill proficiency.");
    if(character.class.id==="barbarian")validateBarbarian(errors,character);if(character.class.id==="rogue")validateRogue(errors,character);if(character.class.id==="fighter")validateFighter(errors,character);if(character.class.id==="monk")validateMonk(errors,character);if(character.class.spellcasting==="wizard")validateWizard(errors,character);if(character.class.spellcasting==="cleric")validateCleric(errors,character);if(!Number.isInteger(character.ac)||character.ac<1)errors.push("Armor Class failed calculation.");if(!Number.isInteger(character.hp)||character.hp<1)errors.push("Hit Points failed calculation.");return{valid:errors.length===0,errors};
  }catch(error){console.error("[validation] character validation failed",error);throw error;}
}
function validateBarbarian(errors,character){try{const row=barbarianProgression(character.ruleset,character.level),resources=Object.fromEntries((character.classResources||[]).map(item=>[item.id,item.value]));if(resources["rage-uses"]!==String(row.rages))errors.push("Barbarian Rage uses do not match the class table.");if(resources["rage-damage"]!==`+${row.rageDamage}`)errors.push("Barbarian Rage Damage does not match the class table.");const expectedMasteries=character.ruleset==="2024"?row.masteries:0;if(character.masteryIds.length!==expectedMasteries)errors.push(`Barbarian Weapon Mastery count should be ${expectedMasteries}.`);const expectedSkills=character.class.skillCount+(character.ruleset==="2024"&&character.level>=3?1:0);if(character.skills.length<expectedSkills)errors.push(`Barbarian should have at least ${expectedSkills} class/background skill proficiencies at this level.`);if(!character.equipment.armor){const expectedAc=barbarianUnarmoredAc(character.abilities,character.equipment.shield);if(character.ac!==expectedAc)errors.push(`Barbarian Unarmored Defense should produce AC ${expectedAc}.`);}const expectedSpeed=barbarianSpeed(character.species.speed,character.level,false);if(character.speed!==expectedSpeed)errors.push(`Barbarian speed should be ${expectedSpeed} ft at this level.`);if(character.level>=3&&character.subclass?.id!=="path-berserker")errors.push("Verified Barbarian levels 3+ require the SRD Path of the Berserker subclass.");validateBarbarianAdvancement(errors,character);}catch(error){console.error("[validation] Barbarian validation failed",error);throw error;}}
function validateBarbarianAdvancement(errors,character){try{const choices=character.advancementChoices||[],levels=character.ruleset==="2014"?BARBARIAN_ADVANCEMENT.levels2014:BARBARIAN_ADVANCEMENT.normal2024,expected=levels.filter(level=>character.level>=level);if(character.ruleset==="2024"&&character.level>=19)expected.push(19);if(choices.length!==expected.length)errors.push(`Barbarian advancement choice count should be ${expected.length}.`);if(choices.some((choice,index)=>choice.level!==expected[index]))errors.push("Barbarian advancement levels are out of sequence.");if(character.feats.filter(feat=>feat.id==="grappler").length>1)errors.push("Grappler cannot be selected more than once.");if(character.feats.some(feat=>feat.id==="grappler")&&character.ruleset==="2014"&&character.abilities.str<13)errors.push("2014 Grappler requires Strength 13+.");if(character.ruleset==="2024"){const normal=choices.filter(choice=>choice.level<19);if(normal.some(choice=>!["ability-score-improvement","grappler"].includes(choice.id)))errors.push("2024 Barbarian normal feat levels contain an ineligible General feat.");if(character.level>=19){const epic=choices.find(choice=>choice.level===19);if(!epic||!BARBARIAN_ADVANCEMENT.epicBoons.includes(epic.id))errors.push("Level 19+ Barbarian is missing an eligible SRD Epic Boon.");if(epic&&!character.feats.some(feat=>feat.id===epic.id))errors.push("Selected Epic Boon is missing from feat records.");}}else if(choices.some(choice=>choice.type==="feat"&&choice.id!=="grappler"))errors.push("2014 SRD Barbarian may replace an ASI only with Grappler.");}catch(error){console.error("[validation] Barbarian advancement validation failed",error);throw error;}}
function validateRogue(errors,character){
  try{
    const row=rogueProgression(character.ruleset,character.level),resources=Object.fromEntries((character.classResources||[]).map(item=>[item.id,item.value]));
    if(resources["sneak-attack"]!==row.sneakAttack)errors.push(`Rogue Sneak Attack should be ${row.sneakAttack}.`);
    if(character.expertise.length!==rogueExpertiseCount(character.level))errors.push(`Rogue Expertise count should be ${rogueExpertiseCount(character.level)}.`);
    const expectedSaves=new Set(["dex","int",...rogueExtraSaveProficiencies(character.ruleset,character.level)]);for(const save of expectedSaves)if(!character.saves.includes(save))errors.push(`Rogue is missing ${save.toUpperCase()} save proficiency.`);
    const expectedMasteries=character.ruleset==="2024"?2:0;if(character.masteryIds.length!==expectedMasteries)errors.push(`Rogue Weapon Mastery count should be ${expectedMasteries}.`);
    if(character.ruleset==="2024"&&!character.languages.includes("Thieves' Cant"))errors.push("2024 Rogue is missing Thieves' Cant.");
    if(character.level>=3&&character.subclass?.id!=="thief")errors.push("Verified Rogue levels 3+ require the SRD Thief subclass.");
    validateRogueAdvancement(errors,character);
  }catch(error){console.error("[validation] Rogue validation failed",error);throw error;}
}
function validateRogueAdvancement(errors,character){
  try{
    const choices=character.advancementChoices||[],levels=character.ruleset==="2014"?ROGUE_ADVANCEMENT.levels2014:ROGUE_ADVANCEMENT.levels2024,expected=levels.filter(level=>character.level>=level);if(character.ruleset==="2024"&&character.level>=19)expected.push(19);
    if(choices.length!==expected.length)errors.push(`Rogue advancement choice count should be ${expected.length}.`);if(choices.some((choice,index)=>choice.level!==expected[index]))errors.push("Rogue advancement levels are out of sequence.");
    if(character.ruleset==="2024"){const normal=choices.filter(choice=>choice.level<19);if(normal.some(choice=>!["ability-score-improvement","grappler"].includes(choice.id)))errors.push("2024 Rogue normal feat levels contain an ineligible General feat.");if(character.level>=19){const epic=choices.find(choice=>choice.level===19);if(!epic||!ROGUE_ADVANCEMENT.epicBoons.includes(epic.id))errors.push("Level 19+ Rogue is missing an eligible SRD Epic Boon.");}}
    else if(choices.some(choice=>choice.type!=="asi"))errors.push("Current verified 2014 Rogue advancement uses legal Ability Score Improvements only.");
  }catch(error){console.error("[validation] Rogue advancement validation failed",error);throw error;}
}
function validateFighter(errors,character){
  try{
    const row=fighterProgression(character.ruleset,character.level),resources=Object.fromEntries((character.classResources||[]).map(item=>[item.id,item.value]));
    const secondWind=character.ruleset==="2024"?row.secondWind:1;if(resources["second-wind"]!==String(secondWind))errors.push(`Fighter Second Wind uses should be ${secondWind}.`);
    if(row.actionSurge&&resources["action-surge"]!==String(row.actionSurge))errors.push(`Fighter Action Surge uses should be ${row.actionSurge}.`);
    if(row.indomitable&&resources.indomitable!==String(row.indomitable))errors.push(`Fighter Indomitable uses should be ${row.indomitable}.`);
    if(resources["attacks-per-action"]!==String(row.attacks))errors.push(`Fighter attacks per Attack action should be ${row.attacks}.`);
    const expectedMasteries=character.ruleset==="2024"?row.masteries:0;if(character.masteryIds.length!==expectedMasteries)errors.push(`Fighter Weapon Mastery count should be ${expectedMasteries}.`);
    const getsSecond=character.level>=3&&character.subclass?.id==="champion"&&(character.ruleset==="2014"?character.level>=10:character.level>=7),expectedStyles=getsSecond?2:1;
    if((character.fightingStyles||[]).length!==expectedStyles)errors.push(`Fighter should have ${expectedStyles} distinct Fighting Style${expectedStyles===1?"":"s"} at this level.`);
    if(character.fightingStyle?.id!==character.fightingStyles?.[0]?.id)errors.push("Primary Fighting Style must match the first style entry.");
    if(character.level>=3&&character.subclass?.id!=="champion")errors.push("Verified Fighter levels 3+ require the SRD Champion subclass.");
    validateFighterAdvancement(errors,character);
  }catch(error){console.error("[validation] Fighter validation failed",error);throw error;}
}
function validateFighterAdvancement(errors,character){
  try{
    const choices=character.advancementChoices||[],levels=character.ruleset==="2014"?FIGHTER_ADVANCEMENT.levels2014:FIGHTER_ADVANCEMENT.levels2024,expected=levels.filter(level=>character.level>=level);if(character.ruleset==="2024"&&character.level>=19)expected.push(19);
    if(choices.length!==expected.length)errors.push(`Fighter advancement choice count should be ${expected.length}.`);if(choices.some((choice,index)=>choice.level!==expected[index]))errors.push("Fighter advancement levels are out of sequence.");if(character.feats.filter(feat=>feat.id==="grappler").length>1)errors.push("Fighter cannot select Grappler more than once.");
    if(character.ruleset==="2014"){if(choices.some(choice=>choice.type==="feat"&&choice.id!=="grappler"))errors.push("2014 SRD Fighter may replace an ASI only with Grappler.");if(character.feats.some(feat=>feat.id==="grappler")&&character.abilities.str<13)errors.push("2014 Fighter Grappler requires Strength 13+.");}
    else{const normal=choices.filter(choice=>choice.level<19);if(normal.some(choice=>!["ability-score-improvement","grappler"].includes(choice.id)))errors.push("2024 Fighter normal feat levels contain an ineligible General feat.");if(character.level>=19){const epic=choices.find(choice=>choice.level===19);if(!epic||!FIGHTER_ADVANCEMENT.epicBoons.includes(epic.id))errors.push("Level 19+ Fighter is missing an eligible SRD Epic Boon.");if(epic&&!character.feats.some(feat=>feat.id===epic.id))errors.push("Selected Fighter Epic Boon is missing from feat records.");}}
  }catch(error){console.error("[validation] Fighter advancement validation failed",error);throw error;}
}
function validateMonk(errors,character){
  try{
    const row=monkProgression(character.ruleset,character.level),resources=Object.fromEntries((character.classResources||[]).map(item=>[item.id,item.value]));
    if(resources["martial-arts"]!==row.martialArts)errors.push(`Monk Martial Arts die should be ${row.martialArts}.`);
    if(character.level>=2&&resources[character.ruleset==="2014"?"ki":"focus"]!==character.level)errors.push(`Monk ${character.ruleset==="2014"?"Ki":"Focus"} points should be ${character.level}.`);
    if(row.unarmoredMovement>0&&resources["unarmored-movement"]!==`+${row.unarmoredMovement} ft.`)errors.push(`Monk Unarmored Movement should be +${row.unarmoredMovement} ft.`);
    if(resources["flurry-strikes"]!==`${monkFlurryStrikes(character.ruleset,character.level)} strikes`)errors.push("Monk Flurry of Blows strike count is incorrect.");
    if(character.equipment.armor||character.equipment.shield)errors.push("Verified Monk starting equipment must be unarmored and use no shield.");
    const expectedAc=monkUnarmoredAc(character.abilities);if(character.ac!==expectedAc)errors.push(`Monk Unarmored Defense should produce AC ${expectedAc}.`);
    const expectedSpeed=monkSpeed(character.species.speed,character.ruleset,character.level,{armored:false,shield:false});if(character.speed!==expectedSpeed)errors.push(`Monk speed should be ${expectedSpeed} ft at this level.`);
    for(const save of ["str","dex",...monkExtraSaveProficiencies(character.level)])if(!character.saves.includes(save))errors.push(`Monk is missing ${save.toUpperCase()} save proficiency.`);if(character.level>=14&&character.saves.length!==6)errors.push("Level 14+ Monk should be proficient in all six saving throws.");
    if(character.masteryIds.length!==0)errors.push("Monk should not receive Weapon Mastery from the class progression.");
    if(character.level>=3&&character.subclass?.id!=="open-hand")errors.push("Verified Monk levels 3+ require the SRD Open Hand subclass.");
    const unarmed=character.attacks.find(attack=>attack.id==="unarmed-strike");if(!unarmed)errors.push("Monk is missing its Unarmed Strike attack entry.");else{const dex=abilityMod(character.abilities.dex);if(unarmed.damage!==row.martialArts)errors.push(`Monk Unarmed Strike should use ${row.martialArts}.`);if(unarmed.ability!=="dex")errors.push("Monk Unarmed Strike should use Dexterity in this generated build.");if(unarmed.attackBonus!==dex+character.proficiency)errors.push("Monk Unarmed Strike attack bonus is incorrect.");if(unarmed.damageBonus!==dex)errors.push("Monk Unarmed Strike damage bonus is incorrect.");if(character.ruleset==="2024"&&character.level>=6&&!String(unarmed.type).includes("Force"))errors.push("2024 level 6+ Monk Empowered Strikes should expose Force damage.");}
    for(const attack of character.attacks.filter(attack=>attack.id!=="unarmed-strike"))if(attack.ability!=="dex")errors.push(`Monk weapon attack ${attack.name} should use Dexterity in this generated build.`);
    if(character.ruleset==="2024"&&character.level>=20&&((character.abilityMaximums.dex||20)<25||(character.abilityMaximums.wis||20)<25))errors.push("2024 level 20 Monk Body and Mind requires Dexterity and Wisdom maxima of at least 25.");
    validateMonkAdvancement(errors,character);
  }catch(error){console.error("[validation] Monk validation failed",error);throw error;}
}
function validateMonkAdvancement(errors,character){
  try{
    const choices=character.advancementChoices||[],levels=character.ruleset==="2014"?MONK_ADVANCEMENT.levels2014:MONK_ADVANCEMENT.normal2024,expected=levels.filter(level=>character.level>=level);if(character.ruleset==="2024"&&character.level>=19)expected.push(19);
    if(choices.length!==expected.length)errors.push(`Monk advancement choice count should be ${expected.length}.`);if(choices.some((choice,index)=>choice.level!==expected[index]))errors.push("Monk advancement levels are out of sequence.");if(character.feats.filter(feat=>feat.id==="grappler").length>1)errors.push("Monk cannot select Grappler more than once.");
    if(character.ruleset==="2014"){if(choices.some(choice=>choice.type==="feat"&&choice.id!=="grappler"))errors.push("2014 SRD Monk may replace an ASI only with Grappler.");if(character.feats.some(feat=>feat.id==="grappler")&&character.abilities.str<13)errors.push("2014 Monk Grappler requires Strength 13+.");}
    else{const normal=choices.filter(choice=>choice.level<19);if(normal.some(choice=>!["ability-score-improvement","grappler"].includes(choice.id)))errors.push("2024 Monk normal feat levels contain an ineligible General feat.");if(character.level>=19){const epic=choices.find(choice=>choice.level===19);if(!epic||!MONK_ADVANCEMENT.epicBoons.includes(epic.id))errors.push("Level 19+ Monk is missing an eligible SRD Epic Boon.");if(epic&&!character.feats.some(feat=>feat.id===epic.id))errors.push("Selected Monk Epic Boon is missing from feat records.");}}
  }catch(error){console.error("[validation] Monk advancement validation failed",error);throw error;}
}
function validateWizard(errors,character){try{if(!character.spells){errors.push("Wizard spellcasting data is missing.");return;}checkDuplicates(errors,"Wizard cantrips",character.spells.cantrips.all);checkDuplicates(errors,"Wizard spellbook spells",character.spells.spellbook.all);checkDuplicates(errors,"prepared Wizard spells",character.spells.prepared.all);const book=new Set(character.spells.spellbook.all),outside=character.spells.prepared.all.filter(id=>!book.has(id));if(outside.length)errors.push(`Prepared Wizard spells missing from spellbook: ${outside.join(", ")}.`);if(!Number.isInteger(character.spells.saveDc)||!Number.isInteger(character.spells.attackBonus))errors.push("Wizard spellcasting math failed.");}catch(error){console.error("[validation] Wizard validation failed",error);throw error;}}
function validateCleric(errors,character){try{if(!character.spells){errors.push("Cleric spellcasting data is missing.");return;}const spells=character.spells,always=spells.alwaysPrepared||[];checkDuplicates(errors,"Cleric cantrips",spells.cantrips.all);checkDuplicates(errors,"prepared Cleric spells",spells.prepared.all);checkDuplicates(errors,"always-prepared Cleric spells",always);const overlap=spells.prepared.all.filter(id=>always.includes(id));if(overlap.length)errors.push(`Life Domain spells must not consume normal prepared slots: ${overlap.join(", ")}.`);const expectedCantrips=CLERIC_CANTRIPS[character.level]+(character.ruleset==="2024"&&character.divineOrder==="thaumaturge"?1:0),expectedPrepared=character.ruleset==="2024"?CLERIC_PREPARED_2024[character.level]:Math.max(1,character.level+abilityMod(character.abilities.wis)),expectedAlways=lifeDomainAlwaysPrepared(character.ruleset,character.level);if(spells.cantrips.all.length!==expectedCantrips)errors.push(`Cleric cantrip count should be ${expectedCantrips}.`);if(spells.prepared.all.length!==expectedPrepared)errors.push(`Cleric prepared-spell count should be ${expectedPrepared}.`);if(always.length!==expectedAlways.length||expectedAlways.some(id=>!always.includes(id)))errors.push("Life Domain always-prepared spells are incomplete.");if(character.ruleset==="2024"&&!['protector','thaumaturge'].includes(character.divineOrder))errors.push("2024 Cleric Divine Order is invalid.");if(!Number.isInteger(spells.saveDc)||!Number.isInteger(spells.attackBonus))errors.push("Cleric spellcasting math failed.");}catch(error){console.error("[validation] Cleric validation failed",error);throw error;}}
function checkDuplicates(errors,label,values,keyFn=value=>value){try{const duplicates=duplicateValues(values||[],keyFn);if(duplicates.length)errors.push(`Duplicate ${label} detected: ${duplicates.join(", ")}.`);}catch(error){console.error(`[validation] duplicate check failed for ${label}`,error);throw error;}}
