import test from "node:test";
import assert from "node:assert/strict";
import { createInitialState } from "../src/state.js";
import { generateCharacter } from "../src/rules/generator.js";
import { buildQuickReference } from "../src/rules/reference.js";
import { BARBARIAN_TABLES, barbarianFeatures, barbarianProgression, barbarianResources } from "../src/rules/barbarian.js";
import { BARBARIAN_ADVANCEMENT } from "../src/rules/barbarian-advancement.js";

const RAGES_2014=[2,2,3,3,3,4,4,4,4,4,4,5,5,5,5,5,6,6,6,"Unlimited"],RAGE_DAMAGE=[2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,4,4,4,4,4],RAGES_2024=[2,2,3,3,3,4,4,4,4,4,4,5,5,5,5,5,6,6,6,6],MASTERY_2024=[2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4];
function barbarianState(ruleset,level="random"){const state=createInitialState();state.ruleset=ruleset;state.constraints.class="barbarian";state.constraints.level=String(level);return state;}

test("Barbarian progression covers every level 1-20 in both editions",()=>{for(const ruleset of ["2014","2024"]){assert.equal(Object.keys(BARBARIAN_TABLES[ruleset]).length,20);for(let level=1;level<=20;level++)assert.ok(barbarianProgression(ruleset,level));}});
test("2014 Rage uses and damage match the edition table exactly",()=>{for(let level=1;level<=20;level++){const row=barbarianProgression("2014",level);assert.equal(row.rages,RAGES_2014[level-1]);assert.equal(row.rageDamage,RAGE_DAMAGE[level-1]);assert.equal("masteries" in row,false);}});
test("2024 Rage uses, damage, and Weapon Mastery match the edition table exactly",()=>{for(let level=1;level<=20;level++){const row=barbarianProgression("2024",level);assert.equal(row.rages,RAGES_2024[level-1]);assert.equal(row.rageDamage,RAGE_DAMAGE[level-1]);assert.equal(row.masteries,MASTERY_2024[level-1]);}});
test("level 20 preserves edition difference in Rage uses",()=>{assert.equal(barbarianProgression("2014",20).rages,"Unlimited");assert.equal(barbarianProgression("2024",20).rages,6);});
test("Berserker subclass feature timing stays edition-correct",()=>{const old10=barbarianFeatures("2014",10,"path-berserker"),new10=barbarianFeatures("2024",10,"path-berserker");assert.ok(old10.includes("Intimidating Presence"));assert.ok(!old10.includes("Retaliation"));assert.ok(new10.includes("Retaliation"));assert.ok(!new10.includes("Intimidating Presence"));assert.ok(barbarianFeatures("2014",14,"path-berserker").includes("Retaliation"));assert.ok(barbarianFeatures("2024",14,"path-berserker").includes("Intimidating Presence"));});
test("Barbarian sheet resources derive from current level",()=>{const old20=Object.fromEntries(barbarianResources("2014",20).map(item=>[item.id,item.value])),new10=Object.fromEntries(barbarianResources("2024",10).map(item=>[item.id,item.value]));assert.equal(old20["rage-uses"],"Unlimited");assert.equal(old20["rage-damage"],"+4");assert.equal(old20["weapon-masteries"],undefined);assert.equal(new10["rage-uses"],"4");assert.equal(new10["rage-damage"],"+3");assert.equal(new10["weapon-masteries"],"4");});

test("both editions generate valid Barbarian characters at every level 1-20",()=>{for(const ruleset of ["2014","2024"])for(let level=1;level<=20;level++){const character=generateCharacter(barbarianState(ruleset,level));assert.equal(character.class.id,"barbarian");assert.equal(character.level,level);assert.equal(character.validation.valid,true);assert.equal(level>=3,Boolean(character.subclass));assert.doesNotThrow(()=>buildQuickReference(character));}});

test("2014 advancement makes five legal ASI-or-Grappler decisions by level 20",()=>{for(let i=0;i<200;i++){const character=generateCharacter(barbarianState("2014",20));assert.equal(character.advancementChoices.length,5);assert.deepEqual(character.advancementChoices.map(c=>c.level),[4,8,12,16,19]);assert.ok(character.advancementChoices.every(c=>c.type==="asi"||c.id==="grappler"));assert.ok(character.feats.filter(f=>f.id==="grappler").length<=1);if(character.feats.some(f=>f.id==="grappler"))assert.ok(character.abilities.str>=13);}});

test("2024 advancement uses General feats at 4/8/12/16 and an eligible Epic Boon at 19",()=>{for(let i=0;i<200;i++){const character=generateCharacter(barbarianState("2024",20)),choices=character.advancementChoices;assert.deepEqual(choices.map(c=>c.level),[4,8,12,16,19]);for(const choice of choices.slice(0,4))assert.ok(["ability-score-improvement","grappler"].includes(choice.id));const epic=choices[4];assert.equal(epic.type,"epic-boon");assert.ok(BARBARIAN_ADVANCEMENT.epicBoons.includes(epic.id));assert.ok(character.feats.some(feat=>feat.id===epic.id));assert.ok(!character.feats.some(feat=>feat.id==="boon-spell-recall"));assert.ok(character.feats.filter(f=>f.id==="grappler").length<=1);}});

test("2024 Barbarian masteries, Fast Movement, and high-level ability limits stay RAW",()=>{const level5=generateCharacter(barbarianState("2024",5)),level19=generateCharacter(barbarianState("2024",19)),level20=generateCharacter(barbarianState("2024",20));assert.equal(level5.speed,40);assert.equal(level5.masteryIds.length,3);const epic=level19.advancementChoices.find(c=>c.level===19),ability=Object.keys(epic.increases)[0];assert.ok(BARBARIAN_ADVANCEMENT.epicBoons.includes(epic.id));assert.ok(level19.abilities[ability]<=30);assert.ok(level19.abilityMaximums[ability]>=level19.abilities[ability]);assert.ok(level20.abilities.str<=25);assert.ok(level20.abilities.con<=25);assert.equal(level20.abilityMaximums.str,25);assert.equal(level20.abilityMaximums.con,25);});

test("2014 level 20 Barbarian applies Primal Champion and unlimited Rage",()=>{const character=generateCharacter(barbarianState("2014",20)),resources=Object.fromEntries(character.classResources.map(item=>[item.id,item.value]));assert.equal(character.abilityMaximums.str,24);assert.equal(character.abilityMaximums.con,24);assert.ok(character.abilities.str<=24);assert.ok(character.abilities.con<=24);assert.equal(resources["rage-uses"],"Unlimited");});
test("selected level above 5 with Random class resolves only to a verified high-level class",()=>{for(const ruleset of ["2014","2024"])for(const level of [6,10,15,20]){const state=createInitialState();state.ruleset=ruleset;state.constraints.level=String(level);const character=generateCharacter(state);assert.ok(["barbarian","rogue"].includes(character.class.id));assert.equal(character.class.maxLevel,20);assert.equal(character.level,level);}});
test("1000 randomized Barbarians per edition pass validation and references",()=>{for(const ruleset of ["2014","2024"])for(let i=0;i<1000;i++){const character=generateCharacter(barbarianState(ruleset));assert.equal(character.validation.valid,true);assert.doesNotThrow(()=>buildQuickReference(character));}});
test("invalid Barbarian editions and levels fail closed",()=>{assert.throws(()=>barbarianProgression("2024",0),/1 to 20/i);assert.throws(()=>barbarianProgression("2024",21),/1 to 20/i);assert.throws(()=>barbarianProgression("2099",1),/Unsupported Barbarian ruleset/i);});
