import test from "node:test";
import assert from "node:assert/strict";
import { createInitialState } from "../src/state.js";
import { generateCharacter } from "../src/rules/generator.js";
import { druidProgressionFor, legalFormsForProgression } from "../src/rules/druid.js";

function seeded(seed){let value=seed>>>0;return()=>{value=(value+0x6D2B79F5)>>>0;let t=value;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function base(ruleset,classId,level,subclass){const state=createInitialState();state.ruleset=ruleset;state.constraints.level=String(level);state.constraints.class=classId;state.constraints.subclass=subclass;state.constraints.species=ruleset==="2014"?"human":"human";state.constraints.background="random";return state;}

test("fixed Bard instruments, Lore skills, and Expertise survive Random background and skill fill across seeds",()=>{
  const original=Math.random;try{for(let seed=1;seed<=64;seed++){Math.random=seeded(seed);const state=base("2014","bard",20,"college-lore");state.classSelections={instruments:["Lute","Flute"],loreBonusSkills:["arcana","athletics","stealth"],expertise:["arcana","deception","performance","persuasion"]};const c=generateCharacter(state);assert.equal(c.validation.valid,true,`seed ${seed}`);for(const item of state.classSelections.instruments)assert.ok(c.bardSelections.instruments.includes(item),`seed ${seed} lost instrument ${item}`);assert.deepEqual(c.bardSelections.loreBonusSkills,state.classSelections.loreBonusSkills);for(const skill of state.classSelections.expertise)assert.ok(c.expertise.includes(skill),`seed ${seed} lost Expertise ${skill}`);for(const skill of state.classSelections.loreBonusSkills)assert.ok(!c.background.skills.includes(skill),`seed ${seed} background stole Lore skill ${skill}`);}}
  finally{Math.random=original;}
});

test("fixed Sorcerer Metamagic survives random remainder",()=>{const state=base("2024","sorcerer",20,"draconic-sorcery");state.constraints.background="acolyte";state.classSelections={metamagic:["quickened-spell","subtle-spell"],elementalAffinity:"Fire"};const c=generateCharacter(state);assert.equal(c.validation.valid,true);for(const id of state.classSelections.metamagic)assert.ok(c.sorcererSelections.metamagic.all.includes(id));assert.equal(c.sorcererSelections.draconic.elementalAffinity,"Fire");});

test("fixed Druid known forms and Circle choices survive random form fill",()=>{const p=druidProgressionFor("2024",20,"circle-land"),forms=legalFormsForProgression("2024",p).slice(0,3).map(item=>item.id),state=base("2024","druid",20,"circle-land");state.constraints.background="acolyte";state.classSelections={primalOrder:"magician",circleLand:"temperate",elementalFury:"potent-spellcasting",knownForms:forms};const c=generateCharacter(state);assert.equal(c.validation.valid,true);assert.equal(c.druidSelections.primalOrder,"magician");assert.equal(c.druidSelections.circleLand,"temperate");assert.equal(c.druidSelections.elementalFury,"potent-spellcasting");for(const id of forms)assert.ok(c.druidSelections.knownForms.includes(id));assert.equal(c.druidSelections.knownForms.length,p.knownFormCount);});

test("fixed 2014 Ranger exploration and Hunter choices survive random remainder",()=>{const state=base("2014","ranger",20,"hunter");state.constraints.background="acolyte";state.classSelections={favoredEnemies:["fiends","dragons"],favoredEnemyLanguages:["Infernal","Draconic"],naturalExplorerTerrains:["forest"],huntersPrey:"horde-breaker",defensiveTactics:"multiattack-defense",multiattack:"volley",superiorDefense:"evasion"};const c=generateCharacter(state);assert.equal(c.validation.valid,true);assert.deepEqual(c.rangerSelections.favoredEnemies.slice(0,2),["fiends","dragons"]);assert.deepEqual(c.rangerSelections.favoredEnemyLanguages.slice(0,2),["Infernal","Draconic"]);assert.equal(c.rangerSelections.naturalExplorerTerrains[0],"forest");assert.equal(c.rangerSelections.huntersPrey,"horde-breaker");assert.equal(c.rangerSelections.defensiveTactics,"multiattack-defense");assert.equal(c.rangerSelections.multiattack,"volley");assert.equal(c.rangerSelections.superiorDefense,"evasion");});
