import test from "node:test";
import assert from "node:assert/strict";
import { createInitialState } from "../src/state.js";
import { generateCharacter } from "../src/rules/generator.js";
import { rogueProgressionFor } from "../src/rules/rogue.js";
import { RAW_2014 } from "../src/data/raw-2014.js";
import { buildQuickReference } from "../src/rules/reference.js";
import { renderCharacter } from "../src/ui/render.js";
import { buildPremiumPrintModel } from "../src/print/model.js";
import { buildQuickTurn } from "../src/print/quick-turn.js";
import { validateCharacter } from "../src/rules/validation.js";

function rogueAt(level){const state=createInitialState();state.ruleset="2014";state.constraints.level=String(level);state.constraints.class="rogue";state.constraints.subclass=level>=3?"thief":"random";state.constraints.species="human";state.constraints.background="acolyte";return generateCharacter(state);}

test("2014 Thief Rogue generates and validates at every level 1 through 20",()=>{for(let level=1;level<=20;level++){const c=rogueAt(level);assert.equal(c.validation.valid,true);assert.equal(c.rogue.sneakAttackDice,Math.ceil(level/2));assert.equal(c.rogue.expertiseCount,level>=6?4:2);assert.equal(c.rogue.masteryCount,0);assert.equal(c.masteryIds.length,0);if(level>=3)assert.equal(c.subclass.id,"thief");else assert.equal(c.subclass,null);}});
test("2014 Rogue class table and progression are exact and isolated from 2024",()=>{const cls=RAW_2014.classes.find(item=>item.id==="rogue");assert.deepEqual(cls.asiLevels,[4,8,10,12,16,19]);assert.equal(cls.maxLevel,20);for(let level=1;level<=20;level++){const p=rogueProgressionFor(level,level>=3?"thief":null,"2014");assert.equal(p.masteryCount,0);assert.equal(p.maxCunningStrikeEffects,0);assert.deepEqual(p.cunningStrikeOptions,[]);assert.equal(p.reliableTalent,level>=11);assert.equal(p.blindsenseRange,level>=14?10:0);}});
test("2014 Rogue spends all six ASIs without exceeding 20",()=>{const before=rogueAt(3),after=rogueAt(19),sum=c=>Object.values(c.abilities).reduce((total,value)=>total+value,0);assert.equal(sum(after)-sum(before),12);assert.ok(Object.values(after.abilities).every(value=>value<=20));});
test("2014 Slippery Mind adds Wisdom proficiency only at level 15",()=>{assert.deepEqual([...rogueAt(14).saves].sort(),["dex","int"]);assert.deepEqual([...rogueAt(15).saves].sort(),["dex","int","wis"]);});
test("2014 Rogue and Thief feature breakpoints are exact",()=>{const f3=rogueAt(3).features,f9=rogueAt(9).features,f11=rogueAt(11).features,f13=rogueAt(13).features,f14=rogueAt(14).features,f15=rogueAt(15).features,f17=rogueAt(17).features,f18=rogueAt(18).features,f20=rogueAt(20).features;assert.ok(f3.includes("Fast Hands")&&f3.includes("Second-Story Work"));assert.ok(f9.includes("Supreme Sneak"));assert.ok(f11.includes("Reliable Talent"));assert.ok(f13.includes("Use Magic Device"));assert.ok(f14.includes("Blindsense"));assert.ok(f15.includes("Slippery Mind"));assert.ok(f17.includes("Thief’s Reflexes"));assert.ok(f18.includes("Elusive"));assert.ok(f20.includes("Stroke of Luck"));});
test("2014 Rogue and Thief play references carry exact SRD 5.1 pages",()=>{const refs=buildQuickReference(rogueAt(20)),byName=new Map(refs.map(item=>[item.name,item]));for(const name of ["Expertise","Sneak Attack"])assert.equal(byName.get(name).source.page,"39");for(const name of ["Cunning Action","Uncanny Dodge","Evasion","Reliable Talent","Blindsense","Slippery Mind","Elusive","Stroke of Luck"])assert.equal(byName.get(name).source.page,"40");for(const name of ["Fast Hands","Second-Story Work","Supreme Sneak","Use Magic Device","Thief’s Reflexes"])assert.match(byName.get(name).source.page,/40|41/);});
test("2014 Rogue Quick Turn never calls Cunning Strike or Steady Aim",()=>{const five=buildQuickTurn(rogueAt(5)).join(" "),seventeen=buildQuickTurn(rogueAt(17)).join(" ");assert.match(five,/Cunning Action/);assert.doesNotMatch(five,/Cunning Strike|Steady Aim/);assert.match(seventeen,/Initiative minus 10/);assert.doesNotMatch(seventeen,/Cunning Strike|Steady Aim/);});
test("2014 level-20 browser sheet shows legacy resources without functional 2024 leakage",()=>{const c=rogueAt(20),target={innerHTML:""};renderCharacter(c,target);assert.match(target.innerHTML,/Rogue Resources/);assert.match(target.innerHTML,/10d6/);assert.match(target.innerHTML,/Reliable Talent/);assert.match(target.innerHTML,/Blindsense/);assert.match(target.innerHTML,/10 ft/);assert.match(target.innerHTML,/Thief’s Reflexes/);assert.match(target.innerHTML,/Wisdom Save/);assert.match(target.innerHTML,/no Weapon Mastery, Steady Aim, or Cunning Strike mechanics/);assert.doesNotMatch(target.innerHTML,/Cunning Strike DC/);assert.match(target.innerHTML,/Rules Audit/);});
test("2014 premium Rogue model exposes legacy resources only",()=>{const model=buildPremiumPrintModel(rogueAt(20)),r=model.rogueResources;assert.equal(r.ruleset,"2014");assert.equal(r.sneakAttack,"10d6");assert.match(String(r.expertise),/^(4 skills|3 skills \+ Thieves’ Tools)$/);assert.equal(r.masteries,0);assert.equal(r.cunningStrikeDc,null);assert.equal(r.effectsPerSneak,0);assert.equal(r.reliableTalent,true);assert.equal(r.blindsense,"10 ft");assert.equal(r.thiefReflexes,true);assert.deepEqual(r.options,[]);assert.equal(r.scrollWarning,null);assert.ok(model.ruleIndex.some(item=>item.name==="Blindsense"));assert.equal(model.packet.totalPages,1);});
test("2014 Rogue audit identity is sourced to class page 39 and Thief page 40",()=>{const audit=rogueAt(20).audit,mechanics=new Map(audit.mechanics.map(item=>[item.label,item]));assert.equal(mechanics.get("Class").source.page,"39");assert.equal(mechanics.get("Subclass").source.page,"40");assert.equal(audit.status,"PASS");assert.equal(audit.rawIntegrity,true);});
test("2014 Rogue validation rejects injected 2024 mechanics",()=>{const c=rogueAt(20),tampered=structuredClone(c);tampered.rogue.masteryCount=2;tampered.rogue.maxCunningStrikeEffects=2;tampered.rogue.cunningStrikeOptions=["trip"];tampered.masteryIds=["rapier","shortbow"];tampered.features.push("Cunning Strike");const result=validateCharacter(tampered,tampered.sourceMode);assert.equal(result.valid,false);assert.match(result.errors.join(" "),/Weapon Mastery|Cunning Strike/);});
test("Random 2014 Rogue can legally reach level 20",()=>{const original=Math.random;try{Math.random=()=>0.999999;const state=createInitialState();state.ruleset="2014";state.constraints.class="rogue";state.constraints.level="random";state.constraints.subclass="random";const c=generateCharacter(state);assert.equal(c.level,20);assert.equal(c.validation.valid,true);}finally{Math.random=original;}});
