import test from "node:test";
import assert from "node:assert/strict";
import { createInitialState } from "../src/state.js";
import { CLERIC_SPELLS_2024 } from "../src/data/cleric-spells.js";
import { SPELL_REFERENCE_2024_LEVEL1_CLERIC } from "../src/data/spell-reference-2024-level1-cleric.js";
import { generateCharacter } from "../src/rules/generator.js";
import { characterActiveSpellReferences } from "../src/rules/spell-reference.js";

const ids=values=>values.map(value=>value.id).sort(),expected=CLERIC_SPELLS_2024.filter(spell=>spell.level===1).map(spell=>spell.id).sort(),byId=id=>SPELL_REFERENCE_2024_LEVEL1_CLERIC.find(spell=>spell.id===id);
function cleric(level){const state=createInitialState();state.ruleset="2024";state.constraints.class="cleric";state.constraints.level=String(level);return generateCharacter(state);}
test("all 15 SRD 5.2.1 Cleric level-1 spells have exactly one reference",()=>{try{assert.equal(SPELL_REFERENCE_2024_LEVEL1_CLERIC.length,15);assert.deepEqual(ids(SPELL_REFERENCE_2024_LEVEL1_CLERIC),expected);assert.equal(new Set(ids(SPELL_REFERENCE_2024_LEVEL1_CLERIC)).size,15);}catch(error){console.error("[test] Cleric level1 coverage",error);throw error;}});
test("level-1 reference action economy and ritual flags match the verified SRD set",()=>{try{const bonus=SPELL_REFERENCE_2024_LEVEL1_CLERIC.filter(spell=>spell.castingTime==="Bonus Action").map(spell=>spell.id).sort(),ritual=SPELL_REFERENCE_2024_LEVEL1_CLERIC.filter(spell=>spell.ritual).map(spell=>spell.id).sort();assert.deepEqual(bonus,["healing-word","sanctuary","shield-of-faith"]);assert.deepEqual(ritual,["detect-magic","detect-poison-and-disease","purify-food-and-drink"]);}catch(error){console.error("[test] level1 timing flags",error);throw error;}});
test("level-1 concentration set is exact",()=>{try{const values=SPELL_REFERENCE_2024_LEVEL1_CLERIC.filter(spell=>spell.concentration).map(spell=>spell.id).sort();assert.deepEqual(values,["bane","bless","detect-evil-and-good","detect-magic","detect-poison-and-disease","protection-from-evil-and-good","shield-of-faith"]);}catch(error){console.error("[test] level1 concentration",error);throw error;}});
test("only the eight verified level-1 Cleric spells expose explicit upcast rules",()=>{try{const values=SPELL_REFERENCE_2024_LEVEL1_CLERIC.filter(spell=>spell.upcast).map(spell=>spell.id).sort();assert.deepEqual(values,["bane","bless","command","create-or-destroy-water","cure-wounds","guiding-bolt","healing-word","inflict-wounds"]);}catch(error){console.error("[test] level1 upcast set",error);throw error;}});
test("2024 Command upcast adds targets without the legacy 30-foot grouping restriction",()=>{try{assert.equal(byId("command").upcast,"Target one additional creature for each slot level above 1.");assert.equal(/within 30/i.test(byId("command").upcast),false);}catch(error){console.error("[test] 2024 Command upcast",error);throw error;}});
test("all level-1 records carry complete structured metadata and SRD page provenance",()=>{try{for(const spell of SPELL_REFERENCE_2024_LEVEL1_CLERIC){assert.equal(spell.level,1);assert.equal(spell.source,"SRD 5.2.1");assert.ok(Number.isInteger(spell.srdPage)&&spell.srdPage>=112&&spell.srdPage<=162);for(const key of ["name","school","castingTime","range","components","duration","resolution","effect"])assert.ok(spell[key],`${spell.id} missing ${key}`);assert.ok(spell.effect.length>=35);}}catch(error){console.error("[test] level1 metadata",error);throw error;}});
test("every active 2024 Cleric level-1 spell resolves to a playable reference",()=>{try{const level1=new Set(expected);for(let level=1;level<=5;level++)for(let i=0;i<100;i++){const c=cleric(level),refs=characterActiveSpellReferences(c),refIds=new Set(refs.map(ref=>ref.id)),active=[...(c.spells.prepared?.all||[]),...(c.spells.alwaysPrepared||[])].filter(id=>level1.has(id));for(const id of active)assert.ok(refIds.has(id),`${id} missing at Cleric ${level}`);}}catch(error){console.error("[test] active level1 references",error);throw error;}});
test("level-1 Cleric references include the complete class subset plus only explained granted magic",()=>{try{const c=cleric(1),refs=characterActiveSpellReferences(c),lookup=new Map(refs.map(ref=>[ref.id,ref])),classIds=new Set([...c.spells.cantrips.all,...c.spells.prepared.all]);for(const id of c.spells.cantrips.all){assert.ok(lookup.has(id),`${id} class cantrip missing`);assert.equal(lookup.get(id).preparation,"Cantrip");}for(const id of c.spells.prepared.all){assert.ok(lookup.has(id),`${id} prepared spell missing`);assert.equal(lookup.get(id).preparation,"Prepared");}for(const ref of refs.filter(ref=>!classIds.has(ref.id))){assert.ok(ref.grantSource,`${ref.id} extra active magic lacks a grant source`);assert.notEqual(ref.grantSource,"class",`${ref.id} unexplained class spell leaked into level-1 Cleric references`);assert.ok(["Species Cantrip","Species Magic","Magic Initiate Cantrip","Magic Initiate · Always Prepared"].includes(ref.preparation),`${ref.id} has unexplained preparation label ${ref.preparation}`);}}catch(error){console.error("[test] level1 active subset",error);throw error;}});
test("Life Domain Bless and Cure Wounds are marked Always Prepared from Cleric level 3 onward",()=>{try{for(const level of [3,4,5]){const refs=characterActiveSpellReferences(cleric(level));for(const id of ["bless","cure-wounds"]){const ref=refs.find(item=>item.id===id);assert.ok(ref);assert.equal(ref.preparation,"Always Prepared");}}}catch(error){console.error("[test] Life Domain level1 refs",error);throw error;}});
