import { SKILLS } from "../schema.js";
import { validateClericClassSelections } from "../rules/cleric.js";
import { bardProgressionFor } from "../rules/bard.js";
import { LAND_2014, LAND_2024, PRIMAL_ORDERS_2024, ELEMENTAL_FURY_2024, druidProgressionFor, legalFormsForProgression } from "../rules/druid.js";
import { DRACONIC_AFFINITIES_2024, DRACONIC_ANCESTRIES_2014 } from "../data/sorcerer-class.js";
import { metamagicOptionsFor } from "../data/sorcerer-metamagic.js";
import { sorcererProgressionFor } from "../rules/sorcerer.js";
import { PACT_BOONS_2014 } from "../data/warlock-class.js";
import { invocationCantripTargetIds, invocationOptionsAtLevel, warlockInvocationById } from "../data/warlock-invocations.js";
import { warlockSpellById } from "../data/warlock-spells.js";
import { warlockProgressionFor } from "../rules/warlock.js";
import { FAVORED_ENEMY_TYPES_2014, FAVORED_ENEMY_LANGUAGE_OPTIONS_2014, NATURAL_EXPLORER_TERRAINS_2014, HUNTER_PREY_2014, HUNTER_DEFENSE_2014, HUNTER_MULTIATTACK_2014, HUNTER_SUPERIOR_DEFENSE_2014, HUNTER_PREY_2024, HUNTER_DEFENSE_2024, rangerProgressionFor } from "../rules/ranger.js";
import { RANGER_LANGUAGE_OPTIONS_2024 } from "../rules/ranger-explorer-selections.js";
import { fighterProgressionFor } from "../rules/fighter.js";
import { rogueProgressionFor } from "../rules/rogue.js";
import { sanitizeWeaponMasterySelections, weaponMasteryCountFor, weaponMasteryPoolFor } from "../rules/weapon-mastery-selections.js";
import { guaranteedSpeciesSkillIds } from "../rules/species-skill-proficiencies.js";
import { SCHOLAR_SKILLS } from "../rules/wizard-selections.js";
import { forgeDataFor } from "../data/forge-data.js";
import { advancementChoicesForState } from "../rules/advancement-feats.js";
import { ADVANCEMENT_ASI_ID } from "../data/feat-library.js";
import { sanitizeActiveClassChoiceFields } from "./class-choice-sanitizer.js";
import { spellPickerConfigForState } from "./spell-picker-config.js";

const DIVINE_ORDERS=[{id:"protector",name:"Protector"},{id:"thaumaturge",name:"Thaumaturge"}];
const BLESSED_STRIKES=[{id:"divine-strike",name:"Divine Strike"},{id:"potent-spellcasting",name:"Potent Spellcasting"}];
const CLASS_SELECTION_KEYS=Object.freeze(["classSkills","equipmentPackage","weaponMasteries","primalKnowledgeSkill","divineOrder","blessedStrikes","instruments","loreBonusSkills","expertise","scholarExpertise","primalOrder","circleLand","elementalFury","fieldForms","knownForms","fightingStyle","additionalFightingStyle","deftExplorerLanguages","favoredEnemies","favoredEnemyLanguages","naturalExplorerTerrains","huntersPrey","defensiveTactics","multiattack","superiorDefense","monkTool","metamagic","draconicAncestry","elementalAffinity","pactBoon","eldritchInvocations","warlockInvocationTargets","advancements"]);
const pretty=value=>String(value||"").replace(/([a-z])([A-Z])/g,"$1 $2").replace(/-/g," ").replace(/\b\w/g,char=>char.toUpperCase());
const asOptions=values=>values.map(value=>typeof value==="string"?{id:value,name:pretty(value)}:{id:value.id,name:value.displayName||value.name||pretty(value.id)});
const mapOptions=map=>Object.entries(map).map(([id,name])=>({id,name}));

export function bindClassOptions(state,{onChange=()=>{},showToast=()=>{}}={}){
  try{
    const panel=document.getElementById("classChoicePanel");if(!panel)throw new Error("Class options panel is missing.");
    panel.addEventListener("change",event=>{
      const single=event.target.closest("[data-class-choice]"),multi=event.target.closest("[data-class-multi]"),indexed=event.target.closest("[data-class-index-choice]");if(!single&&!multi&&!indexed)return;
      const previous=structuredClone(state.classSelections||{}),proposed=structuredClone(previous);
      try{
        if(single){const key=single.dataset.classChoice;if(single.value==="random")delete proposed[key];else proposed[key]=single.value;}
        if(multi){const key=multi.dataset.classMulti,value=multi.value,current=[...(proposed[key]||[])];proposed[key]=multi.checked?[...new Set([...current,value])]:current.filter(item=>item!==value);if(!proposed[key].length)delete proposed[key];}
        if(indexed){const key=indexed.dataset.classIndexChoice,index=Number(indexed.dataset.index),current=[...(proposed[key]||[])];while(current.length<=index)current.push(null);current[index]=indexed.value==="random"?null:indexed.value;while(current.length&&current.at(-1)==null)current.pop();if(current.length)proposed[key]=current;else delete proposed[key];if(key==="eldritchInvocations"){const targets=[...(proposed.warlockInvocationTargets||[])];while(targets.length<=index)targets.push(null);targets[index]=null;while(targets.length&&targets.at(-1)==null)targets.pop();if(targets.length)proposed.warlockInvocationTargets=targets;else delete proposed.warlockInvocationTargets;}}
        state.classSelections=proposed;validateClassChoiceState(state);validateCurrentSpellChoices(state);renderClassOptions(state);onChange();
      }catch(error){state.classSelections=previous;console.error("[class-ui] change blocked",error);renderClassOptions(state);showToast(error.message,true);}
    });
    renderClassOptions(state);
  }catch(error){console.error("[class-ui] bind failed",error);throw error;}
}
export function resetClassOptions(state){try{state.classSelections={};renderClassOptions(state);}catch(error){console.error("[class-ui] reset failed",error);throw error;}}
export function renderClassOptions(state){try{const panel=document.getElementById("classChoicePanel"),fieldsNode=document.getElementById("classChoiceFields"),summary=document.getElementById("classChoiceSummary");if(!panel||!fieldsNode||!summary)throw new Error("Class option UI is incomplete.");const fields=classChoiceFieldsForState(state);panel.hidden=fields.length===0;fieldsNode.innerHTML=fields.map(field=>fieldHtml(field,state.classSelections||{})).join("");summary.textContent=fields.length?summaryText(fields,state.classSelections||{}):"";}catch(error){console.error("[class-ui] render failed",error);throw error;}}
export function sanitizeWeaponMasterySelectionsForState(state){
  try{
    state.classSelections=state.classSelections||{};
    const data=forgeDataFor(state.ruleset),cls=data.classes.find(item=>item.id===state.constraints.class);
    if(!cls){delete state.classSelections.weaponMasteries;return[];}
    const fixed=sanitizeWeaponMasterySelections({ruleset:state.ruleset,level:resolvedLevel(state),subclassId:resolvedSubclassId(state),cls,data,selections:state.classSelections});
    if(fixed.length)state.classSelections.weaponMasteries=fixed;else delete state.classSelections.weaponMasteries;
    return fixed;
  }catch(error){console.error("[class-ui] Weapon Mastery state sanitization failed",error);throw error;}
}
export function sanitizeClassSelectionsForCurrentState(state){
  try{
    state.classSelections=state.classSelections||{};
    let fields=classChoiceFieldsForState(state),active=new Set(fields.map(field=>field.key));
    for(const key of CLASS_SELECTION_KEYS)if(key!=="favoredEnemyLanguages"&&!active.has(key))delete state.classSelections[key];
    sanitizeWeaponMasterySelectionsForState(state);
    fields=classChoiceFieldsForState(state);
    state.classSelections=sanitizeActiveClassChoiceFields(state.classSelections,fields);
    fields=classChoiceFieldsForState(state);
    state.classSelections=sanitizeActiveClassChoiceFields(state.classSelections,fields);
    if(state.constraints.class!=="ranger"||state.ruleset!=="2014"||!(state.classSelections.favoredEnemies||[]).length)delete state.classSelections.favoredEnemyLanguages;else if(Array.isArray(state.classSelections.favoredEnemyLanguages))state.classSelections.favoredEnemyLanguages=state.classSelections.favoredEnemyLanguages.slice(0,state.classSelections.favoredEnemies.length);
    return state.classSelections;
  }catch(error){console.error("[class-ui] class selection sanitization failed",error);throw error;}
}
export function clearIllegalClassSelectionsForLevel(state){
  try{
    sanitizeClassSelectionsForCurrentState(state);validateClassChoiceState(state);renderClassOptions(state);
  }catch(error){console.error("[class-ui] level cleanup failed",error);state.classSelections={};renderClassOptions(state);}
}
export function classChoiceFieldsForState(state){
  try{
    const classId=state.constraints.class,level=resolvedLevel(state),subclassId=resolvedSubclassId(state),data=forgeDataFor(state.ruleset),cls=data.classes.find(item=>item.id===classId);if(!cls)return[];let fields=[];
    if(classId==="barbarian"){if(state.ruleset==="2024"&&level>=3)fields.push(single("primalKnowledgeSkill","Primal Knowledge Skill",primalKnowledgeOptionsForState(state,cls,data)));return withAdvancements(fields,state,cls,level);}
    if(classId==="cleric"&&state.ruleset==="2024"){fields=[single("divineOrder","Divine Order",DIVINE_ORDERS)];if(level>=7)fields.push(single("blessedStrikes","Blessed Strikes",BLESSED_STRIKES));return withAdvancements(fields,state,cls,level);}
    if(classId==="bard"){const p=bardProgressionFor(state.ruleset,level,subclassId);fields=[multi("instruments","Instrument Proficiencies",asOptions(cls.instrumentChoices||[]),cls.instrumentCount||0)];if(p.loreBonusSkills)fields.push(multi("loreBonusSkills","College of Lore Bonus Skills",bardLoreSkillOptionsForState(state,cls,data),p.loreBonusSkills));if(p.expertiseCount)fields.push(multi("expertise","Expertise",asOptions(cls.skillChoices||[]),p.expertiseCount));return withAdvancements(fields,state,cls,level);}
    if(classId==="druid"){const p=druidProgressionFor(state.ruleset,level,subclassId);if(state.ruleset==="2024")fields.push(single("primalOrder","Primal Order",asOptions(PRIMAL_ORDERS_2024)));const threshold=state.ruleset==="2014"?2:3;if(subclassId==="circle-land"&&level>=threshold)fields.push(single("circleLand","Circle Land",asOptions(state.ruleset==="2014"?LAND_2014:LAND_2024)));if(state.ruleset==="2024"&&level>=7)fields.push(single("elementalFury","Elemental Fury",asOptions(ELEMENTAL_FURY_2024)));const forms=asOptions(legalFormsForProgression(state.ruleset,p));if(state.ruleset==="2014"&&level>=2)fields.push(multi("fieldForms","Wild Shape Field Forms",forms,Math.min(4,forms.length)));if(state.ruleset==="2024"&&p.knownFormCount)fields.push(multi("knownForms","Known Wild Shape Forms",forms,p.knownFormCount));return withAdvancements(fields,state,cls,level);}
    if(classId==="fighter"){const p=fighterProgressionFor(state.ruleset,level,subclassId),styleOptions=(cls.styleChoices||[]).map(id=>({id,name:data.fightingStyles[id]?.name||pretty(id)}));fields=[single("fightingStyle","Fighting Style",styleOptions)];if(p.additionalFightingStyle)fields.push(single("additionalFightingStyle","Additional Fighting Style",styleOptions.filter(option=>option.id!==state.classSelections?.fightingStyle)));return withAdvancements(fields,state,cls,level);}
    if(classId==="rogue"){const p=rogueProgressionFor(level,subclassId,state.ruleset);fields=[multi("expertise","Expertise",rogueExpertiseOptionsForState(state,cls,data),p.expertiseCount)];return withAdvancements(fields,state,cls,level);}
    if(classId==="wizard"&&state.ruleset==="2024"&&level>=2){fields=[single("scholarExpertise","Scholar Expertise",wizardScholarOptionsForState(state,cls,data))];return withAdvancements(fields,state,cls,level);}
    if(classId==="paladin"&&level>=2)fields=[single("fightingStyle","Fighting Style",(cls.styleChoices||[]).map(id=>({id,name:data.fightingStyles[id]?.name||pretty(id)})))];
    else if(classId==="ranger")fields=rangerFields(state,cls,data,level,subclassId);
    else if(classId==="monk"&&(cls.toolChoices||[]).length)fields=[single("monkTool","Monk Tool",asOptions(cls.toolChoices))];
    else if(classId==="sorcerer"){const p=sorcererProgressionFor(state.ruleset,level,subclassId);if(p.metamagicCount)fields.push(multi("metamagic","Metamagic",asOptions(metamagicOptionsFor(state.ruleset)),p.metamagicCount));if(state.ruleset==="2014"&&subclassId==="draconic-bloodline")fields.push(single("draconicAncestry","Dragon Ancestor",asOptions(DRACONIC_ANCESTRIES_2014)));if(state.ruleset==="2024"&&subclassId==="draconic-sorcery"&&level>=6)fields.push(single("elementalAffinity","Elemental Affinity",asOptions(DRACONIC_AFFINITIES_2024)));}
    else if(classId==="warlock"){
      const p=warlockProgressionFor(state.ruleset,level,subclassId);if(state.ruleset==="2014"&&p.pactBoon)fields.push(single("pactBoon","Pact Boon",asOptions(PACT_BOONS_2014)));
      if(p.invocations){
        const pact=state.classSelections?.pactBoon||null,selected=state.classSelections?.eldritchInvocations||[];
        if(state.ruleset==="2024"){
          const targets=state.classSelections?.warlockInvocationTargets||[];
          for(let index=0;index<p.invocations;index++){
            const current=selected[index]||null,currentTarget=targets[index]||null,options=invocationOptionsAtLevel(state.ruleset,level,{pactBoon:pact,selectedIds:selected.filter(Boolean)}).filter(option=>{
              if(option.id===current)return true;
              const copies=selected.filter((id,otherIndex)=>otherIndex!==index&&id===option.id).length;
              if(!option.repeatable)return copies===0;
              const pool=invocationCantripTargetIds(state.ruleset,option.id);if(!pool.length)return true;
              return copies<Math.min(pool.length,p.cantrips||pool.length);
            });
            fields.push(indexed("eldritchInvocations",`Eldritch Invocation — Slot ${index+1}`,asOptions(options),index));
            if(current){
              const targetPool=invocationCantripTargetIds(state.ruleset,current);
              if(targetPool.length){const used=new Set(selected.map((id,otherIndex)=>id===current&&otherIndex!==index?targets[otherIndex]:null).filter(Boolean)),targetOptions=targetPool.filter(id=>id===currentTarget||!used.has(id)).map(id=>({id,name:warlockSpellById(state.ruleset,id).name}));fields.push(indexed("warlockInvocationTargets",`${warlockInvocationById(state.ruleset,current).name} — Cantrip`,targetOptions,index));}
            }
          }
        }else{const options=invocationOptionsAtLevel(state.ruleset,level,{pactBoon:pact,selectedIds:selected});fields.push(multi("eldritchInvocations","Eldritch Invocations",asOptions(options),p.invocations));}
      }
    }
    return withAdvancements(fields,state,cls,level);
  }catch(error){console.error("[class-ui] field definition failed",error);throw error;}
}
function withAdvancements(fields,state,cls,level){try{const equipment=state.ruleset==="2024"&&(cls.equipmentPackages||[]).length>1?[single("equipmentPackage","Starting Equipment",startingEquipmentOptions(cls),"Automatic ready-to-play package")]:[],next=cls.skillCount?[...equipment,multi("classSkills",`${cls.name} Skill Proficiencies`,classSkillOptionsForState(state,cls),cls.skillCount),...fields]:[...equipment,...fields],data=forgeDataFor(state.ruleset),masteryCount=weaponMasteryCountFor(state.ruleset,cls.id,level,resolvedSubclassId(state));if(masteryCount)next.push(multi("weaponMasteries","Weapon Masteries",weaponMasteryOptionsForState(cls,data),masteryCount));const slots=advancementChoicesForState(state.ruleset,cls,level);for(const [index,slot] of slots.entries())next.push(indexed("advancements",`Advancement — Level ${slot.level}`,asOptions(slot.options),index,"Automatic ASI"));return next;}catch(error){console.error("[class-ui] advancement fields failed",error);throw error;}}
function startingEquipmentOptions(cls){try{return(cls.equipmentPackages||[]).map(pkg=>{const gold=(pkg.gear||[]).find(item=>/^\d+ GP$/.test(item)),detail=pkg.startingGoldOnly?gold||"Starting Gold":pretty(pkg.id);return{id:pkg.id,name:`Package ${pkg.srdOption||"?"} — ${detail}`};});}catch(error){console.error("[class-ui] starting equipment options failed",error);throw error;}}
function weaponMasteryOptionsForState(cls,data){try{return weaponMasteryPoolFor(cls,data).map(id=>{const weapon=data.weapons[id];return{id,name:`${weapon?.name||pretty(id)} — ${weapon?.mastery||"Mastery"}`};});}catch(error){console.error("[class-ui] Weapon Mastery options failed",error);throw error;}}
function speciesSkillsForState(state){try{return[...guaranteedSpeciesSkillIds({ruleset:state.ruleset,speciesId:state.constraints.species,selections:state.speciesSelections||{}})];}catch(error){console.error("[class-ui] species skill provenance failed",error);throw error;}}
function classSkillOptionsForState(state,cls){try{const data=forgeDataFor(state.ruleset),background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,blocked=new Set([...(background?.skills||[]),...speciesSkillsForState(state),...(state.constraints.class==="bard"?(state.classSelections?.loreBonusSkills||[]):[]),...(state.constraints.class==="barbarian"&&state.ruleset==="2024"&&resolvedLevel(state)>=3&&state.classSelections?.primalKnowledgeSkill?[state.classSelections.primalKnowledgeSkill]:[])]);return asOptions((cls.skillChoices||[]).filter(skill=>!blocked.has(skill)));}catch(error){console.error("[class-ui] class skill options failed",error);throw error;}}
function bardLoreSkillOptionsForState(state,cls,data){try{const background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,blocked=new Set([...(background?.skills||[]),...speciesSkillsForState(state),...(state.classSelections?.classSkills||[])]);return asOptions((cls.skillChoices||[]).filter(skill=>!blocked.has(skill)));}catch(error){console.error("[class-ui] Bard Lore skill options failed",error);throw error;}}
function primalKnowledgeOptionsForState(state,cls,data){try{const background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,backgroundSkills=background?.skills||[],speciesSkills=speciesSkillsForState(state),classSkills=state.classSelections?.classSkills||[],blocked=new Set([...backgroundSkills,...speciesSkills,...classSkills]);return asOptions((cls.skillChoices||[]).filter(skill=>!blocked.has(skill)));}catch(error){console.error("[class-ui] Primal Knowledge options failed",error);throw error;}}
function rogueExpertiseOptionsForState(state,cls,data){try{const background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,backgroundSkills=background?.skills||[],speciesSkills=speciesSkillsForState(state),values=[...new Set([...(cls.skillChoices||[]),...backgroundSkills,...speciesSkills,...(state.ruleset==="2014"?["Thieves' Tools"]:[])])];return asOptions(values);}catch(error){console.error("[class-ui] Rogue Expertise options failed",error);throw error;}}
function wizardScholarOptionsForState(state,cls,data){try{const background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,backgroundSkills=background?.skills||[],speciesSkills=speciesSkillsForState(state),values=[...new Set([...(cls.skillChoices||[]),...backgroundSkills,...speciesSkills])].filter(value=>SCHOLAR_SKILLS.includes(value));return asOptions(values);}catch(error){console.error("[class-ui] Wizard Scholar options failed",error);throw error;}}
function rangerExpertiseOptionsForState(state,cls,data){try{const background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,backgroundSkills=background?.skills||[],speciesSkills=speciesSkillsForState(state),values=[...new Set([...(cls.skillChoices||[]),...backgroundSkills,...speciesSkills])];return asOptions(values);}catch(error){console.error("[class-ui] Ranger Expertise options failed",error);throw error;}}
function rangerFields(state,cls,data,level,subclassId){const p=rangerProgressionFor(state.ruleset,level,subclassId),fields=[];if(level>=2)fields.push(single("fightingStyle","Fighting Style",(cls.styleChoices||[]).map(id=>({id,name:data.fightingStyles[id]?.name||pretty(id)}))));if(state.ruleset==="2024"&&level>=2){fields.push(multi("expertise","Expertise",rangerExpertiseOptionsForState(state,cls,data),p.expertiseCount));fields.push(multi("deftExplorerLanguages","Deft Explorer Languages",asOptions(RANGER_LANGUAGE_OPTIONS_2024),p.extraLanguages));}if(state.ruleset==="2014"){fields.push(multi("favoredEnemies","Favored Enemies",asOptions(FAVORED_ENEMY_TYPES_2014),p.favoredEnemyCount));fields.push(multi("naturalExplorerTerrains","Natural Explorer Terrains",asOptions(NATURAL_EXPLORER_TERRAINS_2014),p.naturalExplorerTerrainCount));for(const [index,enemy] of (state.classSelections?.favoredEnemies||[]).entries()){const languages=FAVORED_ENEMY_LANGUAGE_OPTIONS_2014[enemy]||[];if(languages.length>1)fields.push(indexed("favoredEnemyLanguages",`Favored Enemy Language — ${pretty(enemy)}`,asOptions(languages),index));}if(p.hunter){fields.push(single("huntersPrey","Hunter's Prey",mapOptions(HUNTER_PREY_2014)));if(level>=7)fields.push(single("defensiveTactics","Defensive Tactics",mapOptions(HUNTER_DEFENSE_2014)));if(level>=11)fields.push(single("multiattack","Multiattack",mapOptions(HUNTER_MULTIATTACK_2014)));if(level>=15)fields.push(single("superiorDefense","Superior Hunter's Defense",mapOptions(HUNTER_SUPERIOR_DEFENSE_2014)));}}else if(p.hunter){fields.push(single("huntersPrey","Hunter's Prey",mapOptions(HUNTER_PREY_2024)));if(level>=7)fields.push(single("defensiveTactics","Defensive Tactics",mapOptions(HUNTER_DEFENSE_2024)));}return fields;}
function validateClassChoiceState(state){try{const fields=classChoiceFieldsForState(state),seenMulti=new Set();for(const field of fields){const legal=new Set(field.options.map(option=>option.id));if(field.type==="single"){const value=state.classSelections?.[field.key];if(value&&!legal.has(value))throw new Error(`${field.label} choice "${value}" is unavailable.`);}else if(field.type==="multi"&&!seenMulti.has(field.key)){seenMulti.add(field.key);const values=state.classSelections?.[field.key]||[];if(!Array.isArray(values))throw new Error(`${field.label} choices must be a list.`);if(new Set(values).size!==values.length)throw new Error(`Duplicate ${field.label} choice.`);if(values.length>field.max)throw new Error(`Choose at most ${field.max} ${field.label}.`);const bad=values.filter(value=>!legal.has(value));if(bad.length)throw new Error(`Illegal ${field.label}: ${bad.join(", ")}.`);}else if(field.type==="indexed"){const value=(state.classSelections?.[field.key]||[])[field.index];if(value&&!legal.has(value))throw new Error(`${field.label} choice "${value}" is unavailable.`);}}const advancementValues=(state.classSelections?.advancements||[]).filter(value=>value&&value!==ADVANCEMENT_ASI_ID);if(new Set(advancementValues).size!==advancementValues.length)throw new Error("The same nonrepeatable advancement feat cannot be selected twice.");if(state.constraints.class==="fighter"&&state.classSelections?.fightingStyle&&state.classSelections?.additionalFightingStyle&&state.classSelections.fightingStyle===state.classSelections.additionalFightingStyle)throw new Error("Primary and additional Fighter Fighting Styles must be different.");validateBardChoiceDependencies(state);validateWarlockChoiceDependencies(state);if(state.constraints.class==="cleric")validateClericClassSelections({ruleset:state.ruleset,level:resolvedLevel(state),selections:state.classSelections||{},spellSelections:state.spellSelections||{}});}catch(error){console.error("[class-ui] class choice validation failed",error);throw error;}}
function validateBardChoiceDependencies(state){if(state.constraints.class!=="bard")return;const level=resolvedLevel(state),subclassId=resolvedSubclassId(state),p=bardProgressionFor(state.ruleset,level,subclassId),selections=state.classSelections||{},lore=selections.loreBonusSkills||[],expertise=selections.expertise||[],classSkills=selections.classSkills||[],data=forgeDataFor(state.ruleset),background=state.constraints.background&&state.constraints.background!=="random"?data.backgrounds.find(item=>item.id===state.constraints.background):null,backgroundSkills=background?.skills||[],speciesSkills=speciesSkillsForState(state),duplicateLore=lore.filter(skill=>backgroundSkills.includes(skill)||speciesSkills.includes(skill)||classSkills.includes(skill));if(duplicateLore.length)throw new Error(`College of Lore bonus skills must add new proficiencies: ${duplicateLore.join(", ")}.`);if(state.ruleset==="2024"&&level<9&&expertise.some(skill=>lore.includes(skill)))throw new Error("Before Bard level 9, Expertise cannot rely on a College of Lore proficiency gained later than the early Expertise choices.");const baseNeeded=expertise.filter(skill=>!backgroundSkills.includes(skill)&&!speciesSkills.includes(skill)&&!lore.includes(skill));if(baseNeeded.length>(data.classes.find(item=>item.id==="bard")?.skillCount||3))throw new Error("Those fixed Expertise choices require more base Bard skill proficiencies than Bard can choose.");if(lore.length>p.loreBonusSkills||expertise.length>p.expertiseCount)throw new Error("A fixed Bard skill choice is unavailable at this level.");}
function validateWarlockChoiceDependencies(state){try{if(state.constraints.class!=="warlock")return;const raw=state.classSelections?.eldritchInvocations||[],values=raw.filter(Boolean),targets=state.classSelections?.warlockInvocationTargets||[],p=warlockProgressionFor(state.ruleset,resolvedLevel(state),resolvedSubclassId(state));if(values.length>p.invocations)throw new Error(`Choose at most ${p.invocations} Eldritch Invocations.`);const counts=new Map();for(const id of values)counts.set(id,(counts.get(id)||0)+1);for(const [id,count] of counts){const option=warlockInvocationById(state.ruleset,id);if(count>1&&!option.repeatable)throw new Error(`${option.name} is not a repeatable Eldritch Invocation.`);const pool=invocationCantripTargetIds(state.ruleset,id);if(pool.length&&count>Math.min(pool.length,p.cantrips||pool.length))throw new Error(`${option.name} has only ${Math.min(pool.length,p.cantrips||pool.length)} different eligible known-cantrip target${Math.min(pool.length,p.cantrips||pool.length)===1?"":"s"} at this level.`);}const used=new Map();for(const [index,id] of raw.entries()){const target=targets[index]||null;if(!id){if(target)throw new Error(`Warlock invocation target in slot ${index+1} has no invocation.`);continue;}const pool=invocationCantripTargetIds(state.ruleset,id);if(!pool.length){if(target)throw new Error(`${warlockInvocationById(state.ruleset,id).name} does not take a cantrip target.`);continue;}if(target&&!pool.includes(target))throw new Error(`${warlockInvocationById(state.ruleset,id).name} cannot target ${target}.`);if(target){const set=used.get(id)||new Set();if(set.has(target))throw new Error(`${warlockInvocationById(state.ruleset,id).name} must choose a different eligible cantrip for each copy.`);set.add(target);used.set(id,set);}}}catch(error){console.error("[class-ui] Warlock invocation validation failed",error);throw error;}}
function validateCurrentSpellChoices(state){try{if(state.constraints.level==="random")return;const classId=state.constraints.class;if(!["wizard","cleric","bard","druid","paladin","ranger","sorcerer","warlock"].includes(classId))return;const config=spellPickerConfigForState(state);config.validate(state.spellSelections||{});}catch(error){console.error("[class-ui] spell compatibility validation failed",error);throw error;}}
function single(key,label,options,defaultLabel="Random"){return{type:"single",key,label,options,defaultLabel};}
function multi(key,label,options,max){return{type:"multi",key,label,options,max};}
function indexed(key,label,options,index,defaultLabel="Random"){return{type:"indexed",key,label,options,index,defaultLabel};}
function fieldHtml(field,selections){try{if(field.type==="multi"){const selected=new Set(selections[field.key]||[]);return `<fieldset class="class-choice-field class-choice-multi"><legend>${field.label}</legend><small>${selected.size} / ${field.max} fixed · rest Random</small><div class="class-choice-checks">${field.options.map(option=>`<label><input type="checkbox" data-class-multi="${field.key}" value="${option.id}"${selected.has(option.id)?" checked":""}><span>${option.name}</span></label>`).join("")}</div></fieldset>`;}const value=field.type==="indexed"?(selections[field.key]||[])[field.index]||"random":selections[field.key]||"random",attribute=field.type==="indexed"?`data-class-index-choice="${field.key}" data-index="${field.index}"`:`data-class-choice="${field.key}"`,options=[`<option value="random">${field.defaultLabel||"Random"}</option>`,...field.options.map(option=>`<option value="${option.id}"${value===option.id?" selected":""}>${option.name}</option>`)].join("");return `<label class="class-choice-field">${field.label}<select ${attribute}>${options}</select></label>`;}catch(error){console.error(`[class-ui] ${field.key} field failed`,error);throw error;}}
function summaryText(fields,selections){try{const keys=[...new Set(fields.map(field=>field.key))],fixed=keys.reduce((sum,key)=>sum+(Array.isArray(selections[key])?selections[key].filter(Boolean).length:selections[key]?1:0),0);return fixed?`${fixed} class choice${fixed===1?"":"s"} fixed · every other class choice stays Random`:`All class choices Random / automatic`;}catch(error){console.error("[class-ui] summary failed",error);throw error;}}
function resolvedLevel(state){const level=Number(state.constraints.level);return Number.isInteger(level)?level:1;}
function resolvedSubclassId(state){try{if(state.constraints.subclass&&state.constraints.subclass!=="random")return state.constraints.subclass;const data=forgeDataFor(state.ruleset),cls=data.classes.find(item=>item.id===state.constraints.class),level=resolvedLevel(state);if(!cls||level<cls.subclassLevel)return null;const options=data.subclasses.filter(item=>item.classId===cls.id);return options.length===1?options[0].id:null;}catch(error){console.error("[class-ui] subclass resolution failed",error);throw error;}}
