import { buildPremiumPrintModel } from "../print/model.js";

const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
export function renderPremiumPrintSheet(character,target){
  try{const model=buildPremiumPrintModel(character);target.innerHTML=sheet(model);return model;}
  catch(error){console.error("[premium-print] render failed",error);throw error;}
}
function sheet(m){return `<article class="premium-sheet theme-${esc(m.theme.id)}"><div class="ps-frame"><header class="ps-top">${portrait(m)}${identity(m)}${topStats(m)}</header><main class="ps-body"><div class="ps-column ps-left">${panel("Ability Scores",abilities(m))}${passive(m)}${panel("Equipment",list(m.equipment),"ps-equipment")}</div><div class="ps-column ps-center">${panel("Skills",skills(m),"ps-skills")}${panel("Attacks",attacks(m),"ps-attacks")}${panel("Features & Traits",features(m),"ps-features")}</div><div class="ps-column ps-right">${m.feat?panel("Feat",feat(m),"ps-feat"):""}${m.spellcasting?panel("Spellcasting",spells(m),"ps-spells"):""}${panel("Proficiencies & Languages",proficiencies(m),"ps-proficiencies")}${panel("Quick Turn",quickTurn(m),"ps-quick")}</div></main><footer class="ps-footer"><span class="ps-motto">${esc(m.motto)}</span><span class="ps-audit">✓ ${esc(m.audit.status)} · ${esc(m.audit.sourceMode)} · ${esc(m.audit.version)}${m.audit.rawIntegrity?" · RAW integrity":""}</span></footer></div></article>`;}
function portrait(m){return `<section class="ps-portrait"><div class="ps-portrait-art"><span>${esc(m.theme.emblem)}</span><small>${esc(m.theme.label)}</small></div><div class="ps-portrait-caption">${esc(m.identity.className)}${m.identity.subclassName?` · ${esc(m.identity.subclassName)}`:""}</div></section>`;}
function identity(m){return `<section class="ps-identity"><small>Name</small><h1>${esc(m.identity.name)}</h1><dl><div><dt>Class & Level</dt><dd>${esc(m.identity.className)} ${m.identity.level}${m.identity.subclassName?` · ${esc(m.identity.subclassName)}`:""}</dd></div><div><dt>Species</dt><dd>${esc(m.identity.species)}</dd></div><div><dt>Background</dt><dd>${esc(m.identity.background)}</dd></div><div><dt>Size</dt><dd>${esc(m.identity.size)}</dd></div></dl></section>`;}
function topStats(m){const s=m.stats;return `<section class="ps-top-stats"><div class="ps-badge-row">${badge("Proficiency",s.proficiency)}${badge("Armor Class",s.ac)}${badge("Initiative",`${s.initiative}${s.initiativeAdvantage?" ADV":""}`)}${badge("Speed",s.speed)}</div><div class="ps-hp-row">${badge("Max HP",s.hp,"large")}${tracking("Current HP")}${tracking("Temp HP")}</div><div class="ps-save-row"><div><span>Hit Dice</span><strong>${esc(s.hitDice)}</strong></div><div class="ps-death"><span>Death Saves</span><small>Success ○ ○ ○ &nbsp; Failure ○ ○ ○</small></div></div></section>`;}
function badge(label,value,size=""){return `<div class="ps-stat ${size}"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function tracking(label){return `<div class="ps-track"><span>${esc(label)}</span><b>&nbsp;</b></div>`;}
function abilities(m){return `<div class="ps-abilities">${m.abilities.map(a=>`<div class="ps-ability"><i>${a.id.toUpperCase()}</i><span>${esc(a.name)}</span><b>${a.score}</b><em>${esc(a.modifier)}</em><small>${a.proficient?"●":"○"} save ${esc(a.save)}</small></div>`).join("")}</div>`;}
function passive(m){return `<section class="ps-passive"><span>Passive Perception</span><strong>${m.stats.passivePerception}</strong></section>`;}
function skills(m){return `<div class="ps-skill-list">${m.skills.map(s=>`<div class="ps-skill ${s.proficient?"proficient":""}"><span>${s.expertise?"◆":s.proficient?"●":"○"} ${esc(s.name)} <small>(${s.ability})</small></span><b>${esc(s.bonus)}</b></div>`).join("")}</div>`;}
function attacks(m){if(!m.attacks.length)return `<p class="ps-empty">No attack entries.</p>`;return `<div class="ps-attack-head"><span>Weapon</span><span>To Hit</span><span>Damage / Type</span></div>${m.attacks.map(a=>`<div class="ps-attack-row"><strong>${esc(a.name)}</strong><b>${esc(a.toHit)}</b><span>${esc(a.damage)}</span></div>`).join("")}`;}
function feat(m){return `<h3>${esc(m.feat.name)}</h3><p>${esc(m.feat.text)}</p>${m.feat.source?`<small class="ps-source">${esc(m.feat.source)}</small>`:""}`;}
function features(m){return `<div class="ps-feature-list">${m.features.map(f=>`<article><strong>${esc(f.name)}</strong><p>${esc(f.text)}</p><small>${esc(f.timing)} · ${esc(f.source)}</small></article>`).join("")}</div>`;}
function spells(m){const s=m.spellcasting;return `<div class="ps-spell-stats"><span>Ability <b>${esc(s.ability)}</b></span><span>Save DC <b>${s.saveDc}</b></span><span>Attack <b>${esc(s.attackBonus)}</b></span></div><p><strong>Slots:</strong> ${esc(s.slots||"—")}</p><p><strong>Cantrips:</strong> ${esc(s.cantrips.join(", ")||"None")}</p>${s.alwaysPrepared.length?`<p><strong>Always prepared:</strong> ${esc(s.alwaysPrepared.join(", "))}</p>`:""}<p><strong>Prepared:</strong> ${esc(s.prepared.join(", ")||"None")}</p>${s.spellbookCount?`<small class="ps-spellbook">Spellbook: ${s.spellbookCount} spells total</small>`:""}`;}
function proficiencies(m){const p=m.proficiencies;return `<p><strong>Saves:</strong> ${esc(p.saves.join(", "))}</p><p><strong>Tools:</strong> ${esc(p.tools.join(", ")||"None")}</p>${p.masteries.length?`<p><strong>Masteries:</strong> ${esc(p.masteries.join(", "))}</p>`:""}<p><strong>Languages:</strong> ${esc(p.languages.join(", "))}</p>`;}
function quickTurn(m){return `<ol class="ps-quick-list">${m.quickTurn.map(step=>`<li>${esc(step)}</li>`).join("")}</ol>`;}
function list(values){return `<ul class="ps-list">${values.map(value=>`<li>${esc(value)}</li>`).join("")}</ul>`;}
function panel(title,content,className=""){return `<section class="ps-panel ${className}"><h2><span>${esc(title)}</span></h2><div class="ps-panel-body">${content}</div></section>`;}
