import { buildPremiumPrintModel } from "../print/model.js";

const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
export function renderPremiumPrintSheet(character,target){
  try{const model=buildPremiumPrintModel(character);target.innerHTML=packet(model);return model;}
  catch(error){console.error("[premium-print] render failed",error);throw error;}
}
function packet(m){let page=2,html=sheet(m);for(const refs of m.appendix.referencePages)html+=referencePage(m,refs,page++);for(const spells of m.appendix.spellPages)html+=spellPage(m,spells,page++);html+=auditPage(m,page);return html;}
function sheet(m){return `<article class="premium-sheet theme-${esc(m.theme.id)}"><div class="ps-frame"><header class="ps-top">${portrait(m)}${identity(m)}${topStats(m)}</header><main class="ps-body"><div class="ps-column ps-left">${panel("Ability Scores",abilities(m))}${passive(m)}${panel("Equipment",list(m.equipment),"ps-equipment")}</div><div class="ps-column ps-center">${panel("Skills",skills(m),"ps-skills")}${panel("Attacks",attacks(m),"ps-attacks")}${panel("Features & Traits",features(m),"ps-features")}</div><div class="ps-column ps-right">${m.feat?panel("Feat",feat(m),"ps-feat"):""}${m.rogueResources?panel("Rogue Resources",rogueResources(m),"ps-rogue"):""}${m.spellcasting?panel("Spellcasting",spells(m),"ps-spells"):""}${panel("Proficiencies & Languages",proficiencies(m),"ps-proficiencies")}${panel("Quick Turn",quickTurn(m),"ps-quick")}</div></main><footer class="ps-footer"><span class="ps-motto">${esc(m.motto)}</span><span class="ps-audit">✓ ${esc(m.audit.status)} · ${esc(m.audit.sourceMode)} · ${esc(m.audit.version)}${m.audit.rawIntegrity?" · RAW integrity":""} · Page 1/${m.packet.totalPages}</span></footer></div></article>`;}
function referencePage(m,refs,page){return appendixShell(m,"Rules & Provenance","Complete active rules",`<div class="ps-appendix-intro"><p>These are the active species, background, feat, class, subclass, Fighting Style, and Weapon Mastery references generated for this exact character. Page 1 is the quick-play sheet; this appendix is the complete rule-reference record.</p></div><div class="ps-reference-grid">${refs.map(referenceCard).join("")}</div>`,page);}
function referenceCard(ref){return `<article class="ps-reference-card"><header><span>${esc(ref.category||"Rule")}</span><strong>${esc(ref.name)}</strong></header><p>${esc(ref.text)}</p><footer><span>${esc(ref.timing||"Reference")}</span><b>${esc(ref.source)}</b></footer></article>`;}
function spellPage(m,spells,page){return appendixShell(m,"Spell Loadout","Validated generated spell state",`<div class="ps-spell-appendix-head"><div><span>Spellcasting Ability</span><strong>${esc(spells.ability)}</strong></div><div><span>Save DC</span><strong>${spells.saveDc}</strong></div><div><span>Spell Attack</span><strong>${esc(spells.attackBonus)}</strong></div><div class="wide"><span>Slots</span><strong>${esc(spells.slots||"—")}</strong></div></div><p class="ps-appendix-note">${esc(spells.source)}. This page proves the generated loadout and preparation state; it does not invent per-spell page citations where Character Forge does not yet maintain a verified structured spell-text reference.</p><div class="ps-spell-entry-grid">${spells.entries.map(spellEntry).join("")}</div>`,page);}
function spellEntry(spell){return `<article class="ps-spell-entry"><span>${esc(spell.levelLabel)}</span><strong>${esc(spell.name)}</strong><small>${esc(spell.tags.join(" · ")||"Known")}</small></article>`;}
function auditPage(m,page){const a=m.appendix.audit;return appendixShell(m,"Rules Audit","Generation proof",`<section class="ps-audit-summary"><div><span>Status</span><strong>${esc(a.status)}</strong></div><div><span>Source Mode</span><strong>${esc(a.sourceMode)}</strong></div><div><span>Rules</span><strong>${esc(a.rulesLabel)}</strong></div><div><span>License</span><strong>${esc(a.license)}</strong></div></section><section class="ps-audit-source"><h3>${esc(a.sourceDocument)} · ${esc(a.sourceVersion)}</h3><p>${esc(a.scope)}</p><p class="ps-audit-url">Official source: ${esc(a.sourceUrl||a.sourcePdfUrl||"")}</p><p class="ps-audit-url">Official PDF: ${esc(a.sourcePdfUrl||"")}</p></section><section class="ps-audit-mechanics"><h3>Verified identity</h3>${a.mechanics.map(item=>`<article><span>${esc(item.label)}</span><strong>${esc(item.value)}</strong><small>${esc(item.source)}</small></article>`).join("")}</section><section class="ps-audit-checks"><h3>Validation checks</h3><ol>${a.checks.map(check=>`<li>${esc(check)}</li>`).join("")}</ol></section>`,page);}
function appendixShell(m,title,kicker,body,page){return `<section class="ps-appendix-page theme-${esc(m.theme.id)}"><div class="ps-appendix-frame"><header class="ps-appendix-header"><div><span>${esc(kicker)}</span><h1>${esc(title)}</h1><p>${esc(m.identity.name)} · Level ${m.identity.level} ${esc(m.identity.className)}${m.identity.subclassName?` · ${esc(m.identity.subclassName)}`:""}</p></div><b>Page ${page}/${m.packet.totalPages}</b></header><main class="ps-appendix-body">${body}</main><footer class="ps-appendix-footer"><span>Character Forge · ${esc(m.audit.version)}</span><strong>✓ ${esc(m.audit.status)}${m.audit.rawIntegrity?" · RAW integrity":""}</strong></footer></div></section>`;}
function portrait(m){const art=m.portraitDataUrl?`<div class="ps-portrait-art has-image"><img src="${esc(m.portraitDataUrl)}" alt=""></div>`:`<div class="ps-portrait-art"><div class="ps-crest"><span>${esc(m.theme.emblem)}</span></div><small>${esc(m.theme.label)}</small></div>`;return `<section class="ps-portrait">${art}<div class="ps-portrait-caption">${esc(m.identity.className)}${m.identity.subclassName?` · ${esc(m.identity.subclassName)}`:""}</div></section>`;}
function identity(m){return `<section class="ps-identity"><small>Name</small><h1>${esc(m.identity.name)}</h1><dl><div><dt>Class & Level</dt><dd>${esc(m.identity.className)} ${m.identity.level}${m.identity.subclassName?` · ${esc(m.identity.subclassName)}`:""}</dd></div><div><dt>Species</dt><dd>${esc(m.identity.species)}</dd></div><div><dt>Background</dt><dd>${esc(m.identity.background)}</dd></div><div><dt>Size</dt><dd>${esc(m.identity.size)}</dd></div></dl></section>`;}
function topStats(m){const s=m.stats;return `<section class="ps-top-stats"><div class="ps-badge-row">${badge("Proficiency",s.proficiency)}${badge("Armor Class",s.ac)}${badge("Initiative",`${s.initiative}${s.initiativeAdvantage?" ADV":""}`)}${badge("Speed",s.speed)}</div><div class="ps-hp-row">${badge("Max HP",s.hp,"large")}${tracking("Current HP")}${tracking("Temp HP")}</div><div class="ps-save-row"><div><span>Hit Dice</span><strong>${esc(s.hitDice)}</strong></div><div class="ps-death"><span>Death Saves</span><small>Success ○ ○ ○ &nbsp; Failure ○ ○ ○</small></div></div></section>`;}
function badge(label,value,size=""){return `<div class="ps-stat ${size}"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function tracking(label){return `<div class="ps-track"><span>${esc(label)}</span><b>&nbsp;</b></div>`;}
function abilities(m){return `<div class="ps-abilities">${m.abilities.map(a=>`<div class="ps-ability"><i><span>${a.id.toUpperCase()}</span></i><span>${esc(a.name)}</span><b>${a.score}</b><em>${esc(a.modifier)}</em><small>${a.proficient?"●":"○"} save ${esc(a.save)}</small></div>`).join("")}</div>`;}
function passive(m){return `<section class="ps-passive"><span>Passive Perception</span><strong>${m.stats.passivePerception}</strong></section>`;}
function skills(m){return `<div class="ps-skill-list">${m.skills.map(s=>`<div class="ps-skill ${s.proficient?"proficient":""}"><span>${s.expertise?"◆":s.proficient?"●":"○"} ${esc(s.name)} <small>(${s.ability})</small></span><b>${esc(s.bonus)}</b></div>`).join("")}</div>`;}
function attacks(m){if(!m.attacks.length)return `<p class="ps-empty">No attack entries.</p>`;return `<div class="ps-attack-head"><span>Weapon</span><span>To Hit</span><span>Damage / Type</span></div>${m.attacks.map(a=>`<div class="ps-attack-row"><strong>${esc(a.name)}</strong><b>${esc(a.toHit)}</b><span>${esc(a.damage)}</span></div>`).join("")}`;}
function feat(m){return `<h3>${esc(m.feat.name)}</h3><p>${esc(m.feat.text)}</p>${m.feat.source?`<small class="ps-source">${esc(m.feat.source)}</small>`:""}`;}
function features(m){return `<div class="ps-feature-list">${m.features.map(f=>`<article><strong>${esc(f.name)}</strong><p>${esc(f.text)}</p><small>${esc(f.timing)} · ${esc(f.source)}</small></article>`).join("")}</div>`;}
function rogueResources(m){
  const r=m.rogueResources;
  if(r.ruleset==="2014")return `<div class="ps-rogue-stats">${rogueStat("Sneak",r.sneakAttack)}${rogueStat("Expertise",r.expertise)}${rogueStat("Reliable",r.reliableTalent?"YES":"—")}${rogueStat("Blindsense",r.blindsense||"—")}${rogueStat("Reflexes",r.thiefReflexes?"2 turns R1":"—")}</div><p class="ps-empty">Classic Rogue: no Weapon Mastery or Cunning Strike. Use the sourced feature cards for current Rogue and Thief abilities.</p>`;
  return `<div class="ps-rogue-stats">${rogueStat("Sneak",r.sneakAttack)}${rogueStat("Expertise",r.expertise)}${rogueStat("Masteries",r.masteries)}${rogueStat("Strike DC",r.cunningStrikeDc??"—")}${rogueStat("Effects",r.effectsPerSneak||"—")}${rogueStat("Reliable",r.reliableTalent?"YES":"—")}</div>${r.options.length?`<div class="ps-rogue-options">${r.options.map(option=>`<article><b>${esc(option.name)} · ${esc(option.cost)}${option.save?` · ${esc(option.save)}`:""}</b><p>${esc(option.effect)}${option.requires?` Requires ${esc(option.requires)} on your person.`:""}</p></article>`).join("")}</div>`:`<p class="ps-empty">Cunning Strike unlocks at level 5.</p>`}${r.scrollWarning?`<p class="ps-rogue-warning"><strong>Use Magic Device:</strong> ${esc(r.scrollWarning)}</p>`:""}`;
}
function rogueStat(label,value){return `<span><small>${esc(label)}</small><b>${esc(value)}</b></span>`;}
function spells(m){const s=m.spellcasting;return `<div class="ps-spell-stats"><span>Ability <b>${esc(s.ability)}</b></span><span>Save DC <b>${s.saveDc}</b></span><span>Attack <b>${esc(s.attackBonus)}</b></span></div><p><strong>Slots:</strong> ${esc(s.slots||"—")}</p><p><strong>Cantrips:</strong> ${esc(s.cantrips.join(", ")||"None")}</p>${s.alwaysPrepared.length?`<p><strong>Always prepared:</strong> ${esc(s.alwaysPrepared.join(", "))}</p>`:""}<p><strong>Prepared:</strong> ${esc(s.prepared.join(", ")||"None")}</p>${s.spellbookCount?`<small class="ps-spellbook">Spellbook: ${s.spellbookCount} spells total</small>`:""}`;}
function proficiencies(m){const p=m.proficiencies;return `<p><strong>Saves:</strong> ${esc(p.saves.join(", "))}</p><p><strong>Tools:</strong> ${esc(p.tools.join(", ")||"None")}</p>${p.masteries.length?`<p><strong>Masteries:</strong> ${esc(p.masteries.join(", "))}</p>`:""}<p><strong>Languages:</strong> ${esc(p.languages.join(", "))}</p>`;}
function quickTurn(m){return `<ol class="ps-quick-list">${m.quickTurn.map(step=>`<li>${esc(step)}</li>`).join("")}</ol>`;}
function list(values){return `<ul class="ps-list">${values.map(value=>`<li>${esc(value)}</li>`).join("")}</ul>`;}
function panel(title,content,className=""){return `<section class="ps-panel ${className}"><h2><span>${esc(title)}</span></h2><div class="ps-panel-body">${content}</div></section>`;}
