import { ABILITIES, SKILLS } from "../schema.js";
import { abilityMod } from "../rules/math.js";

const fmt = value => value >= 0 ? `+${value}` : `${value}`;
const label = text => text.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
const joinText = values => values.filter(Boolean).join(" · ");

export function renderCharacter(character, target) {
  try {
    const homebrew = character.homebrew.length > 0;
    const badge = homebrew ? "HOMEBREW · CALCULATED" : "✓ RAW VALIDATED";
    target.innerHTML = `<article class="character-sheet">
      <header class="character-hero">
        <div class="character-topline">
          <div><p class="section-kicker">CHARACTER FORGED</p><h2 class="character-name">${character.name}</h2>
          <p class="character-subtitle">Level ${character.level} ${character.species.name} ${character.class.name}${character.subclass?` · ${character.subclass.name}`:""}<br>${character.background.name} · ${character.size}</p></div>
          <span class="validation-badge ${homebrew?"hb":"raw"}">${badge}</span>
        </div>
        <div class="character-actions"><button class="action-button" data-action="reroll">↻ Forge again</button><button class="action-button" data-action="print">Print / PDF</button></div>
        <div class="ability-grid">${ABILITIES.map(key=>abilityCard(key,character.abilities[key])).join("")}</div>
      </header>
      <div class="metric-grid">${metric("Armor Class",character.ac)}${metric("Hit Points",character.hp)}${metric("Initiative",fmt(character.initiative))}${metric("Speed",`${character.speed} ft`)}${metric("Proficiency",fmt(character.proficiency))}${metric("Passive Perception",character.passivePerception)}</div>
      <div class="detail-grid">
        ${detail("Attacks",character.attacks.map(attack=>`<div class="attack-row"><span>${attack.name}</span><strong>${fmt(attack.attackBonus)}</strong><span>${attack.damage}${fmt(attack.damageBonus)} ${attack.type}</span></div>`).join(""),"span-2")}
        ${detail("Saving Throws",`<p>${ABILITIES.map(key=>`${character.saves.includes(key)?"●":"○"} ${key.toUpperCase()} ${fmt(character.saveBonuses[key])}`).join(" &nbsp; ")}</p>`)}
        ${detail("Languages",`<p>${joinText(character.languages)}</p>`)}
        ${detail("Skills",`<div class="skills">${Object.keys(SKILLS).map(skill=>`<span class="skill ${character.skills.includes(skill)?"is-proficient":""}"><span>${character.skills.includes(skill)?"●":"○"} ${label(skill)}</span><strong>${fmt(character.skillBonuses[skill])}</strong></span>`).join("")}</div>`,"span-2")}
        ${detail("Features",`<p>${joinText([...(character.species.traits||[]),character.background.feature,...character.features])}</p>`,"span-2")}
        ${character.feats.length?detail("Feats",`<p>${joinText(character.feats.map(feat=>feat.name))}</p>`):""}
        ${character.masteryIds.length?detail("Weapon Mastery",`<p>${joinText(character.masteryIds)}</p>`):""}
        ${detail("Equipment",`<p>${character.inventory.map(item=>`${item.quantity > 1 ? `${item.quantity} × ` : ""}${item.name}`).join(", ")}</p>`,"span-2")}
        ${homebrew?detail("Homebrew Used",`<p>${joinText(character.homebrew.map(item=>item.name))}</p>`,"span-2"):""}
      </div>
      <footer class="sheet-footer"><span>Validation passed · ${character.sourceMode} · ${character.ruleset}</span><span>Generated by Character Forge</span></footer>
    </article>`;
  } catch (error) {
    console.error("[ui] renderCharacter failed", error);
    throw error;
  }
}

function abilityCard(key, score) {
  try { return `<div class="ability-card"><span>${key.toUpperCase()}</span><strong>${score}</strong><em>${fmt(abilityMod(score))}</em></div>`; }
  catch (error) { console.error("[ui] abilityCard failed", error); throw error; }
}
function metric(name,value) { return `<div class="metric"><span>${name}</span><strong>${value}</strong></div>`; }
function detail(title,content,className="") { return `<section class="detail-card ${className}"><h3>${title}</h3>${content}</section>`; }
