import { ABILITIES, SKILLS } from "../schema.js";
import { abilityMod } from "../rules/math.js";
import { buildQuickReference } from "../rules/reference.js";
import { characterActiveSpellReferences } from "../rules/spell-reference.js";
import { wizardSpellsFor } from "../data/wizard-spells.js";
import { clericSpellsFor } from "../data/cleric-spells.js";
import { orderedSheetSections, sheetProfileFor } from "./sheet-profiles.js";

const fmt=value=>value>=0?`+${value}`:`${value}`,label=text=>text.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase()),escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));

export function renderCharacter(character,target){
  try{
    if(character.sourceMode!=="RAW"||(character.homebrew||[]).length)throw new Error("Printable Character Forge sheets accept RAW characters only.");
    const profile=sheetProfileFor(character.class.id);
    target.innerHTML=`<article class="character-sheet sheet-theme-${profile.theme}" data-class="${escapeHtml(profile.id)}" data-ruleset="${escapeHtml(character.ruleset)}"><header class="character-hero"><div class="class-ribbon"><span>${escapeHtml(profile.label)}</span><small>${escapeHtml(profile.theme.replaceAll("-"," "))} sheet</small></div><div class="character-topline"><div><p class="section-kicker">CHARACTER FORGED</p><h2 class="character-name">${escapeHtml(character.name)}</h2><p class="character-subtitle">Level ${character.level} ${escapeHtml(character.species.name)} ${escapeHtml(character.class.name)}${character.subclass?` · ${escapeHtml(character.subclass.name)}`:""}<br>${escapeHtml(character.background.name)} · ${escapeHtml(character.size)}</p></div><span class="validation-badge raw">✓ RAW VALIDATED</span></div><div class="character-actions"><button class="action-button primary-action" data-action="save">＋ Save to Pregens</button><button class="action-button" data-action="reroll">↻ Forge again</button><button class="action-button" data-action="print">Print / PDF</button></div><div class="ability-grid">${ABILITIES.map(key=>abilityCard(key,character.abilities[key])).join("")}</div></header><div class="metric-grid">${metric("Armor Class",character.ac)}${metric("Hit Points",character.hp)}${metric("Initiative",fmt(character.initiative))}${metric("Speed",`${character.speed} ft`)}${metric("Proficiency",fmt(character.proficiency))}${metric("Passive Perception",character.passivePerception)}</div><div class="detail-grid">${renderSheetSections(character)}</div><footer class="sheet-footer"><span>Validation passed · RAW · ${escapeHtml(character.ruleset)}</span><span>${escapeHtml(profile.label)} play sheet · Character Forge</span></footer></article>`;
  }catch(error){console.error("[ui] renderCharacter failed",error);throw error;}
}
function renderSheetSections(character){try{return orderedSheetSections(character).map(section=>renderSection(character,section)).join("");}catch(error){console.error("[ui] renderSheetSections failed",error);throw error;}}
function renderSection(character,section){
  try{
    if(section==="attacks")return detail("Attacks",character.attacks.map(attack=>`<div class="attack-row"><span>${escapeHtml(attack.name)}</span><strong>${fmt(attack.attackBonus)}</strong><span>${escapeHtml(attack.damage)}${fmt(attack.damageBonus)} ${escapeHtml(attack.type)}</span></div>`).join(""),"span-2 sheet-section-attacks");
    if(section==="savingThrows")return detail("Saving Throws",`<div class="save-grid">${ABILITIES.map(key=>`<span class="save-entry ${character.saves.includes(key)?"is-proficient":""}"><b>${character.saves.includes(key)?"●":"○"} ${key.toUpperCase()}</b><strong>${fmt(character.saveBonuses[key])}</strong></span>`).join("")}</div>`,"span-2 sheet-section-saves");
    if(section==="skills")return detail("Skills",`<div class="skills">${Object.keys(SKILLS).map(skill=>skillRow(character,skill)).join("")}</div>`,"span-2 sheet-section-skills");
    if(section==="feats")return detail("Feats & Boons",featSummary(character),"span-2 sheet-section-feats");
    if(section==="spellcasting")return detail("Spellcasting",spellSummary(character),"span-2 sheet-section-spellcasting");
    if(section==="spellReference")return detail("Spell Reference",spellReferenceSummary(character),"span-2 sheet-section-spell-reference");
    if(section==="classResources")return detail("Class Resources",classResourceSummary(character),"span-2 sheet-section-resources");
    if(section==="playReference")return detail("Play Reference",referenceSummary(character),"span-2 sheet-section-play-reference");
    if(section==="equipment")return detail("Equipment",`<p>${character.inventory.map(item=>`${item.quantity>1?`${item.quantity} × `:""}${escapeHtml(item.name)}`).join(", ")}</p>`,"span-2 sheet-section-equipment");
    throw new Error(`Unknown character sheet section: ${section}`);
  }catch(error){console.error(`[ui] failed to render sheet section ${section}`,error);throw error;}
}
function classResourceSummary(character){try{if(!character.classResources?.length)throw new Error(`${character.class.name} sheet requested class resources that are missing from the validated character model.`);return `<div class="resource-grid">${character.classResources.map(resource=>`<article class="resource-card"><span>${escapeHtml(resource.name)}</span><strong>${escapeHtml(resource.value)}</strong>${resource.detail?`<small>${escapeHtml(resource.detail)}</small>`:""}</article>`).join("")}</div>`;}catch(error){console.error("[ui] classResourceSummary failed",error);throw error;}}
function featSummary(character){
  try{
    const references=buildQuickReference(character).filter(item=>item.id.startsWith("feat:"));
    if(!references.length)return`<p>No feat rules are active for this character.</p>`;
    return `<div class="feat-grid">${references.map(item=>`<article class="feat-card"><div><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.category)}</span></div><p>${escapeHtml(item.text)}</p><small>${escapeHtml(item.timing)}</small></article>`).join("")}</div>`;
  }catch(error){console.error("[ui] featSummary failed",error);throw error;}
}
function skillRow(character,skill){try{const proficient=character.skills.includes(skill),expert=character.expertise.includes(skill),mark=expert?"◆":proficient?"●":"○";return `<span class="skill ${proficient?"is-proficient":""}"><span>${mark} ${label(skill)}${expert?" · Expertise":""}</span><strong>${fmt(character.skillBonuses[skill])}</strong></span>`;}catch(error){console.error("[ui] skillRow failed",error);throw error;}}
function spellReferenceSummary(character){try{return `<div class="spell-reference-grid">${characterActiveSpellReferences(character).map(spell=>`<article class="spell-reference-card"><div class="spell-reference-head"><div><strong>${escapeHtml(spell.name)}</strong><span>${spell.level===0?"Cantrip":`Level ${spell.level}`} · ${escapeHtml(spell.school)} · ${escapeHtml(spell.preparation)}</span></div><span>${escapeHtml(spell.castingTime)}</span></div><div class="spell-reference-meta"><span>${escapeHtml(spell.range)}</span><span>${escapeHtml(spell.duration)}</span><span>${escapeHtml(spell.components)}</span><span>${escapeHtml(spell.resolution)}</span></div>${spell.currentEffect?`<b>${escapeHtml(spell.currentEffect)}</b>`:""}<p>${escapeHtml(spell.effect)}</p>${spell.upcast?`<p class="spell-upcast"><strong>Higher slot:</strong> ${escapeHtml(spell.upcast)}</p>`:""}<div class="spell-reference-foot"><div>${spell.ritual?`<em>Ritual</em>`:""}${spell.concentration?`<em>Concentration</em>`:""}</div><small>${escapeHtml(spell.source)} · p.${spell.srdPage}</small></div></article>`).join("")}</div>`;}catch(error){console.error("[ui] spellReferenceSummary failed",error);throw error;}}
function referenceSummary(character){try{const entries=buildQuickReference(character).filter(item=>!item.id.startsWith("feat:"));return `<div class="reference-list">${entries.map(item=>`<article class="reference-item"><div class="reference-head"><strong>${escapeHtml(item.name)}</strong><span class="reference-tag">${escapeHtml(item.category)}</span></div><p>${escapeHtml(item.text)}</p><span class="reference-timing">${escapeHtml(item.timing)}</span></article>`).join("")}</div>`;}catch(error){console.error("[ui] referenceSummary failed",error);throw error;}}
function spellSummary(character){try{const source=character.class.id==="cleric"?clericSpellsFor(character.ruleset):wizardSpellsFor(character.ruleset),catalog=new Map(source.map(spell=>[spell.id,spell.name])),names=ids=>(ids||[]).map(id=>catalog.get(id)||id).join(", "),slots=Object.entries(character.spells.slots).map(([level,count])=>`${level}${level==="1"?"st":level==="2"?"nd":level==="3"?"rd":"th"}: ${count}`).join(" · ");const groups=[`<div class="spell-group"><strong>Cantrips</strong><p>${names(character.spells.cantrips.all)}</p></div>`];if(character.spells.alwaysPrepared?.length)groups.push(`<div class="spell-group"><strong>Always Prepared</strong><p>${names(character.spells.alwaysPrepared)}</p></div>`);groups.push(`<div class="spell-group"><strong>Prepared</strong><p>${names(character.spells.prepared.all)}</p></div>`);if(character.spells.spellbook)groups.push(`<div class="spell-group"><strong>Spellbook</strong><p>${names(character.spells.spellbook.all)}</p></div>`);return `<div class="spell-summary"><div class="spell-stat-row"><div class="spell-stat"><span>Spell Save DC</span><strong>${character.spells.saveDc}</strong></div><div class="spell-stat"><span>Spell Attack</span><strong>${fmt(character.spells.attackBonus)}</strong></div><div class="spell-stat"><span>Slots</span><strong>${slots}</strong></div></div>${groups.join("")}</div>`;}catch(error){console.error("[ui] spellSummary failed",error);throw error;}}
function abilityCard(key,score){try{return `<div class="ability-card"><span>${key.toUpperCase()}</span><strong>${score}</strong><em>${fmt(abilityMod(score))}</em></div>`;}catch(error){console.error("[ui] abilityCard failed",error);throw error;}}
function metric(name,value){return `<div class="metric"><span>${name}</span><strong>${value}</strong></div>`;}
function detail(title,content,className=""){return `<section class="detail-card ${className}"><h3>${title}</h3>${content}</section>`;}
