import { WIZARD_SPELL_MASTERY_ACTION_IDS_2024 } from "../data/wizard-spells.js";
import { CASTER_IDS, spellPickerConfigForState } from "./spell-picker-config.js";
import { emptySpellSelections } from "./spell-selection-state.js";

const LABELS={cantrips:"Cantrips",known:"Known Spells",spellbook:"Spellbook",prepared:"Prepared",magicalSecrets:"Magical Secrets",loreDiscoveries:"Lore Discoveries"},CASTERS=new Set(CASTER_IDS),MASTERY_ELIGIBLE_2024=new Set(WIZARD_SPELL_MASTERY_ACTION_IDS_2024);
export { emptySpellSelections, spellPickerConfigForState };

export function bindSpellPicker(state,showToast){
  try{
    const button=document.getElementById("openSpellPicker"),dialog=document.getElementById("spellDialog");button.addEventListener("click",()=>{try{renderPicker(state);dialog.showModal();}catch(error){showToast(error.message,true);}});document.getElementById("closeSpellPicker").addEventListener("click",()=>dialog.close());document.getElementById("doneSpellPicker").addEventListener("click",()=>dialog.close());document.getElementById("spellSearch").addEventListener("input",filterPicker);
    dialog.addEventListener("change",event=>{const input=event.target.closest("input[data-spell-id]");if(input){const bucket=input.dataset.bucket,id=input.dataset.spellId,previous=new Set(state.spellSelections[bucket]||[]),next=new Set(previous);input.checked?next.add(id):next.delete(id);const proposed={...state.spellSelections,[bucket]:[...next]};try{spellPickerConfigForState(state).validate(proposed);state.spellSelections=proposed;renderPicker(state);}catch(error){input.checked=previous.has(id);console.error("[spell-picker] choice blocked",error);showToast(error.message,true);}return;}const select=event.target.closest("select[data-wizard-special]");if(select){const field=select.dataset.wizardSpecial,previous=state.spellSelections[field]||null,proposed={...state.spellSelections,[field]:select.value||null};try{spellPickerConfigForState(state).validate(proposed);state.spellSelections=proposed;renderPicker(state);}catch(error){select.value=previous||"";console.error("[spell-picker] Wizard special choice blocked",error);showToast(error.message,true);}}});
    ["class","level","ruleset","subclass"].forEach(id=>document.getElementById(id).addEventListener("change",()=>{state.spellSelections=emptySpellSelections();refreshSpellPicker(state);}));refreshSpellPicker(state);
  }catch(error){console.error("[spell-picker] bind failed",error);throw error;}
}
export function refreshSpellPicker(state){try{const panel=document.getElementById("spellPickerPanel"),button=document.getElementById("openSpellPicker"),caster=CASTERS.has(state.constraints.class);panel.hidden=!caster;if(!caster)return;const hasLevel=state.constraints.level!=="random";let available=false;if(hasLevel){try{available=spellPickerConfigForState(state).available!==false;}catch(error){console.error("[spell-picker] availability check failed",error);}}button.disabled=!hasLevel||!available;button.textContent=!hasLevel?"Select level first":available?"Choose spells":"No class spells yet";document.getElementById("spellPickerHint").textContent=!hasLevel?"Leave Level on Random for a fully randomized spell loadout, or choose a level to pick specific spells.":available?"Fix any legal spell choices you care about. Forge fills every remaining legal slot at Random.":"This class has no selectable class spells at this level; Forge still applies any automatic magic correctly.";updateSummary(state);}catch(error){console.error("[spell-picker] refresh failed",error);throw error;}}
function renderPicker(state){try{if(!CASTERS.has(state.constraints.class)||state.constraints.level==="random")throw new Error("Choose a supported spellcasting class and a specific level before selecting spells.");const config=spellPickerConfigForState(state);if(config.available===false)throw new Error("This class has no selectable class spells at this level.");let html=config.buckets.map(bucket=>section(bucket,state,config)).join("");if(config.always.size)html+=alwaysSection(config.spells,config.always,config.alwaysLabel);const level=Number(state.constraints.level);if(state.constraints.class==="wizard"&&level>=18)html+=masterySection(config.spells,state);if(state.constraints.class==="wizard"&&level>=20)html+=signatureSection(config.spells,state);document.getElementById("spellPickerLists").innerHTML=html;document.getElementById("spellSearch").value="";updateSummary(state);}catch(error){console.error("[spell-picker] render failed",error);throw error;}}
function section(bucket,state,config){try{const pool=config.poolFor(bucket),selected=new Set(state.spellSelections[bucket]||[]),limit=config.limits[bucket],dynamic=typeof config.dynamicLimit==="object"?config.dynamicLimit[bucket]:config.dynamicLimit,note=config.notes?.[bucket],limitText=limit===null?(dynamic||"ability-based limit"):`${selected.size} / ${limit}`;return `<section class="spell-bucket"><div class="spell-bucket-head"><h3>${LABELS[bucket]||bucket}</h3><span>${limitText}${note?` · ${note}`:""} · rest Random</span></div><div class="spell-list">${pool.map(spell=>spellOption(spell,bucket,selected)).join("")}</div></section>`;}catch(error){console.error(`[spell-picker] ${bucket} section failed`,error);throw error;}}
function masterySection(spells,state){try{const options=level=>spells.filter(spell=>spell.level===level&&(state.ruleset!=="2024"||MASTERY_ELIGIBLE_2024.has(spell.id))),select=(field,label,values)=>`<label class="wizard-special-select">${label}<select data-wizard-special="${field}"><option value="">Random</option>${values.map(spell=>`<option value="${spell.id}" ${state.spellSelections[field]===spell.id?"selected":""}>${spell.name}</option>`).join("")}</select></label>`,rule=state.ruleset==="2014"?"Level 18 · any level-1 + level-2 Wizard spell":"Level 18 · Action casting time only",note=state.ruleset==="2014"?"Each mastered spell must be prepared to cast it at its lowest level without a spell slot. This Forge loadout keeps both mastered spells in the normal prepared selection, where they count against your prepared total. After 8 hours of study, either or both mastered spells can be exchanged for same-level Wizard spells in the spellbook.":"Each mastered spell is always prepared and can be cast at its lowest level without a spell slot. Leave either choice Random for Forge to choose a legal spell from the finished spellbook.";return `<section class="spell-bucket wizard-special-bucket"><div class="spell-bucket-head"><h3>Spell Mastery</h3><span>${rule}</span></div><div class="wizard-special-fields">${select("masteryLevel1","Level 1 mastery",options(1))}${select("masteryLevel2","Level 2 mastery",options(2))}</div><p class="wizard-special-note">${note}</p></section>`;}catch(error){console.error("[spell-picker] Spell Mastery section failed",error);throw error;}}
function signatureSection(spells,state){try{const pool=spells.filter(spell=>spell.level===3),selected=new Set(state.spellSelections.signatureSpells||[]);return `<section class="spell-bucket wizard-special-bucket"><div class="spell-bucket-head"><h3>Signature Spells</h3><span>${selected.size} / 2 · rest Random</span></div><div class="spell-list">${pool.map(spell=>spellOption(spell,"signatureSpells",selected)).join("")}</div><p class="wizard-special-note">Choose up to two level-3 spells. Forge fills any remaining Signature Spell choice from the finished spellbook. Signature Spells are always prepared and each has one free level-3 casting per Short or Long Rest.</p></section>`;}catch(error){console.error("[spell-picker] Signature Spell section failed",error);throw error;}}
function spellOption(spell,bucket,selected){return `<label class="spell-option" data-search="${spell.name.toLowerCase()}"><input type="checkbox" data-spell-id="${spell.id}" data-bucket="${bucket}" ${selected.has(spell.id)?"checked":""}><span><strong>${spell.name}</strong><small>${spell.level===0?"Cantrip":`Level ${spell.level}`}${spell.school?` · ${spell.school}`:""}</small></span></label>`;}
function alwaysSection(spells,always,label){const values=spells.filter(spell=>always.has(spell.id));return `<section class="spell-bucket"><div class="spell-bucket-head"><h3>Always Prepared</h3><span>${label||"Does not use normal spell choices"}</span></div><div class="spell-list">${values.map(spell=>`<div class="spell-option is-fixed" data-search="${spell.name.toLowerCase()}"><span><strong>${spell.name}</strong><small>${spell.level===0?"Cantrip":`Level ${spell.level}`}</small></span></div>`).join("")}</div></section>`;}
function filterPicker(){try{const query=document.getElementById("spellSearch").value.trim().toLowerCase();document.querySelectorAll(".spell-option").forEach(option=>option.hidden=!!query&&!option.dataset.search?.includes(query)&&!option.textContent.toLowerCase().includes(query));}catch(error){console.error("[spell-picker] filter failed",error);throw error;}}
function updateSummary(state){try{const total=Object.values(state.spellSelections||{}).reduce((sum,value)=>sum+(Array.isArray(value)?value.length:value?1:0),0),text=total?`${total} choice${total===1?"":"s"} fixed · Forge fills every remaining legal slot`:"All spell choices Random";for(const id of ["spellChoiceSummary","spellDialogSummary"]){const node=document.getElementById(id);if(node)node.textContent=text;}}catch(error){console.error("[spell-picker] summary failed",error);throw error;}}
