export const CLASS_DOSSIER=Object.freeze({
  barbarian:{epithet:"Primal Fury",awakening:["held a broken line after everyone else fell back","answered a threat with a fury that felt older than fear","discovered that anger could become discipline when someone needed protection"],duty:"stand where danger is worst and make strength mean safety",burden:"fears the fury will someday choose the target instead of serving the cause",look:"hide, leather, scarred metal, and practical gear worn without ornament",combat:"takes the dangerous lane, enters Rage when pressure peaks, and refuses to give ground",quote:"Strength is survival. Fury is freedom."},
  bard:{epithet:"Living Legend",awakening:["turned a frightened crowd into a chorus that would not break","learned that the right words could change a battle before steel crossed","found power in a story told at exactly the moment hope was failing"],duty:"carry truth, courage, and memory farther than fear can travel",burden:"sometimes hides uncertainty behind wit and performance",look:"travel-worn finery, a treasured instrument or focus, and small keepsakes from old roads",combat:"shifts the rhythm of a fight with inspiration, magic, and perfectly timed interference",quote:"Every battle deserves a story worth remembering."},
  cleric:{epithet:"Sacred",awakening:["answered a desperate prayer and felt something answer back","stood between a frightened community and a darkness no one else would face","learned that faith was less about certainty than choosing whom to serve"],duty:"turn belief into practical protection, healing, and courage",burden:"worries that one unanswered plea will matter more than every prayer that succeeded",look:"carefully tended gear, a visible sacred focus, and signs of ritual use rather than luxury",combat:"anchors allies with divine magic, protection, and decisive bursts of sacred force",quote:"In faith we stand. In light we endure."},
  druid:{epithet:"The Old Wild",awakening:["survived a night when the wilderness seemed to speak in every sound","protected a living place others saw only as a resource","learned to change shape and viewpoint before changing the world around them"],duty:"protect the balance between people, beasts, weather, and wild places",burden:"sometimes trusts the patience of nature more readily than the promises of people",look:"weathered natural materials, practical layers, and tokens gathered rather than purchased",combat:"changes roles fluidly, using terrain, magic, and Wild Shape to answer the battlefield",quote:"The old world is always listening."},
  fighter:{epithet:"Master at Arms",awakening:["won a fight by doing the simple things correctly while everyone else panicked","learned that discipline outlasted bravado","became the person others looked toward when plans collapsed"],duty:"make preparation, positioning, and steel count when lives depend on them",burden:"measures mistakes too harshly and carries old tactical failures longer than necessary",look:"maintained weapons, fitted armor, and equipment placed exactly where muscle memory expects it",combat:"controls distance and tempo, spends resources deliberately, and turns openings into decisive attacks",quote:"Steel answers when words fail."},
  monk:{epithet:"Centered Discipline",awakening:["found stillness in the instant before violence","learned to move through danger without letting danger dictate the mind","discovered that control of breath could become control of battle"],duty:"master the self so power is never separated from judgment",burden:"can mistake emotional distance for wisdom when the stakes become personal",look:"uncluttered travel gear, carefully wrapped hands or feet, and one or two meaningful personal tokens",combat:"uses mobility, timing, and focused bursts to dismantle dangerous positions",quote:"Stillness first. Then the decisive motion."},
  paladin:{epithet:"Oathbound",awakening:["made a promise in a moment when breaking it would have been easier","stood between helpless people and a threat that expected them to move","discovered that conviction could become something almost physical"],duty:"stand between the innocent and the dark, then accept the cost of that position",burden:"judges personal failures against the impossible clarity of the oath",look:"well-kept armor, a shield or sacred device treated like a trust, and ceremonial details kept practical",combat:"holds the center, protects nearby allies, and commits sacred power when a strike truly matters",quote:"Stand between the innocent and the dark."},
  ranger:{epithet:"Warden",awakening:["tracked a danger everyone else had already decided was gone","learned that the ground itself could become an ally","guided others through a route that should have killed them"],duty:"see threats early, choose the ground, and bring people home",burden:"prefers solvable trails and clear signs to complicated motives",look:"layered field gear, repaired leather, route marks, and tools chosen for distance rather than display",combat:"controls range, marks priorities, uses terrain, and wastes neither movement nor ammunition",quote:"Watch the trail. Choose the ground. Never waste the shot."},
  rogue:{epithet:"Shadow",awakening:["escaped a locked place that was supposed to be impossible to leave","noticed the one weakness everyone stronger had overlooked","learned that survival often belonged to the person who saw the room most clearly"],duty:"use precision, nerve, and inconvenient knowledge against people who rely on power",burden:"expects betrayal quickly and trust slowly",look:"quiet gear, concealed tools, layered pockets, and nothing that catches light without a reason",combat:"creates advantage, strikes the exposed point, and disappears before retaliation can settle",quote:"Stay unseen. Strike once. Leave nothing behind."},
  sorcerer:{epithet:"Innate Arcane",awakening:["released magic before understanding what was happening","survived a surge of power that permanently changed how others looked at them","learned that emotion and magic were never entirely separate"],duty:"master an inherited or awakened power without letting it define every choice",burden:"fears losing control more than being outmatched",look:"ordinary travel gear interrupted by unmistakable signs of power: unusual light, heat, frost, static, or motion",combat:"reshapes spells through instinctive control and turns limited openings into overwhelming magical pressure",quote:"Power is not borrowed. It answers from within."},
  warlock:{epithet:"Eldritch",awakening:["accepted knowledge that came with terms","found an answer in a place sensible people would not have asked the question","survived an encounter that left a bargain where certainty used to be"],duty:"use dangerous access deliberately and make every bargain cost less than surrender would",burden:"never completely knows whether the next consequence has already been agreed to",look:"practical gear marked by one impossible detail: an eye-like seal, strange script, a token, or a shadow that seems too deliberate",combat:"uses pact magic, invocations, and relentless pressure while protecting scarce resources",quote:"Every bargain has a price. Make yours worth paying."},
  wizard:{epithet:"Arcane Scholar",awakening:["solved a magical problem that had resisted every shortcut","realized a page of notation could be as dangerous as a blade","learned that preparation could make impossible situations merely difficult"],duty:"turn knowledge into foresight before danger demands improvisation",burden:"can keep studying after action has become necessary",look:"annotated equipment, protected writing tools, a spellbook or equivalent archive, and small signs of constant revision",combat:"plans the field before the first spell, then spends exactly the right tool for the problem",quote:"Knowledge shapes the battlefield before steel is drawn."}
});

export const BACKGROUND_DOSSIER=Object.freeze({
  acolyte:{origin:"served a shrine, temple, or religious community where daily duty mattered more than ceremony",token:"a worn devotional token kept from those years",bond:"the people and vows of that religious community",mentor:"a patient elder who taught that belief without service was only decoration"},
  criminal:{origin:"learned survival among people who valued leverage, discretion, and useful skills",token:"an old coin, key, or coded mark from a life best discussed carefully",bond:"someone who once took a risk when abandoning them would have been easier",mentor:"a practical operator who taught the difference between being clever and being prepared"},
  sage:{origin:"spent years around records, teachers, experiments, or questions that refused easy answers",token:"a page of notes protected far more carefully than its appearance suggests",bond:"a question, archive, teacher, or discovery that still has unfinished consequences",mentor:"a demanding scholar who rewarded proof and distrusted convenient certainty"},
  soldier:{origin:"served in an organized fighting force where responsibility was measured in other people's lives",token:"a battered insignia or small campaign keepsake",bond:"the people who once stood in formation beside them",mentor:"a veteran who taught that discipline is what remains after courage becomes tired"}
});

export const STORY_EVENTS=Object.freeze(["a winter evacuation","a failed expedition","a night raid","a ruined crossing","a siege that lasted one day too long","a rescue no one expected to succeed","a contract that became a moral choice","a journey through country abandoned by everyone else"]);
export const STORY_PLACES=Object.freeze(["a roadside sanctuary","a river town","a border settlement","an old market district","a mountain pass","a forest hamlet","a fortified waystation","a remote archive"]);
