import { ABILITIES, SKILLS } from "../schema.js";
import { abilityMod } from "../rules/math.js";
import { buildQuickReference } from "../rules/reference-router.js";
import { CUNNING_STRIKE_OPTIONS_2024, rogueCunningStrikeDc } from "../rules/rogue.js";
import { natureWardResistance } from "../rules/druid.js";
import { speciesChoiceLabel } from "../rules/species.js";
import { RAW_2024 } from "../data/raw-2024.js";
import { wizardSpellsFor } from "../data/wizard-spells.js";
import { clericSpellsFor } from "../data/cleric-spells.js";
import { druidSpellsFor } from "../data/druid-spells.js";
import { druidFormById } from "../data/druid-forms.js";
import { paladinSpellsFor } from "../data/paladin-spells.js";
import { rangerSpellsFor, RANGER_DRUIDIC_WARRIOR_CANTRIPS_2024 } from "../data/ranger-spells.js";
import { selectPrintTheme } from "./theme.js";
import { buildQuickTurn } from "./quick-turn.js";
import { buildClassUtility } from "./class-utility.js";
import { normalizeSheetCustomization, sheetCustomizationClasses, sheetCustomizationStyle } from "./customization.js";
import { compactFeatureCards, compactRuleIndex, exportProfileFor } from "./profile.js";

const fmt=value=>value>=0?`+${value}`:`${value}`;
export function buildPremiumPrintModel(character){
  try{
    if(!character?.validation?.valid)throw new Error("Premium print requires a validated character.");
    const references=buildQuickReference(character),profile=exportProfileFor(character),theme=selectPrintTheme(character),species=speciesChoiceLabel(character),feat=chooseFeat(character,references),customization=normalizeSheetCustomization(character.presentation?.sheetCustomization);
    return{profile,theme,presentation:{customization,classes:sheetCustomizationClasses(customization),style:sheetCustomizationStyle(customization)},portraitDataUrl:customization.portraitVisible?safePortrait(character.presentation?.portraitDataUrl):null,identity:{name:character.name,level:character.level,classId:character.class.id,className:character.class.name,subclassName:character.subclass?.name||null,species,background:character.background.name,size:character.size},stats:{ac:character.ac,hp:character.hp,initiative:fmt(character.initiative),initiativeAdvantage:Boolean(character.initiativeAdvantage),speed:`${character.speed} ft`,proficiency:fmt(character.proficiency),passivePerception:character.passivePerception,hitDice:`${character.level}d${character.class.hitDie}`},abilities:ABILITIES.map(id=>({id,name:abilityName(id),score:character.abilities[id],modifier:fmt(abilityMod(character.abilities[id])),save:fmt(character.saveBonuses[id]),proficient:character.saves.includes(id)})),skills:Object.entries(SKILLS).map(([id,ability])=>({id,name:skillName(id),ability:ability.toUpperCase(),bonus:fmt(character.skillBonuses[id]),proficient:character.skills.includes(id),expertise:character.expertise.includes(id)})),attacks:(character.attacks||[]).slice(0,4).map(attack=>({name:attack.name,toHit:fmt(attack.attackBonus),damage:`${attack.damage}${fmt(attack.damageBonus)} ${attack.type}`})),feat,features:compactFeatureCards(references,feat?.name,profile.caster?7:8),ruleIndex:compactRuleIndex(references,48),rogueResources:roguePrintModel(character),druidSupport:druidPrintModel(character),rangerSupport:rangerPrintModel(character),classUtility:buildClassUtility(character),proficiencies:{saves:character.saves.map(abilityName),tools:[...(character.toolProficiencies||[])],languages:[...(character.languages||[])],masteries:masteryLabels(character)},equipment:equipmentLines(character.inventory||[]),spellcasting:spellcastingModel(character),spellPage:profile.caster?spellPageModel(character):null,quickTurn:buildQuickTurn(character),audit:auditModel(character),packet:{totalPages:profile.maxPages},motto:theme.motto};
  }catch(error){console.error("[print-model] build failed",error);throw error;}
}
function chooseFeat(character,references){try{const feat=character.feats?.[0];if(!feat)return null;const ref=references.find(item=>item.name===feat.name);return{name:feat.name,text:shorten(ref?.text||"Applied to this character.",190),source:ref?.source?`${ref.source.version} · p.${ref.source.page}`:null};}catch(error){console.error("[print-model] feat selection failed",error);throw error;}}
function auditModel(character){try{const a=character.audit;if(!a)throw new Error("Premium export requires Rules Audit data.");return{status:a.status,sourceMode:a.sourceMode,version:a.sourceVersion,rulesLabel:a.rulesLabel,rawIntegrity:Boolean(a.rawIntegrity),license:a.license,scope:a.scope,mechanics:(a.mechanics||[]).map(item=>({label:item.label,value:item.value,source:`${item.source.version} · p.${item.source.page}`})),checks:[...(a.checks||[])]};}catch(error){console.error("[print-model] audit failed",error);throw error;}}
function spellPageModel(character){try{if(!character.spells)return null;const catalog=spellCatalogRecords(character),byId=new Map(catalog.map(spell=>[spell.id,spell])),cantrips=new Set(character.spells.cantrips?.all||[]),known=new Set(character.spells.known?.all||[]),prepared=new Set(character.spells.prepared?.all||[]),always=new Set(character.spells.alwaysPrepared||[]),mastery=new Set(Object.values(character.spells.spellMastery||{}).filter(Boolean)),signature=new Set(character.spells.signatureSpells||[]),book=new Set(character.spells.spellbook?.all||[]),ids=character.class.id==="wizard"?[...cantrips,...book]:character.class.id==="ranger"&&character.ruleset==="2014"?[...known]:[...cantrips,...always,...prepared];const entries=[...new Set(ids)].map(id=>{const spell=byId.get(id);if(!spell)throw new Error(`Missing print spell ${id}.`);const tags=[];if(cantrips.has(id))tags.push("C");if(known.has(id))tags.push("K");if(prepared.has(id))tags.push("P");if(always.has(id))tags.push("A");if(mastery.has(id))tags.push("M");if(signature.has(id))tags.push("S");return{id,name:spell.name,level:spell.level,tags:tags.join("")||"B"};}).sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name));return{entries,source:spellSourceLabel(character),slots:Object.entries(character.spells.slots||{}).map(([level,count])=>`${level}:${count}`).join(" · "),ability:abilityName(character.spells.ability),saveDc:character.spells.saveDc,attackBonus:fmt(character.spells.attackBonus)};}catch(error){console.error("[print-model] spell page failed",error);throw error;}}
function druidPrintModel(character){
  try{
    if(character.class?.id!=="druid")return null;const d=character.druid,s=character.druidSelections||{};if(!d)throw new Error("Druid print requires progression state.");const ids=character.ruleset==="2014"?(s.fieldForms||[]):(s.knownForms||[]),forms=ids.map(id=>{const form=druidFormById(character.ruleset,id);return{id:form.id,name:form.name,size:form.size,cr:form.cr,ac:form.ac,hp:form.hp,speeds:Object.entries(form.speeds).filter(([,value])=>value).map(([kind,value])=>`${prettyChoice(kind)} ${value} ft`).join(" · "),senses:form.senses,traits:[...form.traits],actions:form.actions.map(action=>({name:action.name,toHit:action.toHit,damage:action.damage||null,effect:action.effect||null})),source:`${form.source.version} · p.${form.source.page}`};});
    return{ruleset:character.ruleset,fieldFormsAreExamples:Boolean(s.fieldFormsAreExamples),forms,wildShapeUses:d.unlimitedWildShape?"∞":d.wildShapeUses,wildShapeTempHp:d.wildShapeTempHp,maxCr:d.maxCr===.25?"1/4":d.maxCr===.5?"1/2":String(d.maxCr),durationHours:d.durationHours,allowSwim:d.allowSwim,allowFly:d.allowFly,primalOrder:prettyChoice(s.primalOrder),circleLand:prettyChoice(s.circleLand),elementalFury:prettyChoice(s.elementalFury),naturalRecovery:d.naturalRecovery,natureWardResistance:character.ruleset==="2024"?natureWardResistance(s.circleLand):null,landsAidDice:d.landsAidDice||0,beastSpells:Boolean(d.beastSpells),archdruid:Boolean(d.archdruid),preparedCount:character.spells?.prepared?.all?.length||0,alwaysPreparedCount:character.spells?.alwaysPrepared?.length||0};
  }catch(error){console.error("[print-model] Druid support failed",error);throw error;}
}
function rangerPrintModel(character){try{if(character.class?.id!=="ranger")return null;const r=character.ranger,s=character.rangerSelections||{};if(!r)throw new Error("Ranger print requires progression state.");return{ruleset:character.ruleset,favoredEnemies:(s.favoredEnemies||[]).map(prettyChoice),favoredEnemyLanguages:(s.favoredEnemyLanguages||[]).filter(Boolean),terrains:(s.naturalExplorerTerrains||[]).map(prettyChoice),huntersPrey:prettyChoice(s.huntersPrey),defensiveTactics:prettyChoice(s.defensiveTactics),multiattack:prettyChoice(s.multiattack),superiorDefense:prettyChoice(s.superiorDefense),hunterMarkFreeCasts:r.hunterMarkFreeCasts,hunterMarkDie:r.hunterMarkDie,expertiseCount:r.expertiseCount,speedBonus:r.speedBonus,tirelessUses:r.tirelessUses,natureVeilUses:r.natureVeilUses,knownCount:character.spells?.known?.all?.length||0,preparedCount:character.spells?.prepared?.all?.length||0,cantripCount:character.spells?.cantrips?.all?.length||0};}catch(error){console.error("[print-model] Ranger support failed",error);throw error;}}
function roguePrintModel(character){try{if(character.class?.id!=="rogue")return null;const rogue=character.rogue;if(!rogue)throw new Error("Rogue print requires progression state.");const is2024=character.ruleset==="2024",options=is2024?rogue.cunningStrikeOptions.map(id=>CUNNING_STRIKE_OPTIONS_2024.find(option=>option.id===id)).filter(Boolean).map(option=>({name:option.name,cost:`${option.cost}d6`,save:option.save?.toUpperCase()||null,effect:shorten(option.effect,90),requires:option.requires||null})):[];return{ruleset:character.ruleset,sneakAttack:`${rogue.sneakAttackDice}d6`,expertise:is2024?rogue.expertiseCount:rogueExpertiseLabel(character,rogue),masteries:rogue.masteryCount,cunningStrikeDc:is2024&&character.level>=5?rogueCunningStrikeDc(character):null,effectsPerSneak:is2024?rogue.maxCunningStrikeEffects:0,reliableTalent:Boolean(rogue.reliableTalent),blindsense:rogue.blindsenseRange?`${rogue.blindsenseRange} ft`:null,thiefReflexes:Boolean(rogue.thiefReflexes),options,scrollWarning:is2024&&character.subclass?.id==="thief"&&character.level>=13?"Spell Scrolls use Intelligence. Above level 1: Intelligence (Arcana) DC 10 + spell level; a failed check disintegrates the scroll.":null};}catch(error){console.error("[print-model] Rogue resources failed",error);throw error;}}
function rogueExpertiseLabel(character,rogue){const tool=character.expertise?.includes("Thieves' Tools"),skills=rogue.expertiseCount-(tool?1:0);return tool?`${skills} skills + Thieves’ Tools`:`${skills} skills`;}
function spellcastingModel(character){try{if(!character.spells)return null;const catalog=spellCatalog(character),names=ids=>(ids||[]).map(id=>catalog.get(id)||id),slots=Object.entries(character.spells.slots||{}).map(([level,count])=>`${level}:${count}`).join(" · ");return{ability:abilityName(character.spells.ability),saveDc:character.spells.saveDc,attackBonus:fmt(character.spells.attackBonus),slots,cantrips:names(character.spells.cantrips?.all),known:names(character.spells.known?.all),prepared:names(character.spells.prepared?.all),alwaysPrepared:names(character.spells.alwaysPrepared),spellbookCount:character.spells.spellbook?.all?.length||0};}catch(error){console.error("[print-model] spellcasting failed",error);throw error;}}
function spellCatalog(character){return new Map(spellCatalogRecords(character).map(spell=>[spell.id,spell.name]));}
function spellCatalogRecords(character){try{if(character.class.id==="cleric")return clericSpellsFor(character.ruleset);if(character.class.id==="druid")return druidSpellsFor(character.ruleset,{includeCircle:true});if(character.class.id==="wizard")return wizardSpellsFor(character.ruleset);if(character.class.id==="paladin"){const base=[...paladinSpellsFor(character.ruleset)];if(character.ruleset==="2024")base.push(...clericSpellsFor("2024").filter(spell=>spell.level===0));return base;}if(character.class.id==="ranger"){const base=[...rangerSpellsFor(character.ruleset)];if(character.ruleset==="2024")base.push(...RANGER_DRUIDIC_WARRIOR_CANTRIPS_2024);return base;}return[];}catch(error){console.error("[print-model] spell catalog resolution failed",error);throw error;}}
function spellSourceLabel(character){try{if(character.class.id==="cleric"&&character.ruleset==="2014")return`${character.audit.sourceVersion} · Cleric spell list pp.106–107`;if(character.class.id==="druid")return`${character.audit.sourceVersion} · Druid spell list pp.${character.ruleset==="2014"?"107–108":"44–45"}`;if(character.class.id==="paladin")return`${character.audit.sourceVersion} · Paladin spell list pp.${character.ruleset==="2014"?"108–109":"55–56"}`;if(character.class.id==="ranger")return`${character.audit.sourceVersion} · Ranger spell list p.${character.ruleset==="2014"?"109":"60"}`;return`${character.audit.sourceVersion} · validated ${character.class.name} spell catalog`;}catch(error){console.error("[print-model] spell source label failed",error);throw error;}}
function masteryLabels(character){try{if(character.ruleset!=="2024")return[];return(character.masteryIds||[]).map(id=>{const weapon=RAW_2024.weapons[id];if(!weapon?.mastery)throw new Error(`Missing print Weapon Mastery data for ${id}.`);return`${weapon.name} — ${weapon.mastery}`;});}catch(error){console.error("[print-model] Weapon Mastery labels failed",error);throw error;}}
function safePortrait(value){const portrait=String(value||"");return /^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(portrait)?portrait:null;}
function equipmentLines(items){return items.slice(0,11).map(item=>`${item.quantity>1?`${item.quantity} × `:""}${item.name}`);}
function shorten(value,max){const text=String(value||"").replace(/\s+/g," ").trim();return text.length<=max?text:`${text.slice(0,max-1).trimEnd()}…`;}
function abilityName(id){return({str:"Strength",dex:"Dexterity",con:"Constitution",int:"Intelligence",wis:"Wisdom",cha:"Charisma"})[id]||String(id||"");}
function skillName(id){return String(id).replace(/([A-Z])/g," $1").replace(/^./,char=>char.toUpperCase());}
function prettyChoice(value){return value?String(value).replace(/-/g," ").replace(/\b\w/g,char=>char.toUpperCase()):null;}
