import { rogueCunningStrikeDc } from "../rules/rogue.js";

export function buildQuickTurn(character){
  try{
    const builders={barbarian:barbarianTurn,paladin:paladinTurn,ranger:rangerTurn,druid:druidTurn,fighter:fighterTurn,wizard:wizardTurn,cleric:clericTurn,rogue:rogueTurn};
    return (builders[character?.class?.id]||defaultTurn)(character).slice(0,3);
  }catch(error){console.error("[print-quick-turn] build failed",error);return defaultTurn(character);}
}
function barbarianTurn(character){try{const b=character.barbarian;if(!b)throw new Error("Barbarian Quick Turn requires progression data.");const rage=b.unlimitedRage?"unlimited Rage":`${b.rageUses} Rage use${b.rageUses===1?"":"s"}`,steps=[`Enter Rage when the fight justifies it; you have ${rage} and deal +${b.rageDamage} qualifying Rage damage.`];if(character.level>=9&&character.ruleset==="2024")steps.push(`Use Reckless Attack deliberately; on one eligible hit, Brutal Strike can trade its Advantage for +${b.brutalStrikeDice}d10 and ${b.brutalStrikeEffectCount} effect${b.brutalStrikeEffectCount===1?"":"s"}.`);else if(character.level>=2)steps.push("Use Reckless Attack when Advantage is worth giving enemies Advantage against you until your next turn.");else steps.push("Close distance, attack with Strength, and use Rage resistance to hold the dangerous space.");if(b.frenzy)steps.push(character.ruleset==="2014"?"If you chose Frenzy, remember the bonus-action melee attack starts on later turns and Exhaustion arrives when Rage ends.":`Berserker Frenzy adds ${b.rageDamage}d6 to your first Strength-based hit each turn when Reckless Attack is active during Rage.`);else if(b.relentlessRage)steps.push(`Relentless Rage can keep you standing at ${b.relentlessRageHp} HP if its Constitution save succeeds.`);else steps.push("End your turn where your Rage resistance and threat protect the rest of the party.");return steps;}catch(error){console.error("[print-quick-turn] Barbarian turn failed",error);throw error;}}
function paladinTurn(character){try{const p=character.paladin;if(!p)throw new Error("Paladin Quick Turn requires progression data.");const steps=[];steps.push(p.auraProtection?`Fight where allies can stay inside your ${p.auraRange}-ft aura and benefit from its saving-throw bonus.`:"Protect the front line and preserve position for the allies who need you most.");if(character.ruleset==="2014"){if(p.divineSmite)steps.push("After a melee weapon hit, decide whether the target is important enough to spend a spell slot on Divine Smite.");else steps.push("Use Lay on Hands as an action when its healing or poison/disease cure changes the fight.");steps.push(p.channelDivinityUses?"Use Sacred Weapon when its 1-minute attack bonus will pay off across several attacks; keep Turn the Unholy for Fiends or Undead.":"Keep Lay on Hands available for emergency healing instead of spending the pool too early.");return steps;}if(p.paladinsSmite)steps.push("Use your free Divine Smite cast on a hit that matters; save spell slots when the free casting can do the job.");else steps.push("Use Lay On Hands as a Bonus Action when emergency healing is worth part of your pool.");if(p.channelDivinityUses)steps.push(p.sacredWeapon?"Spend Channel Divinity on Sacred Weapon when the 10-minute attack bonus will matter; Divine Sense and Abjure Foes compete for the same resource.":"Spend Channel Divinity on Divine Sense or Abjure Foes only when the information or control will materially change the encounter.");else steps.push("Use your Weapon Masteries and prepared spells to create value without wasting limited resources.");return steps;}catch(error){console.error("[print-quick-turn] Paladin turn failed",error);throw error;}}
function rangerTurn(character){try{const r=character.ranger,s=character.rangerSelections||{};if(!r)throw new Error("Ranger Quick Turn requires progression data.");if(character.ruleset==="2014"){const prey=s.huntersPrey?pretty(s.huntersPrey):null,steps=[r.attacksPerAction>1?`Choose the best lane for ${r.attacksPerAction} weapon attacks; keep range or cover where your Hunter plan works best.`:"Use terrain, range, and cover to make your weapon attack from the position that is hardest to punish."];steps.push(character.spells?`Spend one of your ${r.known} known Ranger spells only when it beats your reliable weapon turn; your spell choices stay fixed until a Ranger level lets you replace one.`:"At level 1, lean on Favored Enemy, Natural Explorer, and weapon positioning; Ranger spellcasting begins at level 2.");steps.push(prey?`Apply ${prey} deliberately; keep your favored-enemy and favored-terrain advantages in mind when the encounter shifts into tracking or exploration.`:"Use Favored Enemy and Natural Explorer whenever tracking, recall, travel, or foraging becomes the objective.");return steps;}const steps=[`Mark the priority target with Hunter's Mark when the fight merits it; you have ${r.hunterMarkFreeCasts} free cast${r.hunterMarkFreeCasts===1?"":"s"} per Long Rest and its extra die is ${r.hunterMarkDie}.`];steps.push(r.preciseHunter?"Attack the marked target with Advantage from Precise Hunter, then apply your best Weapon Mastery to control the next exchange.":`Attack the marked target and use one of your ${r.masteryCount} Weapon Masteries to create positional or damage value.`);if(r.natureVeil)steps.push(`Use Nature's Veil (${r.natureVeilUses}/Long Rest) when one Bonus Action of invisibility through the end of your next turn creates a decisive attack or escape.`);else if(r.tireless)steps.push(`Use Tireless (${r.tirelessUses}/Long Rest) when its temporary HP matters, and remember a Short Rest also reduces Exhaustion by 1.`);else if(r.roving)steps.push(`Exploit Roving: your Speed is +${r.speedBonus} ft and your Climb/Swim Speeds match it while not in Heavy armor.`);else steps.push("Keep the marked target in reach and preserve concentration while using prepared spells only when they outperform another weapon turn.");return steps;}catch(error){console.error("[print-quick-turn] Ranger turn failed",error);throw error;}}
function druidTurn(character){
  try{
    const d=character.druid,s=character.druidSelections||{};if(!d)throw new Error("Druid Quick Turn requires progression data.");const uses=d.unlimitedWildShape?"unlimited Wild Shape":`${d.wildShapeUses} Wild Shape use${d.wildShapeUses===1?"":"s"}`;
    const steps=[`Lead with the prepared spell that most changes the encounter; protect Concentration and keep ${uses} in reserve when transformation will solve positioning, scouting, or survival better.`];
    if(character.ruleset==="2014"){
      steps.push(d.wildShapeUses?`Wild Shape into an eligible Beast you have seen (max CR ${d.maxCr}); the listed field forms are examples, not your complete RAW option list.`:"At level 1, play as a full caster; Wild Shape begins at Druid level 2.");
      steps.push(d.naturalRecovery?`After a Short Rest, Natural Recovery can restore up to ${d.naturalRecovery} total spell-slot levels; your Circle land is ${pretty(s.circleLand||"none")}.`:"Use cantrips and terrain control to preserve spell slots when the encounter does not justify them.");
      return steps;
    }
    steps.push(d.wildShapeUses?`Choose among your ${d.knownFormCount} known Wild Shape forms (max CR ${d.maxCr}); transforming grants ${d.wildShapeTempHp} Temporary HP and keeps your own Hit Points.`:"At level 1, use your Primal Order and full spellcasting; Wild Shape starts at level 2.");
    if(d.wildResurgence)steps.push(`Wild Resurgence lets Wild Shape and spell slots support each other; pair it with ${s.elementalFury?pretty(s.elementalFury):"your Elemental Fury choice"} when the turn needs offense instead of control.`);else if(d.wildCompanion)steps.push("Wild Companion can spend Wild Shape for Find Familiar when scouting or utility is more valuable than transforming yourself.");else steps.push(`Your Primal Order is ${pretty(s.primalOrder||"chosen")}; use that benefit while preserving spell slots for encounter-changing magic.`);
    return steps;
  }catch(error){console.error("[print-quick-turn] Druid turn failed",error);throw error;}
}
function fighterTurn(character){const attacks=character.fighter?.attacksPerAction||1,steps=[`Take the Attack action: ${attacks} attack${attacks===1?"":"s"} with your best weapon.`];if(character.fighter?.actionSurgeUses)steps.push("Use Action Surge when another action can swing the fight.");else steps.push("Keep pressure on the highest-priority target and protect your positioning.");if(character.fighter?.secondWindUses)steps.push(character.ruleset==="2014"?"Use Second Wind when its self-healing matters most.":"Use Second Wind when the healing and repositioning value matter most.");else steps.push("Use your class resources before the fight is already decided.");return steps;}
function wizardTurn(character){const dc=character.spells?.saveDc,third=character.ruleset==="2014"?"Protect concentration and keep distance; after a Short Rest, use Arcane Recovery when recovered spell slots will matter.":character.level>=5?"Protect concentration and keep distance; use Memorize Spell after a Short Rest when preparation needs change.":"Protect concentration and keep distance from melee threats.";return[`Choose the spell that changes the battlefield most${dc?` (save DC ${dc})`:""}.`,"Use a cantrip when the encounter does not justify spending a spell slot.",third];}
function clericTurn(character){const steps=["Decide early whether the fight needs concentration, damage, support, or recovery."];if(character.cleric?.channelDivinityUses){const options=character.ruleset==="2014"?"Turn Undead or Preserve Life":"Divine Spark, Turn Undead, or your domain option";steps.push(`You have ${character.cleric.channelDivinityUses} Channel Divinity uses; spend them when ${options} creates real value.`);}else steps.push("Use your best prepared spell or cantrip while preserving positioning.");steps.push(character.subclass?.id==="life-domain"?"Keep a fast healing option available for an ally who suddenly drops.":"Keep a recovery option available for a sudden emergency.");return steps;}
function rogueTurn(character){try{const steps=[`Set up Sneak Attack${character.rogue?.sneakAttackDice?` (${character.rogue.sneakAttackDice}d6)`:""} before choosing your target.`];if(character.ruleset==="2014"){if(character.level>=2)steps.push("Use Cunning Action to Dash, Disengage, or Hide when positioning creates more value than standing still.");else steps.push("Use normal movement and cover to preserve the position needed for your next Sneak Attack.");if(character.subclass?.id==="thief"&&character.level>=17)steps.push("In round one, plan around Thief’s Reflexes: your second turn happens at Initiative minus 10 unless you are surprised.");else if(character.subclass?.id==="thief"&&character.level>=3)steps.push("Use Fast Hands or Cunning Action to create position and tempo without giving up your action.");else steps.push("End your turn where enemies must spend movement or actions to reach you.");return steps;}if(character.level>=5)steps.push(`Use Cunning Strike (DC ${rogueCunningStrikeDc(character)}) only when its effect is worth giving up Sneak Attack dice.`);else if(character.level>=2)steps.push("Use Cunning Action to Dash, Disengage, or Hide when positioning creates more value than standing still.");else steps.push("Use normal movement and cover to preserve the position needed for your next Sneak Attack.");if(character.level>=3)steps.push("Use Cunning Action for positioning; if you have not moved, Steady Aim can create Advantage for the next attack this turn.");else steps.push("End your turn where enemies must spend movement or actions to reach you.");return steps;}catch(error){console.error("[print-quick-turn] Rogue turn failed",error);throw error;}}
function defaultTurn(){return["Use your strongest reliable action for the current objective.","Spend limited resources only when they materially improve the outcome.","End your turn in a position that helps the party and limits enemy options."];}
function pretty(value){return String(value||"").replace(/-/g," ").replace(/\b\w/g,char=>char.toUpperCase());}
