import { createInitialState } from "./state.js";
import { SOURCE, RANDOM } from "./schema.js";
import { generateForSystem } from "./systems/generate.js";
import { DND_SYSTEM_ID } from "./systems/dnd.js";
import { savePregen } from "./library/local-library.js";
import { renderCharacter } from "./ui/render.js";
import { populateOptions, populateClasses, populateLevels, populateSubclasses } from "./ui/options.js";
import { bindPregenLibrary, renderPregenLibrary } from "./ui/library.js";
import { bindSpellPicker, refreshSpellPicker } from "./ui/spell-picker.js";
import { bindAdvancementPicker, refreshAdvancementPicker, resetAdvancementSelections } from "./ui/advancement-picker.js";

const state=createInitialState(),constraintIds=["level","species","class","subclass","background","name"];
function boot(){try{enforceRawState();populateOptions(state);bindConstraints();bindTabs();bindResultActions();bindPregenLibrary({onView:viewSavedPregen,showToast});bindSpellPicker(state,showToast);bindAdvancementPicker(state);refreshAdvancementPicker(state);document.getElementById("forgeButton").addEventListener("click",forge);forge();}catch(error){showError(error);}}
function enforceRawState(){try{state.systemId=state.systemId||DND_SYSTEM_ID;state.sourceMode=SOURCE.RAW;state.homebrew=[];}catch(error){console.error("[app] RAW state enforcement failed",error);throw error;}}
function bindConstraints(){
  try{
    constraintIds.forEach(id=>document.getElementById(id).addEventListener("change",event=>{state.constraints[id]=event.target.value;}));
    document.getElementById("name").addEventListener("input",event=>{state.constraints.name=event.target.value;});
    document.getElementById("class").addEventListener("change",()=>{state.constraints.subclass=RANDOM;state.spellSelections=emptySpells();resetAdvancementSelections(state);populateLevels(state);populateSubclasses(state);refreshSpellPicker(state);refreshAdvancementPicker(state);});
    document.getElementById("level").addEventListener("change",()=>{state.spellSelections=emptySpells();trimAdvancementSelections();populateClasses(state);populateSubclasses(state);refreshSpellPicker(state);refreshAdvancementPicker(state);});
    document.getElementById("ruleset").addEventListener("change",event=>{state.ruleset=event.target.value;state.constraints.species=RANDOM;state.constraints.class=RANDOM;state.constraints.subclass=RANDOM;state.constraints.background=RANDOM;state.constraints.level=RANDOM;state.spellSelections=emptySpells();resetAdvancementSelections(state);enforceRawState();populateOptions(state);refreshSpellPicker(state);refreshAdvancementPicker(state);});
  }catch(error){console.error("[app] bindConstraints failed",error);throw error;}
}
function trimAdvancementSelections(){try{if(state.constraints.level===RANDOM)return;const level=Number(state.constraints.level);for(const key of Object.keys(state.advancementSelections))if(Number(key)>level)state.advancementSelections[key]=RANDOM;}catch(error){console.error("[app] advancement trim failed",error);throw error;}}
function bindTabs(){try{document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>showTab(button.dataset.tab)));}catch(error){console.error("[app] bindTabs failed",error);throw error;}}
function showTab(name){try{if(!["forge","pregens"].includes(name))throw new Error("Production Character Forge exposes RAW Forge and Pregens only.");document.querySelectorAll("[data-tab]").forEach(item=>item.classList.toggle("is-active",item.dataset.tab===name));document.querySelectorAll("[data-view]").forEach(view=>view.hidden=view.dataset.view!==name);if(name==="pregens")renderPregenLibrary();}catch(error){console.error("[app] showTab failed",error);throw error;}}
function bindResultActions(){try{document.getElementById("result").addEventListener("click",async event=>{try{const action=event.target.closest("[data-action]")?.dataset.action;if(action==="reroll")forge();if(action==="print")window.print();if(action==="save"){if(state.currentCharacter?.sourceMode!==SOURCE.RAW||state.currentCharacter?.homebrew?.length)throw new Error("Only validated RAW characters can be saved.");const entry=await savePregen(state.currentCharacter);renderPregenLibrary();showToast(`${entry.name} saved to My Pregens.`);}}catch(error){showToast(error.message,true);}});}catch(error){console.error("[app] bindResultActions failed",error);throw error;}}
function viewSavedPregen(entry){try{const character=structuredClone(entry.character);if(character.sourceMode!==SOURCE.RAW||character.homebrew?.length)throw new Error("Production Character Forge opens RAW pregens only.");state.currentCharacter=character;state.systemId=character.systemId||DND_SYSTEM_ID;state.sourceMode=SOURCE.RAW;state.ruleset=character.ruleset;state.constraints={level:String(character.level),species:character.species.id,class:character.class.id,subclass:character.subclass?.id||RANDOM,background:character.background.id,name:character.name};state.spellSelections=character.spells?{cantrips:[...character.spells.cantrips.all],spellbook:[...(character.spells.spellbook?.all||[])],prepared:[...character.spells.prepared.all]}:emptySpells();state.advancementSelections=emptyAdvancements();for(const choice of character.advancementChoices||[])if(choice.locked)state.advancementSelections[choice.level]=choice.id||"asi";state.homebrew=[];syncControls();renderCharacter(character,document.getElementById("result"));showTab("forge");showToast(`${character.name} opened from My Pregens.`);}catch(error){console.error("[app] opening pregen failed",error);showToast(error.message,true);}}
function syncControls(){try{enforceRawState();document.getElementById("ruleset").value=state.ruleset;populateOptions(state);for(const id of constraintIds){const element=document.getElementById(id);if(element)element.value=state.constraints[id];}refreshSpellPicker(state);refreshAdvancementPicker(state);}catch(error){console.error("[app] syncControls failed",error);throw error;}}
function forge(){const button=document.getElementById("forgeButton");try{enforceRawState();button.classList.add("is-forging");document.getElementById("error").hidden=true;state.currentCharacter=generateForSystem(state);if(state.currentCharacter.sourceMode!==SOURCE.RAW||state.currentCharacter.homebrew?.length)throw new Error("RAW validation rejected the generated character.");renderCharacter(state.currentCharacter,document.getElementById("result"));}catch(error){showError(error);}finally{window.setTimeout(()=>button.classList.remove("is-forging"),160);}}
function emptySpells(){return{cantrips:[],spellbook:[],prepared:[]};}
function emptyAdvancements(){return{4:RANDOM,6:RANDOM,8:RANDOM,10:RANDOM,12:RANDOM,14:RANDOM,16:RANDOM,19:RANDOM};}
function showError(error){console.error("[app]",error);const element=document.getElementById("error");element.textContent=error.message;element.hidden=false;}
function showToast(message,isError=false){try{const toast=document.getElementById("toast");toast.textContent=message;toast.classList.toggle("is-error",isError);toast.hidden=false;window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>{toast.hidden=true;},3600);}catch(error){console.error("[app] showToast failed",error);}}
boot();