import { createInitialState } from "./state.js";
import { SOURCE } from "./schema.js";
import { generateCharacter } from "./rules/generator.js";
import { createAbilityFeat } from "./rules/homebrew.js";
import { savePregen } from "./library/local-library.js";
import { renderCharacter } from "./ui/render.js";
import { exportCharacterPdf } from "./ui/print.js";
import { populateOptions, populateLevels, populateSubclasses } from "./ui/options.js";
import { bindSpeciesOptions, renderSpeciesOptions, resetSpeciesOptions } from "./ui/species-options.js";
import { bindBackgroundOptions, renderBackgroundOptions, resetBackgroundOptions } from "./ui/background-options.js";
import { bindClassOptions, renderClassOptions, resetClassOptions, clearIllegalClassSelectionsForLevel } from "./ui/class-options.js";
import { bindPortraitUpload, renderPortraitUpload, restorePortraitFromCharacter, applyPortraitToCurrent } from "./ui/portrait-upload.js";
import { bindSheetCustomizer, renderSheetCustomizer, restoreSheetCustomizationFromCharacter, applySheetCustomizationToCurrent } from "./ui/sheet-customizer.js";
import { bindPregenLibrary, renderPregenLibrary } from "./ui/library.js";
import { bindHomebrewLibrary, renderHomebrewLibrary } from "./ui/homebrew-library.js";
import { bindSpellPicker, refreshSpellPicker } from "./ui/spell-picker.js";

const state=createInitialState(),constraintIds=["level","species","class","subclass","background","name"];
function boot(){try{populateOptions(state);bindConstraints();bindMode();bindTabs();bindHomebrew();bindResultActions();bindPregenLibrary({onView:viewSavedPregen,showToast});bindHomebrewLibrary({onUse:useSavedHomebrew,showToast});bindSpeciesOptions(state);bindBackgroundOptions(state);bindClassOptions(state,{onChange:()=>refreshSpellPicker(state),showToast});bindPortraitUpload(state,showToast);bindSheetCustomizer(state,showToast);bindSpellPicker(state,showToast);document.getElementById("forgeButton").addEventListener("click",forge);forge();}catch(error){showError(error);}}
function bindConstraints(){try{constraintIds.forEach(id=>document.getElementById(id).addEventListener("change",event=>{state.constraints[id]=event.target.value;}));document.getElementById("name").addEventListener("input",event=>{state.constraints.name=event.target.value;});document.getElementById("species").addEventListener("change",()=>resetSpeciesOptions(state));document.getElementById("background").addEventListener("change",()=>resetBackgroundOptions(state));document.getElementById("class").addEventListener("change",()=>{state.constraints.subclass="random";state.classSelections={};populateLevels(state);populateSubclasses(state);renderClassOptions(state);renderSheetCustomizer(state);refreshSpellPicker(state);});document.getElementById("level").addEventListener("change",()=>{populateSubclasses(state);clearIllegalClassSelectionsForLevel(state);refreshSpellPicker(state);});document.getElementById("ruleset").addEventListener("change",event=>{state.ruleset=event.target.value;state.constraints.species="random";state.constraints.class="random";state.constraints.subclass="random";state.constraints.background="random";state.speciesSelections={};state.backgroundSelections={};state.classSelections={};state.spellSelections=emptySpells();populateOptions(state);renderSpeciesOptions(state);renderBackgroundOptions(state);renderClassOptions(state);renderSheetCustomizer(state);});}catch(error){console.error("[app] bindConstraints failed",error);throw error;}}
function bindMode(){try{document.getElementById("sourceMode").addEventListener("change",event=>{state.sourceMode=event.target.value;document.getElementById("homebrewPanel").hidden=state.sourceMode!==SOURCE.HOMEBREW;});}catch(error){console.error("[app] bindMode failed",error);throw error;}}
function bindTabs(){try{document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>showTab(button.dataset.tab)));}catch(error){console.error("[app] bindTabs failed",error);throw error;}}
function showTab(name){try{document.querySelectorAll("[data-tab]").forEach(item=>item.classList.toggle("is-active",item.dataset.tab===name));document.querySelectorAll("[data-view]").forEach(view=>view.hidden=view.dataset.view!==name);if(name==="pregens")renderPregenLibrary();if(name==="homebrew")renderHomebrewLibrary();}catch(error){console.error("[app] showTab failed",error);throw error;}}
function bindHomebrew(){try{document.getElementById("addHomebrew").addEventListener("click",()=>{try{const item=createAbilityFeat({name:document.getElementById("hbName").value,ability:document.getElementById("hbAbility").value,amount:document.getElementById("hbAmount").value});if(state.homebrew.some(value=>value.name.trim().toLowerCase()===item.name.trim().toLowerCase()))throw new Error(`Homebrew named "${item.name}" is already active.`);state.homebrew.push(item);renderActiveHomebrew();}catch(error){showError(error);}});}catch(error){console.error("[app] bindHomebrew failed",error);throw error;}}
function bindResultActions(){try{document.getElementById("result").addEventListener("click",async event=>{try{const action=event.target.closest("[data-action]")?.dataset.action;if(action==="reroll")forge();if(action==="print")await exportCharacterPdf(state.currentCharacter);if(action==="save"){const entry=await savePregen(state.currentCharacter);renderPregenLibrary();showToast(`${entry.name} saved to My Pregens.`);}}catch(error){showToast(error.message,true);}});}catch(error){console.error("[app] bindResultActions failed",error);throw error;}}
function viewSavedPregen(entry){
  try{const character=structuredClone(entry.character);state.currentCharacter=character;state.sourceMode=character.sourceMode;state.ruleset=character.ruleset;state.constraints={level:String(character.level),species:character.species.id,class:character.class.id,subclass:character.subclass?.id||"random",background:character.background.id,name:character.name};state.speciesSelections={...(character.speciesChoices||{})};if(character.ruleset==="2024")state.speciesSelections.size=character.size;state.backgroundSelections=character.ruleset==="2024"?{...(character.backgroundChoices||{})}:{};state.classSelections=character.ruleset==="2024"&&character.class.id==="cleric"?Object.fromEntries(Object.entries({divineOrder:character.divineOrder,blessedStrikes:character.blessedStrikes}).filter(([,value])=>value)):{};state.spellSelections=character.spells?{cantrips:[...character.spells.cantrips.all],spellbook:[...(character.spells.spellbook?.all||[])],prepared:[...character.spells.prepared.all],masteryLevel1:character.spells.spellMastery?.level1||null,masteryLevel2:character.spells.spellMastery?.level2||null,signatureSpells:[...(character.spells.signatureSpells||[])]}:emptySpells();state.homebrew=structuredClone(character.homebrew||[]);restorePortraitFromCharacter(state,character);restoreSheetCustomizationFromCharacter(state,character);syncControls();renderCharacter(character,document.getElementById("result"));showTab("forge");showToast(`${character.name} opened from My Pregens.`);}
  catch(error){console.error("[app] opening pregen failed",error);showToast(error.message,true);}
}
function useSavedHomebrew(entry){try{if(state.homebrew.some(item=>item.name.trim().toLowerCase()===entry.name.trim().toLowerCase()))throw new Error(`${entry.name} is already active in Forge.`);if(state.ruleset!==entry.ruleset){state.ruleset=entry.ruleset;state.constraints.species="random";state.constraints.class="random";state.constraints.subclass="random";state.constraints.background="random";state.speciesSelections={};state.backgroundSelections={};state.classSelections={};state.spellSelections=emptySpells();}state.sourceMode=SOURCE.HOMEBREW;state.homebrew.push(structuredClone(entry.item));syncControls();showTab("forge");showToast(`${entry.name} is active in ${entry.ruleset} Homebrew mode.`);}catch(error){console.error("[app] using Homebrew failed",error);showToast(error.message,true);}}
function syncControls(){try{document.getElementById("sourceMode").value=state.sourceMode;document.getElementById("ruleset").value=state.ruleset;populateOptions(state);for(const id of constraintIds){const element=document.getElementById(id);if(element)element.value=state.constraints[id];}renderSpeciesOptions(state);renderBackgroundOptions(state);renderClassOptions(state);renderPortraitUpload(state);renderSheetCustomizer(state);document.getElementById("homebrewPanel").hidden=state.sourceMode!==SOURCE.HOMEBREW;renderActiveHomebrew();refreshSpellPicker(state);}catch(error){console.error("[app] syncControls failed",error);throw error;}}
function renderActiveHomebrew(){const node=document.getElementById("hbList");if(node)node.textContent=state.homebrew.length?`Active: ${state.homebrew.map(value=>value.name).join(", ")}`:"";}
function forge(){const button=document.getElementById("forgeButton");try{button.classList.add("is-forging");document.getElementById("error").hidden=true;state.currentCharacter=generateCharacter(state);applyPortraitToCurrent(state);applySheetCustomizationToCurrent(state);renderCharacter(state.currentCharacter,document.getElementById("result"));}catch(error){showError(error);}finally{window.setTimeout(()=>button.classList.remove("is-forging"),160);}}
function emptySpells(){return{cantrips:[],spellbook:[],prepared:[],masteryLevel1:null,masteryLevel2:null,signatureSpells:[]};}
function showError(error){console.error("[app]",error);const element=document.getElementById("error");element.textContent=error.message;element.hidden=false;}
function showToast(message,isError=false){try{const toast=document.getElementById("toast");toast.textContent=message;toast.classList.toggle("is-error",isError);toast.hidden=false;window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>{toast.hidden=true;},3600);}catch(error){console.error("[app] showToast failed",error);}}
boot();
